import {ROLE_CONFIG,ROUTES,ICONS,MOBILE_PRIMARY,PUBLIC_ROUTES,routeTitle} from './config.js';
import {loadState,saveState,resetState,signupDemoState} from './store.js';
import {canOpen,visibleNavigation} from './permissions.js';
import {readRoute,navigate,isKnownRoute} from './router.js';
import {homeScreen,placeholderScreen,statesScreen,notFoundScreen,deniedScreen} from './screens.js';
import {welcomeScreen,signupScreen,otpScreen,recoveryScreen,invitationsScreen} from './onboarding.js';
import {normalizeMobile,validateMobile,isKnownMobile,otpStatus,canResend} from './identity.js';
import {businessStartScreen,businessDetailsScreen,businessKycScreen,branchesScreen,bankScreen,applicationStatusScreen,businessDashboardScreen,serviceExpansionScreen,adminApprovalsScreen,applicationReviewScreen} from './business.js';
import {requiredKyc,validateServices,validateBank,workspaceForServices,maskAccount} from './business-rules.js';

let state=loadState();
const $=id=>document.getElementById(id);
const app=$('app'),main=$('main-content'),sidebar=$('sidebar'),backdrop=$('sidebar-backdrop');

function navButton(route,label,badge=0,mobile=false){return `<button type="button" class="nav-button" data-route="${route}" aria-label="${label}"><span class="nav-icon" aria-hidden="true">${ICONS[route]||'□'}</span><span class="nav-label">${label}</span>${badge&&!mobile?`<span class="nav-badge">${badge}</span>`:''}</button>`}
function roleForWorkspace(key){const base=ROLE_CONFIG[key]||ROLE_CONFIG.personal;const override=state.workspaceOverrides?.[key];return override?{...base,...override}:base}
function currentRole(){return roleForWorkspace(state.currentWorkspace)}
function renderWorkspace(){const r=currentRole();$('workspace-icon').textContent=r.icon;$('workspace-name').textContent=r.label;$('workspace-role').textContent=r.subtitle;$('page-context').textContent=r.label;$('branch-button').hidden=!r.branches}
function renderDesktopNav(){const badges=state.badges?.[state.currentWorkspace]||{};$('desktop-nav').innerHTML=visibleNavigation(state.currentWorkspace).map(([id,label])=>navButton(id,label,badges[id])).join('');markActive()}
function renderMobileNav(){const nav=visibleNavigation(state.currentWorkspace);const map=new Map(nav);const primary=MOBILE_PRIMARY.filter(id=>map.has(id));if(!primary.includes('home'))primary.unshift('home');const shown=primary.slice(0,4);$('mobile-nav').innerHTML=shown.map(id=>navButton(id,map.get(id),0,true)).join('')+navButton('more','More',0,true);markActive()}
function renderMore(){const nav=visibleNavigation(state.currentWorkspace);const primary=new Set(MOBILE_PRIMARY);$('more-list').innerHTML=nav.filter(([id])=>!primary.has(id)).map(([id,label])=>`<button type="button" class="more-option" data-route="${id}"><span class="workspace-icon" aria-hidden="true">${ICONS[id]||'□'}</span><span class="workspace-copy"><b>${label}</b><small>Open ${label}</small></span><span aria-hidden="true">›</span></button>`).join('')+`<button type="button" class="more-option" data-route="states"><span class="workspace-icon">◇</span><span class="workspace-copy"><b>Screen states</b><small>P0 test lab</small></span><span>›</span></button>`}
function markActive(){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.currentRoute))}
function renderWorkspaceList(){const options=state.workspaces.map(k=>{const r=roleForWorkspace(k);if(!r)return '';return `<button type="button" class="workspace-option ${k===state.currentWorkspace?'current':''}" data-workspace="${k}"><span class="workspace-icon">${r.icon}</span><span class="workspace-copy"><b>${r.label}</b><small>${r.subtitle}</small></span>${k===state.currentWorkspace?'<span class="status-pill">Current</span>':'<span>›</span>'}</button>`}).join('');const pending=state.invitations?.filter(x=>x.status==='pending').length||0;$('workspace-list').innerHTML=options+`<button type="button" class="workspace-option invitation-entry" data-workspace-action="invitations"><span class="workspace-icon">✉</span><span class="workspace-copy"><b>Pending invitations</b><small>${pending} waiting for review</small></span><span class="status-pill info">${pending}</span></button><button type="button" class="workspace-option add-business-entry" data-workspace-action="add-business"><span class="workspace-icon">+</span><span class="workspace-copy"><b>Add business profile</b><small>One business can enable several services</small></span><span>›</span></button>`}

function closeOverlays(){$('workspace-dialog').hidden=true;$('more-sheet').hidden=true;sidebar.classList.remove('open');backdrop.hidden=true}
function openWorkspaceDialog(){renderWorkspaceList();$('workspace-dialog').hidden=false;$('workspace-list').querySelector('button')?.focus()}
function openMore(){renderMore();$('more-sheet').hidden=false;$('more-list').querySelector('button')?.focus()}
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}

function renderRoute(){
  let route=readRoute();const authenticated=state.auth?.status==='authenticated';
  if(!authenticated&&!PUBLIC_ROUTES.has(route)){location.hash='#/welcome';return}
  if(authenticated&&PUBLIC_ROUTES.has(route)){location.hash='#/home';return}
  if(authenticated&&state.currentWorkspace==='personal'&&['businessStart','businessDetails','businessKyc','branches','bank','applicationStatus'].includes(route))currentApplication();
  let html;
  if(route==='not-found'||!isKnownRoute(route)){state.currentRoute='not-found';html=notFoundScreen()}
  else if(!canOpen(state.currentWorkspace,route,state.auth?.status)){state.currentRoute='access-denied';html=deniedScreen()}
  else{state.currentRoute=route;html=route==='home'?homeScreen(state.currentWorkspace,state):route==='states'?statesScreen():route==='welcome'?welcomeScreen():route==='signup'?signupScreen(state):route==='otp'?otpScreen(state):route==='recover'?recoveryScreen(state):route==='invitations'?invitationsScreen(state):route==='businessStart'?businessStartScreen(state):route==='businessDetails'?businessDetailsScreen(state):route==='businessKyc'?businessKycScreen(state):route==='branches'?branchesScreen(state):route==='bank'?bankScreen(state):route==='applicationStatus'?applicationStatusScreen(state):route==='business'?businessDashboardScreen(state):route==='serviceExpansion'?serviceExpansionScreen(state):route==='approvals'?adminApprovalsScreen(state):route==='applicationReview'?applicationReviewScreen(state):placeholderScreen(route,currentRole().label)}
  document.body.classList.toggle('auth-mode',PUBLIC_ROUTES.has(route));saveState(state);main.innerHTML=html;$('page-title').textContent=state.currentRoute==='access-denied'?'Access denied':state.currentRoute==='not-found'?'Page not found':routeTitle(state.currentRoute);markActive();bindContent();main.focus();closeOverlays();
}
function switchWorkspace(key){if(!ROLE_CONFIG[key])return;state.currentWorkspace=key;state.currentRoute='home';saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();location.hash='#/home';renderRoute();toast(`Switched to ${roleForWorkspace(key).label}`)}
function showFormError(id,message){const el=$(id);if(!el)return;el.textContent=message;el.hidden=false}
function completeNewIdentity(){state.auth={...state.auth,status:'authenticated',mobile:state.auth.pendingMobile,mobileVerified:true,pendingMobile:null};state.person={id:`PER-${Date.now().toString().slice(-6)}`,name:'New User'};state.workspaces=['personal'];state.currentWorkspace='personal';state.invitations=state.invitations.filter(x=>x.mobile===state.auth.mobile);state.businessProfiles={};state.businessApplications=[];state.currentApplicationId=null;state.audit.unshift({id:`AUD-${Date.now()}`,event:'Personal workspace created',at:new Date().toLocaleString('en-IN'),actor:'New User'});saveState(state);renderAll();navigate('home');toast('Mobile verified. Personal workspace created')}
function continueExisting(){const identity=state.knownIdentities.find(x=>x.mobile===state.auth.pendingMobile)||state.knownIdentities[0];state.auth={...state.auth,status:'authenticated',mobile:identity.mobile,mobileVerified:true,pendingMobile:null};state.person={id:identity.personId,name:identity.name};state.workspaces=[...new Set(identity.workspaces)];state.currentWorkspace='personal';state.businessApplications=state.businessApplications.filter(x=>x.ownerId===identity.personId);state.currentApplicationId=state.businessApplications[0]?.id||null;state.businessProfiles=Object.fromEntries(Object.entries(state.businessProfiles).filter(([key])=>state.workspaces.includes(key)));state.audit.unshift({id:`AUD-${Date.now()}`,event:'Existing identity recovered by OTP',at:new Date().toLocaleString('en-IN'),actor:identity.name});saveState(state);renderAll();navigate('home');toast('Existing account opened safely')}
function answerInvite(id,answer){const invite=state.invitations.find(x=>x.id===id);if(!invite||invite.status!=='pending')return;invite.status=answer;if(answer==='accepted'&&!state.workspaces.includes(invite.workspace))state.workspaces.push(invite.workspace);state.audit.unshift({id:`AUD-${Date.now()}`,event:`Invitation ${answer}: ${invite.business} · ${invite.role}`,at:new Date().toLocaleString('en-IN'),actor:state.person.name});saveState(state);renderRoute();toast(answer==='accepted'?`${invite.business} added to workspace switcher`:'Invitation declined')}
function currentApplication(){let app=state.businessApplications.find(x=>x.id===state.currentApplicationId)||state.businessApplications.find(x=>x.ownerId===state.person.id);if(!app){app={id:`APP-${Date.now().toString().slice(-4)}`,ownerId:state.person.id,ownerName:state.person.name,legalName:'',services:[],status:'draft',resumeSection:'services',version:1,details:{entityType:'Proprietorship',pan:'',gstin:'',address:''},documents:[],branches:[],bank:{accountName:'',accountNumber:'',ifsc:'',upi:'',verificationStatus:'not_added'},decisions:[],updatedAt:new Date().toLocaleString('en-IN')};state.businessApplications.push(app);state.currentApplicationId=app.id;saveState(state)}return app}
function recordDecision(app,decision,reason,section){app.decisions.unshift({version:app.version,decision,reason,section,reviewer:'Admin Neha',at:new Date().toLocaleString('en-IN')});app.updatedAt=new Date().toLocaleString('en-IN');state.audit.unshift({id:`AUD-${Date.now()}`,event:`${decision}: ${app.id} v${app.version}`,at:app.updatedAt,actor:'Admin Neha'})}
function resolveCorrection(app,section){if(app.status==='correction_required'&&app.resumeSection===section){app.status='draft';app.resumeSection='review';app.updatedAt=new Date().toLocaleString('en-IN')}}
function approveApplication(app){app.status='approved';app.resumeSection='approved';app.bank.verificationStatus='verified';recordDecision(app,'approved','KYC, branch and bank checks passed','all');if(app.ownerId!==state.person.id)return;const workspace=app.existingWorkspace||workspaceForServices(app.services);if(!state.workspaces.includes(workspace))state.workspaces.push(workspace);state.workspaceOverrides={...(state.workspaceOverrides||{}),[workspace]:{label:app.legalName,subtitle:'Business Owner · Approved'}};state.businessProfiles[workspace]={businessId:app.id,legalName:app.legalName,services:[...new Set([...(state.businessProfiles[workspace]?.services||[]),...app.services])],kycStatus:'approved',bank:{maskedAccount:maskAccount(app.bank.accountNumber),verificationStatus:'verified'},branches:app.branches.map(x=>({...x}))}}
function bindContent(){
  main.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));main.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));
  main.querySelector('[data-unknown-route]')?.addEventListener('click',()=>location.hash='#/does-not-exist');main.querySelector('[data-forbidden-route]')?.addEventListener('click',()=>{const forbidden=state.currentWorkspace==='admin'?'money':'audit';location.hash=`#/${forbidden}`});
  main.querySelector('#mobile-form')?.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.currentTarget);const mobile=normalizeMobile(form.get('mobile'));if(!validateMobile(mobile)){showFormError('mobile-error','Enter a valid 10-digit Indian mobile number.');return}if(!form.get('consent')){showFormError('mobile-error','Please accept the Terms and Privacy Notice before OTP.');return}state.auth={...state.auth,status:'otp-pending',pendingMobile:mobile,isExistingIdentity:isKnownMobile(mobile,state.knownIdentities),consentVersion:'2026-09-27',consentedAt:new Date().toISOString(),otpAttempts:0,otpSentAt:Date.now()};saveState(state);navigate('otp')});
  main.querySelector('#otp-form')?.addEventListener('submit',e=>{e.preventDefault();const entered=new FormData(e.currentTarget).get('otp');const result=otpStatus({entered,sentAt:state.auth.otpSentAt,attempts:state.auth.otpAttempts});if(result==='valid'){state.auth.mobileVerified=true;state.auth.isExistingIdentity?navigate('recover'):completeNewIdentity();return}state.auth.otpAttempts=(state.auth.otpAttempts||0)+1;saveState(state);const messages={invalid:'OTP is incorrect. Use 123456 for this prototype.',expired:'OTP expired. Resend a new OTP.',locked:'Too many attempts. Change the number and start again.'};showFormError('otp-error',messages[result]);if(state.auth.otpAttempts>=5)renderRoute()});
  main.querySelector('[data-action="resend-otp"]')?.addEventListener('click',()=>{if(!canResend(state.auth.otpSentAt)){toast('Please wait 30 seconds before resending');return}state.auth.otpSentAt=Date.now();state.auth.otpAttempts=0;saveState(state);renderRoute();toast('New OTP sent')});
  main.querySelector('[data-action="show-consent"]')?.addEventListener('click',()=>toast('Consent: OTP verification, account security and service updates'));
  main.querySelector('[data-action="continue-existing"]')?.addEventListener('click',continueExisting);
  main.querySelector('[data-action="wrong-account"]')?.addEventListener('click',()=>toast('Support verification opened. No account data changed'));
  main.querySelectorAll('[data-action="accept-invite"]').forEach(b=>b.onclick=()=>answerInvite(b.dataset.invite,'accepted'));
  main.querySelectorAll('[data-action="reject-invite"]').forEach(b=>b.onclick=()=>answerInvite(b.dataset.invite,'declined'));
  main.querySelector('[data-action="start-signup-demo"]')?.addEventListener('click',()=>{state=signupDemoState();saveState(state);navigate('welcome')});
  main.querySelector('[data-action="restore-seeded-demo"]')?.addEventListener('click',()=>{state=resetState();saveState(state);renderAll();navigate('home');toast('Full demo restored')});
  main.querySelector('#business-start-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),services=f.getAll('services'),name=f.get('legalName');const error=validateServices(name,services);if(error){showFormError('business-start-error',error);return}const a=currentApplication();a.legalName=String(name).trim();a.services=services;a.resumeSection='details';saveState(state);navigate('businessDetails')});
  main.querySelector('#business-details-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=currentApplication();const wasCorrection=a.status==='correction_required'&&a.resumeSection==='details';const pan=String(f.get('pan')).trim().toUpperCase(),gstin=String(f.get('gstin')).trim().toUpperCase(),address=String(f.get('address')).trim();if(!/^[A-Z]{5}\d{4}[A-Z]$/.test(pan)){showFormError('business-details-error','Enter a valid PAN, for example ABCDE1234F.');return}if((a.services.includes('transport')||a.services.includes('fleet'))&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/.test(gstin)){showFormError('business-details-error','GSTIN is required for Transport or Own Vehicles.');return}if(address.length<10){showFormError('business-details-error','Enter the full registered address.');return}a.details={entityType:f.get('entityType'),pan,gstin,address};if(wasCorrection){resolveCorrection(a,'details');saveState(state);navigate('applicationStatus')}else{a.resumeSection='kyc';saveState(state);navigate('businessKyc')}});
  main.querySelectorAll('[data-action="use-sample-document"]').forEach(b=>b.onclick=()=>{const a=currentApplication(),type=b.dataset.document;if(!a.documents.some(x=>x.type===type))a.documents.push({type,name:`sample-${type.toLowerCase().replaceAll(' ','-')}.pdf`,status:'uploaded'});saveState(state);renderRoute();toast(`${type} added`)});
  main.querySelector('[data-action="continue-kyc"]')?.addEventListener('click',()=>{const a=currentApplication(),missing=requiredKyc(a.services).filter(type=>!a.documents.some(x=>x.type===type));if(missing.length){showFormError('kyc-error',`Add ${missing.join(', ')} before continuing.`);return}if(a.status==='correction_required'&&a.resumeSection==='kyc'){resolveCorrection(a,'kyc');saveState(state);navigate('applicationStatus')}else{a.resumeSection='branches';saveState(state);navigate('branches')}});
  main.querySelector('#branch-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),address=String(f.get('address')).trim();if(!name||address.length<8){showFormError('branch-error','Enter the branch name and full address.');return}const a=currentApplication(),wasCorrection=a.status==='correction_required'&&a.resumeSection==='branches';a.branches=[{id:a.branches[0]?.id||`BR-${Date.now().toString().slice(-5)}`,name,address,serviceArea:String(f.get('serviceArea')).trim(),manager:String(f.get('manager')).trim(),status:'active',isDefault:true,activeWork:0}];if(wasCorrection){resolveCorrection(a,'branches');saveState(state);navigate('applicationStatus')}else{a.resumeSection='bank';saveState(state);navigate('bank')}});
  main.querySelector('#bank-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),bank={accountName:String(f.get('accountName')).trim(),accountNumber:String(f.get('accountNumber')).replace(/\D/g,''),ifsc:String(f.get('ifsc')).trim().toUpperCase(),upi:String(f.get('upi')).trim(),verificationStatus:'pending'};const error=validateBank(bank);if(error){showFormError('bank-error',error);return}const a=currentApplication(),wasCorrection=a.status==='correction_required'&&a.resumeSection==='bank';a.bank=bank;resolveCorrection(a,'bank');a.resumeSection='review';saveState(state);navigate('applicationStatus')});
  main.querySelector('[data-action="submit-business-application"]')?.addEventListener('click',()=>{const a=currentApplication();a.status='under_review';a.updatedAt=new Date().toLocaleString('en-IN');state.audit.unshift({id:`AUD-${Date.now()}`,event:`Business application submitted: ${a.id}`,at:a.updatedAt,actor:state.person.name});saveState(state);renderRoute();toast('Application submitted for Admin review')});
  main.querySelectorAll('[data-action="review-application"]').forEach(b=>b.onclick=()=>{state.selectedApplicationId=b.dataset.application;saveState(state);navigate('applicationReview')});
  main.querySelectorAll('[data-action="admin-decision"]').forEach(b=>b.onclick=()=>{const a=state.businessApplications.find(x=>x.id===state.selectedApplicationId);if(!a)return;const decision=b.dataset.decision,reason=main.querySelector('#decision-reason')?.value.trim()||'',section=main.querySelector('#decision-section')?.value||'kyc';if(decision!=='approved'&&!reason){toast('Add a reason before sending this decision');return}if(decision==='approved')approveApplication(a);else{a.status=decision;a.resumeSection=section;a.version+=1;recordDecision(a,decision,reason,section)}saveState(state);navigate('approvals');toast(decision==='approved'?'Business approved':'Decision sent to the owner')});
  main.querySelector('[data-action="open-approved-business"]')?.addEventListener('click',()=>{const a=currentApplication(),workspace=a.existingWorkspace||workspaceForServices(a.services);switchWorkspace(workspace)});
  main.querySelector('[data-action="show-add-branch"]')?.addEventListener('click',()=>{if(state.currentWorkspace==='personal'){toast('Complete the default branch form below');return}const p=state.businessProfiles[state.currentWorkspace];if(!p)return;p.branches.push({id:`BR-${Date.now().toString().slice(-5)}`,name:'Lucknow Branch',serviceArea:'Lucknow and nearby districts',manager:'Not assigned',status:'active',isDefault:false,activeWork:0});saveState(state);renderRoute();toast('Sample branch added')});
  main.querySelectorAll('[data-action="disable-branch"]').forEach(b=>b.onclick=()=>{if(b.dataset.blocked){toast('Complete or reassign active work before disabling');return}const p=state.businessProfiles[state.currentWorkspace],branch=p?.branches.find(x=>x.id===b.dataset.branch);if(branch)branch.status='disabled';saveState(state);renderRoute();toast('Branch disabled')});
  main.querySelector('#service-expansion-form')?.addEventListener('submit',e=>{e.preventDefault();const selected=new FormData(e.currentTarget).getAll('services'),p=state.businessProfiles[state.currentWorkspace],added=selected.filter(x=>!p.services.includes(x));if(!added.length){toast('Select at least one new service');return}const app={id:`APP-${Date.now().toString().slice(-4)}`,ownerId:state.person.id,ownerName:state.person.name,legalName:p.legalName,services:added,status:'under_review',resumeSection:'review',version:1,existingWorkspace:state.currentWorkspace,details:{entityType:'Existing verified business',pan:'Verified',gstin:'Verified',address:'Verified'},documents:[{type:'Common KYC',name:'Reused verified KYC',status:'verified'}],branches:p.branches.map(x=>({...x})),bank:{accountName:p.legalName,accountNumber:p.bank.maskedAccount.replace(/\D/g,'').padStart(12,'0'),ifsc:'VERIFIED001',upi:'',verificationStatus:'verified'},decisions:[],updatedAt:new Date().toLocaleString('en-IN')};state.businessApplications.push(app);state.selectedApplicationId=app.id;saveState(state);navigate('business');toast('Service request sent. Common KYC reused')});
}

document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){if(route==='more')openMore();else navigate(route)}const workspace=e.target.closest('[data-workspace]')?.dataset.workspace;if(workspace)switchWorkspace(workspace);if(e.target.closest('[data-workspace-action="invitations"]')){closeOverlays();if(state.currentWorkspace!=='personal'){state.currentWorkspace='personal';renderWorkspace();renderDesktopNav();renderMobileNav()}navigate('invitations')}if(e.target.closest('[data-workspace-action="add-business"]')){closeOverlays();if(state.currentWorkspace!=='personal'){state.currentWorkspace='personal';renderWorkspace();renderDesktopNav();renderMobileNav()}currentApplication();navigate('businessStart')}if(e.target.closest('[data-close-dialog]'))$('workspace-dialog').hidden=true;if(e.target.closest('[data-close-more]'))$('more-sheet').hidden=true});
$('workspace-button').onclick=openWorkspaceDialog;$('menu-button').onclick=()=>{sidebar.classList.add('open');backdrop.hidden=false};backdrop.onclick=closeOverlays;$('reset-demo').onclick=()=>{state=resetState();renderAll();location.hash='#/home';toast('Demo data reset')};$('ai-button').onclick=()=>toast('AI assistant arrives in Phase P8');
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlays()});window.addEventListener('hashchange',renderRoute);

function renderAll(){renderWorkspace();renderDesktopNav();renderMobileNav();if(!location.hash)location.hash=state.auth?.status==='authenticated'?'#/home':'#/welcome';renderRoute();app.setAttribute('aria-busy','false')}
renderAll();

window.MoveAIVNextTest={state:()=>structuredClone(state),switchWorkspace,canOpen,reset:()=>{state=resetState();renderAll()},startSignup:()=>{state=signupDemoState();saveState(state);navigate('welcome')},routes:()=>Object.keys(ROUTES)};
