import {ROLE_CONFIG,ROUTES,ICONS,MOBILE_PRIMARY,PUBLIC_ROUTES,routeTitle} from './config.js';
import {loadState,saveState,resetState,signupDemoState} from './store.js';
import {canOpen,visibleNavigation} from './permissions.js';
import {readRoute,navigate,isKnownRoute} from './router.js';
import {homeScreen,placeholderScreen,statesScreen,notFoundScreen,deniedScreen} from './screens.js';
import {welcomeScreen,signupScreen,otpScreen,recoveryScreen,invitationsScreen} from './onboarding.js';
import {normalizeMobile,validateMobile,isKnownMobile,otpStatus,canResend} from './identity.js';
import {businessStartScreen,businessDetailsScreen,businessKycScreen,branchesScreen,bankScreen,applicationStatusScreen,businessDashboardScreen,serviceExpansionScreen,adminApprovalsScreen,applicationReviewScreen} from './business.js';
import {requiredKyc,validateServices,validateBank,workspaceForServices,maskAccount} from './business-rules.js';
import {peopleScreen,addStaffScreen,staffDetailScreen,staffInviteScreen,staffOtpScreen,staffOnboardingScreen,staffSubmissionScreen,staffReviewScreen,staffSelfProfileScreen,rolesScreen,staffAccessScreen,hiringScreen,postOpeningScreen,findWorkersScreen,openingDetailScreen,applicationsScreen,candidateProfileScreen,candidateWorkScreen,ownerCoverScreen,offboardingScreen} from './people.js';
import {ROLE_TEMPLATES,validateStaffInvite,validateOwnerCover,employmentResult,canAcceptStaffInvitation,staffSubmissionReady,staffReviewDecision} from './people-rules.js';
import {marketplaceHomeScreen,goodsOrderScreen,transportRequirementScreen,arrangementScreen,buyWithDeliveryScreen,goodsRequirementsScreen,postAvailableLoadScreen,postLoadRequirementScreen,transporterRequirementsScreen,postAvailableTruckScreen,routeOpportunitiesScreen,opportunityDetailScreen,opportunityChatScreen} from './marketplace.js';
import {validateGoodsOrder,validateTransportRequirement,validateLoadRequirement,validateTruckAvailability,canConvertOpportunity} from './marketplace-rules.js';

let state=loadState();
const $=id=>document.getElementById(id);
const app=$('app'),main=$('main-content'),sidebar=$('sidebar'),backdrop=$('sidebar-backdrop');

function navButton(route,label,badge=0,mobile=false){return `<button type="button" class="nav-button" data-route="${route}" aria-label="${label}"><span class="nav-icon" aria-hidden="true">${ICONS[route]||'□'}</span><span class="nav-label">${label}</span>${badge&&!mobile?`<span class="nav-badge">${badge}</span>`:''}</button>`}
function roleForWorkspace(key){const base=ROLE_CONFIG[key]||ROLE_CONFIG.personal;const override=state.workspaceOverrides?.[key];return override?{...base,...override}:base}
function currentRole(){return roleForWorkspace(state.currentWorkspace)}
function renderWorkspace(){const r=currentRole();$('workspace-icon').textContent=r.icon;$('workspace-name').textContent=r.label;$('workspace-role').textContent=r.subtitle;$('page-context').textContent=r.label;$('branch-button').hidden=!r.branches}
function renderDesktopNav(){const badges=state.badges?.[state.currentWorkspace]||{};$('desktop-nav').innerHTML=visibleNavigation(state.currentWorkspace).map(([id,label])=>navButton(id,label,badges[id])).join('');markActive()}
function renderMobileNav(){const nav=visibleNavigation(state.currentWorkspace);const map=new Map(nav);const primary=MOBILE_PRIMARY.filter(id=>map.has(id));if(!primary.includes('home'))primary.unshift('home');const shown=primary.slice(0,4);$('mobile-nav').innerHTML=shown.map(id=>navButton(id,map.get(id),0,true)).join('')+navButton('more','More',0,true);markActive()}
function renderMore(){const nav=visibleNavigation(state.currentWorkspace);const primary=new Set(MOBILE_PRIMARY);$('more-list').innerHTML=nav.filter(([id])=>!primary.has(id)).map(([id,label])=>`<button type="button" class="more-option" data-route="${id}"><span class="workspace-icon" aria-hidden="true">${ICONS[id]||'□'}</span><span class="workspace-copy"><b>${label}</b><small>Open ${label}</small></span><span aria-hidden="true">›</span></button>`).join('')+`<button type="button" class="more-option" data-route="states"><span class="workspace-icon">◇</span><span class="workspace-copy"><b>Screen states</b><small>P0 test lab</small></span><span>›</span></button>`}
function markActive(){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.currentRoute))}
function renderWorkspaceList(){const options=state.workspaces.map(k=>{const r=roleForWorkspace(k);if(!r)return '';return `<button type="button" class="workspace-option ${k===state.currentWorkspace?'current':''}" data-workspace="${k}"><span class="workspace-icon">${r.icon}</span><span class="workspace-copy"><b>${r.label}</b><small>${r.subtitle}</small></span>${k===state.currentWorkspace?'<span class="status-pill">Current</span>':'<span>›</span>'}</button>`}).join('');const pending=state.invitations?.filter(x=>x.status==='pending').length||0;$('workspace-list').innerHTML=options+`<button type="button" class="workspace-option invitation-entry" data-workspace-action="invitations"><span class="workspace-icon">✉</span><span class="workspace-copy"><b>Pending invitations</b><small>${pending} waiting for review</small></span><span class="status-pill info">${pending}</span></button><button type="button" class="workspace-option add-business-entry" data-workspace-action="add-business"><span class="workspace-icon">+</span><span class="workspace-copy"><b>Add business profile</b><small>One business can enable several services</small></span><span>›</span></button>`}

function closeOverlays(){$('workspace-dialog').hidden=true;$('more-sheet').hidden=true;sidebar.classList.remove('open');backdrop.hidden=true}
function openWorkspaceDialog(){renderWorkspaceList();$('workspace-dialog').hidden=false;$('workspace-list').querySelector('button')?.focus()}
function openMore(){renderMore();$('more-sheet').hidden=false;$('more-list').querySelector('button')?.focus()}
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}

function renderRoute(){
  let route=readRoute();const authenticated=state.auth?.status==='authenticated';
  if(!authenticated&&!PUBLIC_ROUTES.has(route)){location.hash='#/welcome';return}
  if(authenticated&&PUBLIC_ROUTES.has(route)){location.hash='#/home';return}
  if(authenticated&&state.currentWorkspace==='personal'&&['businessStart','businessDetails','businessKyc','branches','bank','applicationStatus'].includes(route))currentApplication();
  let html;
  if(route==='not-found'||!isKnownRoute(route)){state.currentRoute='not-found';html=notFoundScreen()}
  else if(!canOpen(state.currentWorkspace,route,state.auth?.status)){state.currentRoute='access-denied';html=deniedScreen()}
  else{state.currentRoute=route;const worker=['commercialDriver','personalDriver','helper'].includes(state.currentWorkspace),staffRole=state.currentWorkspace==='staff',businessMarket=['goods','transporter','vehicle'].includes(state.currentWorkspace);html=route==='home'?homeScreen(state.currentWorkspace,state):route==='states'?statesScreen():route==='welcome'?welcomeScreen():route==='signup'?signupScreen(state):route==='otp'?otpScreen(state):route==='recover'?recoveryScreen(state):route==='invitations'?invitationsScreen(state):route==='businessStart'?businessStartScreen(state):route==='businessDetails'?businessDetailsScreen(state):route==='businessKyc'?businessKycScreen(state):route==='branches'?branchesScreen(state):route==='bank'?bankScreen(state):route==='applicationStatus'?applicationStatusScreen(state):route==='business'?businessDashboardScreen(state):route==='serviceExpansion'?serviceExpansionScreen(state):route==='approvals'?adminApprovalsScreen(state):route==='applicationReview'?applicationReviewScreen(state):route==='people'?peopleScreen(state):route==='addStaff'?addStaffScreen(state):route==='staffDetail'?staffDetailScreen(state):route==='staffInvite'?staffInviteScreen(state):route==='staffOtp'?staffOtpScreen(state):route==='staffOnboarding'?staffOnboardingScreen(state):route==='staffSubmission'?staffSubmissionScreen(state):route==='staffReview'?staffReviewScreen(state):route==='roles'?rolesScreen(state):route==='staffAccess'?staffAccessScreen(state):route==='hiring'?hiringScreen(state):route==='postOpening'?postOpeningScreen(state):route==='findWorkers'?findWorkersScreen(state):route==='openingDetail'?openingDetailScreen(state,worker):route==='applications'?applicationsScreen(state):route==='candidateProfile'||(route==='profile'&&worker)?candidateProfileScreen(state):route==='profile'&&staffRole?staffSelfProfileScreen(state):route==='ownerCover'?ownerCoverScreen(state):route==='offboarding'?offboardingScreen(state):route==='goodsOrder'?goodsOrderScreen(state):route==='transportRequirement'?transportRequirementScreen(state):route==='arrangement'?arrangementScreen(state):route==='buyWithDelivery'?buyWithDeliveryScreen(state):route==='goodsRequirements'?goodsRequirementsScreen(state):route==='postAvailableLoad'?postAvailableLoadScreen(state):route==='postLoadRequirement'?postLoadRequirementScreen(state):route==='transporterRequirements'?transporterRequirementsScreen(state):route==='postAvailableTruck'?postAvailableTruckScreen(state):route==='routeOpportunities'?routeOpportunitiesScreen(state):route==='opportunityDetail'?opportunityDetailScreen(state):route==='opportunityChat'?opportunityChatScreen(state):route==='work'&&worker?candidateWorkScreen(state):route==='work'&&businessMarket?marketplaceHomeScreen(state):placeholderScreen(route,currentRole().label)}
  document.body.classList.toggle('auth-mode',PUBLIC_ROUTES.has(route));saveState(state);main.innerHTML=html;$('page-title').textContent=state.currentRoute==='access-denied'?'Access denied':state.currentRoute==='not-found'?'Page not found':routeTitle(state.currentRoute);markActive();bindContent();main.focus();closeOverlays();
}
function switchWorkspace(key){if(!ROLE_CONFIG[key])return;state.currentWorkspace=key;let target='home';const candidateByWorkspace={commercialDriver:'CAND-001',personalDriver:'CAND-004',helper:'CAND-002'};if(candidateByWorkspace[key])state.selectedCandidateId=candidateByWorkspace[key];if(key==='staff'){const x=selectedStaff();target=x?.status==='correction_required'?'staffOnboarding':x?.status==='active'?'home':'staffSubmission'}state.currentRoute=target;saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();location.hash=`#/${target}`;renderRoute();toast(`Switched to ${roleForWorkspace(key).label}`)}
function showFormError(id,message){const el=$(id);if(!el)return;el.textContent=message;el.hidden=false}
function staffOwnerWorkspace(){return state.staffSession?.ownerWorkspace||'transporter'}
function selectedStaff(){return (state.peopleByWorkspace[staffOwnerWorkspace()]||[]).find(x=>x.id===state.selectedStaffId)}
function showStaffWorkspace(member,target='home'){const owner=state.currentWorkspace==='staff'?staffOwnerWorkspace():state.currentWorkspace;state.staffSession={...(state.staffSession||{}),ownerWorkspace:owner,memberId:member.id,mobile:member.mobile,verified:true};state.selectedStaffId=member.id;state.workspaceOverrides={...(state.workspaceOverrides||{}),staff:{label:member.name,subtitle:`${ROLE_TEMPLATES[member.role].label} · Staff`}};if(!state.workspaces.includes('staff'))state.workspaces.push('staff');state.currentWorkspace='staff';saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();navigate(target)}
function completeNewIdentity(){state.auth={...state.auth,status:'authenticated',mobile:state.auth.pendingMobile,mobileVerified:true,pendingMobile:null};state.person={id:`PER-${Date.now().toString().slice(-6)}`,name:'New User'};state.workspaces=['personal'];state.currentWorkspace='personal';state.invitations=state.invitations.filter(x=>x.mobile===state.auth.mobile);state.businessProfiles={};state.businessApplications=[];state.currentApplicationId=null;state.audit.unshift({id:`AUD-${Date.now()}`,event:'Personal workspace created',at:new Date().toLocaleString('en-IN'),actor:'New User'});saveState(state);renderAll();navigate('home');toast('Mobile verified. Personal workspace created')}
function continueExisting(){const identity=state.knownIdentities.find(x=>x.mobile===state.auth.pendingMobile)||state.knownIdentities[0];state.auth={...state.auth,status:'authenticated',mobile:identity.mobile,mobileVerified:true,pendingMobile:null};state.person={id:identity.personId,name:identity.name};state.workspaces=[...new Set(identity.workspaces)];state.currentWorkspace='personal';state.businessApplications=state.businessApplications.filter(x=>x.ownerId===identity.personId);state.currentApplicationId=state.businessApplications[0]?.id||null;state.businessProfiles=Object.fromEntries(Object.entries(state.businessProfiles).filter(([key])=>state.workspaces.includes(key)));state.audit.unshift({id:`AUD-${Date.now()}`,event:'Existing identity recovered by OTP',at:new Date().toLocaleString('en-IN'),actor:identity.name});saveState(state);renderAll();navigate('home');toast('Existing account opened safely')}
function answerInvite(id,answer){const invite=state.invitations.find(x=>x.id===id);if(!invite||invite.status!=='pending')return;invite.status=answer;if(answer==='accepted'&&!state.workspaces.includes(invite.workspace))state.workspaces.push(invite.workspace);state.audit.unshift({id:`AUD-${Date.now()}`,event:`Invitation ${answer}: ${invite.business} · ${invite.role}`,at:new Date().toLocaleString('en-IN'),actor:state.person.name});saveState(state);renderRoute();toast(answer==='accepted'?`${invite.business} added to workspace switcher`:'Invitation declined')}
function currentApplication(){let app=state.businessApplications.find(x=>x.id===state.currentApplicationId)||state.businessApplications.find(x=>x.ownerId===state.person.id);if(!app){app={id:`APP-${Date.now().toString().slice(-4)}`,ownerId:state.person.id,ownerName:state.person.name,legalName:'',services:[],status:'draft',resumeSection:'services',version:1,details:{entityType:'Proprietorship',pan:'',gstin:'',address:''},documents:[],branches:[],bank:{accountName:'',accountNumber:'',ifsc:'',upi:'',verificationStatus:'not_added'},decisions:[],updatedAt:new Date().toLocaleString('en-IN')};state.businessApplications.push(app);state.currentApplicationId=app.id;saveState(state)}return app}
function recordDecision(app,decision,reason,section){app.decisions.unshift({version:app.version,decision,reason,section,reviewer:'Admin Neha',at:new Date().toLocaleString('en-IN')});app.updatedAt=new Date().toLocaleString('en-IN');state.audit.unshift({id:`AUD-${Date.now()}`,event:`${decision}: ${app.id} v${app.version}`,at:app.updatedAt,actor:'Admin Neha'})}
function resolveCorrection(app,section){if(app.status==='correction_required'&&app.resumeSection===section){app.status='draft';app.resumeSection='review';app.updatedAt=new Date().toLocaleString('en-IN')}}
function approveApplication(app){app.status='approved';app.resumeSection='approved';app.bank.verificationStatus='verified';recordDecision(app,'approved','KYC, branch and bank checks passed','all');if(app.ownerId!==state.person.id)return;const workspace=app.existingWorkspace||workspaceForServices(app.services);if(!state.workspaces.includes(workspace))state.workspaces.push(workspace);state.workspaceOverrides={...(state.workspaceOverrides||{}),[workspace]:{label:app.legalName,subtitle:'Business Owner · Approved'}};state.businessProfiles[workspace]={businessId:app.id,legalName:app.legalName,services:[...new Set([...(state.businessProfiles[workspace]?.services||[]),...app.services])],kycStatus:'approved',bank:{maskedAccount:maskAccount(app.bank.accountNumber),verificationStatus:'verified'},branches:app.branches.map(x=>({...x}))}}
function bindContent(){
  main.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));main.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));
  main.querySelector('[data-unknown-route]')?.addEventListener('click',()=>location.hash='#/does-not-exist');main.querySelector('[data-forbidden-route]')?.addEventListener('click',()=>{const forbidden=state.currentWorkspace==='admin'?'money':'audit';location.hash=`#/${forbidden}`});
  main.querySelector('#mobile-form')?.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.currentTarget);const mobile=normalizeMobile(form.get('mobile'));if(!validateMobile(mobile)){showFormError('mobile-error','Enter a valid 10-digit Indian mobile number.');return}if(!form.get('consent')){showFormError('mobile-error','Please accept the Terms and Privacy Notice before OTP.');return}state.auth={...state.auth,status:'otp-pending',pendingMobile:mobile,isExistingIdentity:isKnownMobile(mobile,state.knownIdentities),consentVersion:'2026-09-27',consentedAt:new Date().toISOString(),otpAttempts:0,otpSentAt:Date.now()};saveState(state);navigate('otp')});
  main.querySelector('#otp-form')?.addEventListener('submit',e=>{e.preventDefault();const entered=new FormData(e.currentTarget).get('otp');const result=otpStatus({entered,sentAt:state.auth.otpSentAt,attempts:state.auth.otpAttempts});if(result==='valid'){state.auth.mobileVerified=true;state.auth.isExistingIdentity?navigate('recover'):completeNewIdentity();return}state.auth.otpAttempts=(state.auth.otpAttempts||0)+1;saveState(state);const messages={invalid:'OTP is incorrect. Use 123456 for this prototype.',expired:'OTP expired. Resend a new OTP.',locked:'Too many attempts. Change the number and start again.'};showFormError('otp-error',messages[result]);if(state.auth.otpAttempts>=5)renderRoute()});
  main.querySelector('[data-action="resend-otp"]')?.addEventListener('click',()=>{if(!canResend(state.auth.otpSentAt)){toast('Please wait 30 seconds before resending');return}state.auth.otpSentAt=Date.now();state.auth.otpAttempts=0;saveState(state);renderRoute();toast('New OTP sent')});
  main.querySelector('[data-action="show-consent"]')?.addEventListener('click',()=>toast('Consent: OTP verification, account security and service updates'));
  main.querySelector('[data-action="continue-existing"]')?.addEventListener('click',continueExisting);
  main.querySelector('[data-action="wrong-account"]')?.addEventListener('click',()=>toast('Support verification opened. No account data changed'));
  main.querySelectorAll('[data-action="accept-invite"]').forEach(b=>b.onclick=()=>answerInvite(b.dataset.invite,'accepted'));
  main.querySelectorAll('[data-action="reject-invite"]').forEach(b=>b.onclick=()=>answerInvite(b.dataset.invite,'declined'));
  main.querySelector('[data-action="start-signup-demo"]')?.addEventListener('click',()=>{state=signupDemoState();saveState(state);navigate('welcome')});
  main.querySelector('[data-action="restore-seeded-demo"]')?.addEventListener('click',()=>{state=resetState();saveState(state);renderAll();navigate('home');toast('Full demo restored')});
  main.querySelector('#business-start-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),services=f.getAll('services'),name=f.get('legalName');const error=validateServices(name,services);if(error){showFormError('business-start-error',error);return}const a=currentApplication();a.legalName=String(name).trim();a.services=services;a.resumeSection='details';saveState(state);navigate('businessDetails')});
  main.querySelector('#business-details-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=currentApplication();const wasCorrection=a.status==='correction_required'&&a.resumeSection==='details';const pan=String(f.get('pan')).trim().toUpperCase(),gstin=String(f.get('gstin')).trim().toUpperCase(),address=String(f.get('address')).trim();if(!/^[A-Z]{5}\d{4}[A-Z]$/.test(pan)){showFormError('business-details-error','Enter a valid PAN, for example ABCDE1234F.');return}if((a.services.includes('transport')||a.services.includes('fleet'))&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/.test(gstin)){showFormError('business-details-error','GSTIN is required for Transport or Own Vehicles.');return}if(address.length<10){showFormError('business-details-error','Enter the full registered address.');return}a.details={entityType:f.get('entityType'),pan,gstin,address};if(wasCorrection){resolveCorrection(a,'details');saveState(state);navigate('applicationStatus')}else{a.resumeSection='kyc';saveState(state);navigate('businessKyc')}});
  main.querySelectorAll('[data-action="use-sample-document"]').forEach(b=>b.onclick=()=>{const a=currentApplication(),type=b.dataset.document;if(!a.documents.some(x=>x.type===type))a.documents.push({type,name:`sample-${type.toLowerCase().replaceAll(' ','-')}.pdf`,status:'uploaded'});saveState(state);renderRoute();toast(`${type} added`)});
  main.querySelector('[data-action="continue-kyc"]')?.addEventListener('click',()=>{const a=currentApplication(),missing=requiredKyc(a.services).filter(type=>!a.documents.some(x=>x.type===type));if(missing.length){showFormError('kyc-error',`Add ${missing.join(', ')} before continuing.`);return}if(a.status==='correction_required'&&a.resumeSection==='kyc'){resolveCorrection(a,'kyc');saveState(state);navigate('applicationStatus')}else{a.resumeSection='branches';saveState(state);navigate('branches')}});
  main.querySelector('#branch-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),address=String(f.get('address')).trim();if(!name||address.length<8){showFormError('branch-error','Enter the branch name and full address.');return}const a=currentApplication(),wasCorrection=a.status==='correction_required'&&a.resumeSection==='branches';a.branches=[{id:a.branches[0]?.id||`BR-${Date.now().toString().slice(-5)}`,name,address,serviceArea:String(f.get('serviceArea')).trim(),manager:String(f.get('manager')).trim(),status:'active',isDefault:true,activeWork:0}];if(wasCorrection){resolveCorrection(a,'branches');saveState(state);navigate('applicationStatus')}else{a.resumeSection='bank';saveState(state);navigate('bank')}});
  main.querySelector('#bank-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),bank={accountName:String(f.get('accountName')).trim(),accountNumber:String(f.get('accountNumber')).replace(/\D/g,''),ifsc:String(f.get('ifsc')).trim().toUpperCase(),upi:String(f.get('upi')).trim(),verificationStatus:'pending'};const error=validateBank(bank);if(error){showFormError('bank-error',error);return}const a=currentApplication(),wasCorrection=a.status==='correction_required'&&a.resumeSection==='bank';a.bank=bank;resolveCorrection(a,'bank');a.resumeSection='review';saveState(state);navigate('applicationStatus')});
  main.querySelector('[data-action="submit-business-application"]')?.addEventListener('click',()=>{const a=currentApplication(),missing=requiredKyc(a.services).filter(type=>!a.documents.some(x=>x.type===type));let route='';if(!a.legalName||!a.services.length)route='businessStart';else if(!a.details.pan)route='businessDetails';else if(missing.length)route='businessKyc';else if(!a.branches.length)route='branches';else if(!a.bank.accountNumber)route='bank';if(route){toast('Complete the missing step first');navigate(route);return}a.status='under_review';a.updatedAt=new Date().toLocaleString('en-IN');state.audit.unshift({id:`AUD-${Date.now()}`,event:`Business application submitted: ${a.id}`,at:a.updatedAt,actor:state.person.name});saveState(state);renderRoute();toast('Application submitted for Admin review')});
  main.querySelectorAll('[data-action="review-application"]').forEach(b=>b.onclick=()=>{state.selectedApplicationId=b.dataset.application;saveState(state);navigate('applicationReview')});
  main.querySelectorAll('[data-action="admin-decision"]').forEach(b=>b.onclick=()=>{const a=state.businessApplications.find(x=>x.id===state.selectedApplicationId);if(!a)return;const decision=b.dataset.decision,reason=main.querySelector('#decision-reason')?.value.trim()||'',section=main.querySelector('#decision-section')?.value||'kyc';if(decision!=='approved'&&!reason){toast('Add a reason before sending this decision');return}if(decision==='approved')approveApplication(a);else{a.status=decision;a.resumeSection=section;a.version+=1;recordDecision(a,decision,reason,section)}saveState(state);navigate('approvals');toast(decision==='approved'?'Business approved':'Decision sent to the owner')});
  main.querySelector('[data-action="open-approved-business"]')?.addEventListener('click',()=>{const a=currentApplication(),workspace=a.existingWorkspace||workspaceForServices(a.services);switchWorkspace(workspace)});
  main.querySelector('[data-action="show-add-branch"]')?.addEventListener('click',()=>{if(state.currentWorkspace==='personal'){toast('Complete the default branch form below');return}const p=state.businessProfiles[state.currentWorkspace];if(!p)return;p.branches.push({id:`BR-${Date.now().toString().slice(-5)}`,name:'Lucknow Branch',serviceArea:'Lucknow and nearby districts',manager:'Not assigned',status:'active',isDefault:false,activeWork:0});saveState(state);renderRoute();toast('Sample branch added')});
  main.querySelectorAll('[data-action="disable-branch"]').forEach(b=>b.onclick=()=>{if(b.dataset.blocked){toast('Complete or reassign active work before disabling');return}const p=state.businessProfiles[state.currentWorkspace],branch=p?.branches.find(x=>x.id===b.dataset.branch);if(branch)branch.status='disabled';saveState(state);renderRoute();toast('Branch disabled')});
  main.querySelector('#service-expansion-form')?.addEventListener('submit',e=>{e.preventDefault();const selected=new FormData(e.currentTarget).getAll('services'),p=state.businessProfiles[state.currentWorkspace],added=selected.filter(x=>!p.services.includes(x));if(!added.length){toast('Select at least one new service');return}const app={id:`APP-${Date.now().toString().slice(-4)}`,ownerId:state.person.id,ownerName:state.person.name,legalName:p.legalName,services:added,status:'under_review',resumeSection:'review',version:1,existingWorkspace:state.currentWorkspace,details:{entityType:'Existing verified business',pan:'Verified',gstin:'Verified',address:'Verified'},documents:[{type:'Common KYC',name:'Reused verified KYC',status:'verified'}],branches:p.branches.map(x=>({...x})),bank:{accountName:p.legalName,accountNumber:p.bank.maskedAccount.replace(/\D/g,'').padStart(12,'0'),ifsc:'VERIFIED001',upi:'',verificationStatus:'verified'},decisions:[],updatedAt:new Date().toLocaleString('en-IN')};state.businessApplications.push(app);state.selectedApplicationId=app.id;saveState(state);navigate('business');toast('Service request sent. Common KYC reused')});
  main.querySelectorAll('[data-action="open-staff"]').forEach(b=>b.onclick=()=>{state.selectedStaffId=b.dataset.staff;saveState(state);navigate('staffDetail')});
  main.querySelectorAll('[data-action="test-staff-invite"]').forEach(b=>b.onclick=()=>{const inv=state.staffInvitations.find(x=>x.id===b.dataset.invite);if(!inv)return;state.staffSession={inviteId:inv.id,ownerWorkspace:state.currentWorkspace,mobile:inv.mobile,verified:false,otpAttempts:0,otpSentAt:null};state.workspaceOverrides={...(state.workspaceOverrides||{}),staff:{label:inv.name,subtitle:`${ROLE_TEMPLATES[inv.role].label} · Invitation`}};state.currentWorkspace='staff';saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();navigate('staffInvite')});
  main.querySelector('#staff-mobile-form')?.addEventListener('submit',e=>{e.preventDefault();const inv=state.staffInvitations.find(x=>x.id===state.staffSession?.inviteId),mobile=normalizeMobile(new FormData(e.currentTarget).get('mobile'));if(!inv||mobile!==inv.mobile){showFormError('staff-mobile-error',`Use the invited mobile ending ${inv?.mobile.slice(-4)||''}.`);return}state.staffSession={...state.staffSession,mobile,otpSentAt:Date.now(),otpAttempts:0};saveState(state);navigate('staffOtp')});
  main.querySelector('#staff-otp-form')?.addEventListener('submit',e=>{e.preventDefault();const entered=new FormData(e.currentTarget).get('otp'),result=otpStatus({entered,sentAt:state.staffSession?.otpSentAt,attempts:state.staffSession?.otpAttempts||0});if(result==='valid'){const inv=state.staffInvitations.find(x=>x.id===state.staffSession.inviteId);state.staffSession.verified=true;inv.status='mobile_verified';inv.mobileVerifiedAt=new Date().toISOString();inv.history.push({status:'mobile_verified',at:new Date().toLocaleString('en-IN'),actor:inv.name});saveState(state);navigate('staffInvite');toast('Mobile verified');return}state.staffSession.otpAttempts=(state.staffSession.otpAttempts||0)+1;saveState(state);showFormError('staff-otp-error',{invalid:'OTP is incorrect. Use 123456.',expired:'OTP expired. Send a new OTP.',locked:'Too many attempts. Restart invitation verification.'}[result])});
  main.querySelector('[data-action="accept-staff-invite-self"]')?.addEventListener('click',()=>{const inv=state.staffInvitations.find(x=>x.id===state.staffSession?.inviteId);if(!canAcceptStaffInvitation(inv,state.staffSession)){toast('Verify the invited mobile first');return}const owner=inv.workspace;let member=(state.peopleByWorkspace[owner]||[]).find(x=>x.mobile===inv.mobile);if(!member){member={id:inv.linkedPersonId||`PERSON-${Date.now().toString().slice(-4)}`,staffId:null,sourceInviteId:inv.id,name:inv.name,mobile:inv.mobile,role:inv.role,designation:ROLE_TEMPLATES[inv.role].label,branchIds:[inv.branchId],services:state.businessProfiles[owner]?.services||[],payType:inv.payType,payAmount:0,status:'profile_pending',documentsStatus:'pending_staff',bankStatus:'pending_staff',emergencyStatus:'pending_staff',activeAssignments:[],vehicleAssignments:[],dues:0,employmentType:inv.employmentType,reviewHistory:[]};state.peopleByWorkspace[owner].push(member)}inv.status='accepted';inv.history.push({status:'accepted',at:new Date().toLocaleString('en-IN'),actor:inv.name});state.selectedStaffId=member.id;state.staffSession.memberId=member.id;if(!state.workspaces.includes('staff'))state.workspaces.push('staff');saveState(state);renderDesktopNav();renderMobileNav();navigate('staffOnboarding');toast('Invitation accepted. Complete your own joining details')});
  main.querySelector('[data-action="decline-staff-invite-self"]')?.addEventListener('click',()=>{const inv=state.staffInvitations.find(x=>x.id===state.staffSession?.inviteId);if(!inv)return;inv.status='declined';inv.history.push({status:'declined',at:new Date().toLocaleString('en-IN'),actor:inv.name});const owner=inv.workspace;state.currentWorkspace=owner;state.staffSession=null;saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();navigate('people');toast('Invitation declined')});
  main.querySelector('#staff-invite-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),invite={id:`SINV-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,name:String(f.get('name')).trim(),mobile:String(f.get('mobile')).replace(/\D/g,''),role:f.get('role'),branchId:f.get('branchId'),responsibilities:f.getAll('responsibilities'),payType:f.get('payType'),employmentType:f.get('employmentType'),status:'pending',expires:'04 Oct 2026',invitedBy:state.person.name,history:[{status:'invited',at:new Date().toLocaleString('en-IN'),actor:state.person.name}]};const error=validateStaffInvite(invite);if(error){showFormError('staff-invite-error',error);return}const existing=[...Object.values(state.peopleByWorkspace).flat(),...state.candidates].find(x=>x.mobile===invite.mobile);if(existing){invite.linkedPersonId=existing.id;invite.name=existing.name}if(!state.staffInvitations.some(x=>x.workspace===invite.workspace&&x.mobile===invite.mobile&&['pending','mobile_verified','accepted'].includes(x.status)))state.staffInvitations.push(invite);saveState(state);navigate('people');toast(existing?'Existing verified identity linked to invitation':'Staff invitation sent')});
  main.querySelectorAll('[data-action="complete-staff-step"]').forEach(b=>b.onclick=()=>{const x=selectedStaff();if(!x)return;x[b.dataset.step]=b.dataset.step==='emergencyStatus'?'complete':'verified';if(x.status==='correction_required')x.status='profile_pending';saveState(state);renderRoute();toast('Information saved')});
  main.querySelector('[data-action="finish-staff-onboarding"]')?.addEventListener('click',()=>{const x=selectedStaff();if(!x)return;if(!staffSubmissionReady(x)){toast('Complete all three joining sections');return}x.status='submitted';x.submittedAt=new Date().toISOString();x.correctionSection=null;x.correctionReason='';const inv=state.staffInvitations.find(i=>i.id===x.sourceInviteId);if(inv){inv.status='submitted';inv.history.push({status:'submitted',at:new Date().toLocaleString('en-IN'),actor:x.name})}state.audit.unshift({id:`AUD-${Date.now()}`,event:`Staff self-service submitted: ${x.id}`,at:new Date().toLocaleString('en-IN'),actor:x.name});saveState(state);navigate('staffSubmission');toast('Sent to owner for review')});
  main.querySelector('[data-action="return-owner-demo"]')?.addEventListener('click',()=>{const owner=staffOwnerWorkspace();state.currentWorkspace=owner;saveState(state);renderWorkspace();renderDesktopNav();renderMobileNav();navigate('staffDetail');toast('Returned to owner review view')});
  main.querySelectorAll('[data-action="open-staff-workspace"]').forEach(b=>b.onclick=()=>{const x=(state.peopleByWorkspace[state.currentWorkspace]||[]).find(p=>p.id===state.selectedStaffId);if(x)showStaffWorkspace(x,b.dataset.target||'home')});
  main.querySelectorAll('[data-action="staff-review"]').forEach(b=>b.onclick=()=>{const x=(state.peopleByWorkspace[state.currentWorkspace]||[]).find(p=>p.id===state.selectedStaffId);if(!x)return;const form=main.querySelector('#staff-review-form'),f=new FormData(form),decision=b.dataset.decision,section=f.get('section'),reason=String(f.get('reason')||'').trim(),error=staffReviewDecision(x,decision,section);if(error){showFormError('staff-review-error',error);return}if(decision!=='approve'&&!reason){showFormError('staff-review-error','Add a reason for correction or rejection.');return}const at=new Date().toLocaleString('en-IN'),inv=state.staffInvitations.find(i=>i.id===x.sourceInviteId);x.reviewHistory=x.reviewHistory||[];if(decision==='approve'){x.status='active';x.staffId=x.staffId||`STF-${state.currentWorkspace.toUpperCase().slice(0,3)}-${Date.now().toString().slice(-4)}`;x.joiningDate=f.get('joiningDate');x.payAmount=Number(f.get('payAmount'));x.reportingManager=String(f.get('reportingManager'));x.access={permissions:[...ROLE_TEMPLATES[x.role].permissions],temporary:false,from:'',to:''};if(inv)inv.status='approved'}else if(decision==='correction'){x.status='correction_required';x.correctionSection=section;x.correctionReason=reason;x[section]='correction_required';if(inv)inv.status='correction_required'}else{x.status='rejected';x.rejectionReason=reason;if(inv)inv.status='rejected'}x.reviewHistory.unshift({decision,section,reason,at,actor:state.person.name});inv?.history.push({status:decision==='approve'?'approved':decision==='correction'?'correction_required':'rejected',at,actor:state.person.name});state.audit.unshift({id:`AUD-${Date.now()}`,event:`Staff onboarding ${decision}: ${x.id}`,at,actor:state.person.name});saveState(state);navigate('staffDetail');toast(decision==='approve'?`Staff activated: ${x.staffId}`:decision==='correction'?'Correction sent to staff':'Onboarding rejected')});
  main.querySelector('#staff-access-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),x=(state.peopleByWorkspace[state.currentWorkspace]||[]).find(p=>p.id===state.selectedStaffId);if(!x)return;const branches=f.getAll('branchIds'),services=f.getAll('services');if(!branches.length){toast('Select at least one branch');return}x.branchIds=branches;x.services=services;x.access={permissions:f.getAll('permissions'),temporary:Boolean(f.get('temporary')),from:f.get('from'),to:f.get('to')};saveState(state);navigate('staffDetail');toast('Role-specific access updated')});
  main.querySelectorAll('[data-action="open-opening"]').forEach(b=>b.onclick=()=>{state.selectedOpeningId=b.dataset.opening;saveState(state);navigate('openingDetail')});
  main.querySelector('[data-action="test-commercial-driver"]')?.addEventListener('click',()=>{switchWorkspace('commercialDriver');navigate('candidateProfile')});
  main.querySelector('#opening-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),branch=state.businessProfiles[state.currentWorkspace]?.branches.find(x=>x.id===f.get('branchId')),min=Number(f.get('payMin')),max=Number(f.get('payMax')),employmentType=f.get('employmentType'),endDate=f.get('endDate');if(!f.get('title')||min<=0||max<min||(employmentType==='fixed_term'&&!endDate)){showFormError('opening-error',employmentType==='fixed_term'&&!endDate?'End date is required for fixed-term work.':'Enter a title and a valid pay range.');return}const job={id:`JOB-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,title:String(f.get('title')),role:f.get('role'),branchId:f.get('branchId'),branch:branch?.name||'Branch',location:branch?.serviceArea||'Service area',count:Number(f.get('count')),payMin:min,payMax:max,payType:employmentType==='trip_only'?'per_trip':'monthly',employmentType,startDate:f.get('startDate'),endDate:endDate||'',requirements:String(f.get('requirements')).split(',').map(x=>x.trim()).filter(Boolean),approvalPolicy:f.get('approvalPolicy'),status:'open'};state.vacancies.unshift(job);state.selectedOpeningId=job.id;saveState(state);navigate('hiring');toast('Opening published to matching workers')});
  main.querySelectorAll('[data-action="invite-candidate"]').forEach(b=>b.onclick=()=>{const exists=state.jobApplications.some(a=>a.openingId===b.dataset.opening&&a.candidateId===b.dataset.candidate);if(exists){toast('Candidate already has an application');return}state.jobApplications.push({id:`JAPP-${Date.now().toString().slice(-4)}`,openingId:b.dataset.opening,candidateId:b.dataset.candidate,status:'new',joiningDate:'',expectedPay:state.candidates.find(x=>x.id===b.dataset.candidate)?.expectedPay||0,voiceIntro:'Invited by business',history:[{status:'invited',at:new Date().toLocaleString('en-IN')}]});saveState(state);toast('Candidate invited to apply')});
  main.querySelector('[data-action="apply-opening"]')?.addEventListener('click',e=>{const openingId=e.currentTarget.dataset.opening,candidateId=state.selectedCandidateId,c=state.candidates.find(x=>x.id===candidateId);let application=state.jobApplications.find(a=>a.openingId===openingId&&a.candidateId===candidateId);if(application&&!['withdrawn','rejected'].includes(application.status)){toast('Application already exists');return}const at=new Date().toLocaleString('en-IN');if(application){application.status='new';application.expectedPay=c.expectedPay;application.history.push({status:'reapplied',at})}else{application={id:`JAPP-${Date.now().toString().slice(-4)}`,openingId,candidateId,status:'new',joiningDate:'30 Sep 2026',expectedPay:c.expectedPay,voiceIntro:'Optional voice introduction',history:[{status:'applied',at}]};state.jobApplications.push(application)}saveState(state);renderRoute();toast(application.history.at(-1).status==='reapplied'?'Application sent again':'Application sent')});
  main.querySelector('[data-action="withdraw-application"]')?.addEventListener('click',e=>{const a=state.jobApplications.find(x=>x.id===e.currentTarget.dataset.application);if(a&& !['hired','withdrawn'].includes(a.status)){a.status='withdrawn';a.history.push({status:'withdrawn',at:new Date().toLocaleString('en-IN')})}saveState(state);renderRoute();toast('Application withdrawn. You can apply again later')});
  main.querySelectorAll('[data-action="change-application-status"]').forEach(s=>s.onchange=()=>{const a=state.jobApplications.find(x=>x.id===s.dataset.application);if(!a)return;a.status=s.value;a.history.push({status:s.value,at:new Date().toLocaleString('en-IN')});if(s.value==='hired'){const j=state.vacancies.find(x=>x.id===a.openingId),c=state.candidates.find(x=>x.id===a.candidateId),result=employmentResult(j.employmentType),ownerPeople=state.peopleByWorkspace[state.currentWorkspace]||[];if(result.createsStaffId&&!ownerPeople.some(x=>x.mobile===c.mobile))ownerPeople.push({id:`STAFF-${Date.now().toString().slice(-4)}`,staffId:null,name:c.name,mobile:c.mobile,role:j.role,designation:ROLE_TEMPLATES[j.role].label,branchIds:[j.branchId],services:state.businessProfiles[state.currentWorkspace].services,payType:j.payType,payAmount:a.expectedPay,status:'profile_pending',documentsStatus:'pending_staff',bankStatus:'pending_staff',emergencyStatus:'pending_staff',activeAssignments:[],vehicleAssignments:[],dues:0,sourceApplicationId:a.id});a.assignmentOnly=result.assignmentOnly;a.hiringOutcome=result.assignmentOnly?'Trip-only assignment created':'Staff onboarding required'}saveState(state);renderRoute();toast(s.value==='hired'?(a.assignmentOnly?'Trip-only assignment created':'Candidate hired; staff onboarding is pending'):'Applicant status updated')});
  main.querySelector('#candidate-profile-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),c=state.candidates.find(x=>x.id===state.selectedCandidateId)||state.candidates[0],caps=f.getAll('capabilities');if(!caps.length){toast('Select at least one type of work');return}c.name=String(f.get('name')).trim();c.capabilities=caps;c.locations=[String(f.get('location')).trim()];c.availability=String(f.get('availability')).trim();c.workPreference=f.get('workPreference');c.expectedPay=Number(f.get('expectedPay'));c.status='available';saveState(state);navigate('work');toast('Availability posted')});
  main.querySelector('#goods-order-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),order={id:`GO-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,type:f.get('type'),counterparty:String(f.get('counterparty')).trim(),goods:String(f.get('goods')).trim(),quantity:Number(f.get('quantity')),unit:f.get('unit'),goodsPrice:Number(f.get('goodsPrice')),transportResponsibility:f.get('transportResponsibility'),status:'confirmed',createdAt:new Date().toLocaleString('en-IN')},error=validateGoodsOrder(order);if(error){showFormError('goods-order-error',error);return}state.goodsOrders.unshift(order);state.selectedGoodsOrderId=order.id;saveState(state);navigate('transportRequirement');toast('Goods order saved; now arrange transport')});
  main.querySelector('#transport-requirement-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),order=state.goodsOrders.find(x=>x.id===f.get('goodsOrderId')),req={id:`TR-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,goodsOrderId:f.get('goodsOrderId'),pickup:String(f.get('pickup')).trim(),drop:String(f.get('drop')).trim(),pickupDate:f.get('pickupDate'),truckType:f.get('truckType'),capacity:Number(f.get('capacity')),goods:order?.goods||'Goods',dharamkata:f.get('dharamkata')==='yes',paymentTerms:String(f.get('paymentTerms')).trim(),arrangement:'',selectedTransporters:[],status:'draft',createdBy:state.businessProfiles[state.currentWorkspace]?.legalName||currentRole().label},error=validateTransportRequirement(req);if(error){showFormError('transport-requirement-error',error);return}state.transportRequirements.unshift(req);state.selectedRequirementId=req.id;saveState(state);navigate('arrangement');toast('Transport details saved')});
  main.querySelectorAll('[data-action="open-arrangement"]').forEach(b=>b.onclick=()=>{state.selectedRequirementId=b.dataset.requirement;saveState(state);navigate('arrangement')});
  main.querySelector('#arrangement-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),req=state.transportRequirements.find(x=>x.id===state.selectedRequirementId),mode=f.get('arrangement'),selected=f.getAll('transporters');if(!mode){showFormError('arrangement-error','Choose how transport will be arranged.');return}if(mode==='selected_transporters'&&!selected.length){showFormError('arrangement-error','Select at least one Transporter.');return}req.arrangement=mode;req.selectedTransporters=selected;req.status=mode==='own_vehicle'?'vehicle_assignment_pending':'published';saveState(state);navigate('work');toast(mode==='own_vehicle'?'Ready to assign an approved owned vehicle':mode==='selected_transporters'?'Sent only to selected Transporters':'Published to eligible Transporters')});
  main.querySelector('#buy-delivery-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),goods=String(f.get('goods')).trim(),quantity=Number(f.get('quantity')),goodsBudget=Number(f.get('goodsBudget')),transportBudget=Number(f.get('transportBudget'));if(!goods||quantity<=0||goodsBudget<=0||transportBudget<=0){showFormError('buy-delivery-error','Enter goods, quantity and both budgets.');return}state.goodsRequirements.unshift({id:`GR-${Date.now().toString().slice(-4)}`,workspace:'transporter',buyer:state.businessProfiles[state.currentWorkspace]?.legalName||'Goods Buyer',goods,quantity,unit:'tonnes',delivery:`${String(f.get('delivery')).trim()} by ${f.get('requiredBy')}`,goodsBudget,transportBudget,status:'sourcing',seller:'Not selected'});saveState(state);navigate('work');toast('Sourcing request sent to the Transporter')});
  main.querySelector('#available-load-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),req=state.transportRequirements.find(x=>x.id===f.get('requirementId'));if(!req||req.status==='draft'){showFormError('available-load-error','Select an authorized published requirement.');return}if(state.availableLoads.some(x=>x.requirementId===req.id&&x.status==='open')){showFormError('available-load-error','This requirement already has an open load post.');return}state.availableLoads.unshift({id:`AL-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,requirementId:req.id,route:`${req.pickup.split(',')[0]} → ${req.drop.split(',')[0]}`,pickup:req.pickup.split(',')[0],drop:req.drop.split(',')[0],date:req.pickupDate,truckType:req.truckType,capacity:req.capacity,goods:req.goods,authority:String(f.get('authority')).trim(),goodsOwnerDisplay:'Verified Goods Business',goodsOwnerPrivate:req.createdBy,status:'open'});saveState(state);navigate('work');toast('Available load published with Goods Owner privacy')});
  main.querySelector('#load-requirement-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),req={id:`LR-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,route:`${String(f.get('from')).trim()} → ${String(f.get('to')).trim()}`,from:String(f.get('from')).trim(),to:String(f.get('to')).trim(),date:f.get('date'),truckType:f.get('truckType'),capacity:Number(f.get('capacity')),acceptedGoods:String(f.get('acceptedGoods')).trim(),status:'open',postedBy:state.businessProfiles[state.currentWorkspace]?.legalName||currentRole().label,branch:'Selected branch'},error=validateLoadRequirement(req);if(error){showFormError('load-requirement-error',error);return}state.loadRequirements.unshift(req);saveState(state);navigate('work');toast('Looking-for-load post published')});
  main.querySelectorAll('[data-action="respond-load-requirement"]').forEach(b=>b.onclick=()=>{const source=state.loadRequirements.find(x=>x.id===b.dataset.requirement),existing=state.opportunities.find(x=>x.type==='goods_response'&&x.sourceId===source.id&&x.createdByWorkspace===state.currentWorkspace);if(existing){state.selectedOpportunityId=existing.id;saveState(state);navigate('opportunityDetail');return}const op={id:`OPP-${Date.now().toString().slice(-4)}`,type:'goods_response',sourceId:source.id,createdByWorkspace:state.currentWorkspace,participants:['goods','transporter'],title:`Rice ${source.capacity} tonnes for ${source.route}`,summary:`${state.businessProfiles[state.currentWorkspace]?.legalName||'Goods Business'} can provide compatible goods.`,status:'discussion',canonicalLoadId:null,createdAt:new Date().toLocaleString('en-IN')};state.opportunities.unshift(op);state.opportunityMessages[op.id]=[{id:`MSG-${Date.now()}`,sender:state.businessProfiles[state.currentWorkspace]?.legalName||'Goods Business',text:'We have compatible confirmed goods. Please review the route and terms.',kind:'text',at:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}];state.selectedOpportunityId=op.id;saveState(state);navigate('opportunityDetail');toast('Opportunity created; confirm terms before Load creation')});
  main.querySelector('#truck-availability-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),post={id:`TA-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,vehicleId:'VEH-DEMO',registration:String(f.get('registration')).trim().toUpperCase(),location:String(f.get('location')).trim(),availableDate:f.get('availableDate'),truckType:f.get('truckType'),capacity:Number(f.get('capacity')),destinationPreference:String(f.get('destinationPreference')).trim(),crew:f.get('crew'),documents:f.get('documents'),status:'available'},error=validateTruckAvailability(post);if(error){showFormError('truck-availability-error',error);return}state.truckAvailability.unshift(post);saveState(state);navigate('routeOpportunities');toast('Truck availability published to compatible Transporters')});
  main.querySelectorAll('[data-action="open-opportunity"]').forEach(b=>b.onclick=()=>{state.selectedOpportunityId=b.dataset.opportunity;saveState(state);navigate('opportunityDetail')});
  main.querySelectorAll('[data-action="start-load-discussion"]').forEach(b=>b.onclick=()=>{const load=state.availableLoads.find(x=>x.id===b.dataset.load);let op=state.opportunities.find(x=>x.type==='available_load'&&x.sourceId===load.id);if(!op){op={id:`OPP-${Date.now().toString().slice(-4)}`,type:'available_load',sourceId:load.id,createdByWorkspace:state.currentWorkspace,participants:['goods','transporter','vehicle'],title:`Truck discussion for ${load.route}`,summary:`${load.goods} · ${load.capacity} t · ${load.truckType}`,status:'discussion',canonicalLoadId:null,createdAt:new Date().toLocaleString('en-IN')};state.opportunities.unshift(op);state.opportunityMessages[op.id]=[]}state.selectedOpportunityId=op.id;saveState(state);navigate('opportunityChat')});
  main.querySelector('[data-action="convert-opportunity"]')?.addEventListener('click',e=>{const op=state.opportunities.find(x=>x.id===e.currentTarget.dataset.opportunity);if(!canConvertOpportunity(op)){toast(op?.canonicalLoadId?`Load ${op.canonicalLoadId} already exists`:'Opportunity cannot be converted yet');return}const load={id:`LD-${Date.now().toString().slice(-5)}`,opportunityId:op.id,title:op.title,status:'confirmed',parties:[...op.participants],createdAt:new Date().toLocaleString('en-IN')};state.canonicalLoads.push(load);op.canonicalLoadId=load.id;op.status='converted';state.audit.unshift({id:`AUD-${Date.now()}`,event:`Opportunity converted to canonical Load: ${load.id}`,at:load.createdAt,actor:state.person.name});saveState(state);renderRoute();toast(`Load ${load.id} created once`)});
  main.querySelector('#opportunity-message-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=String(f.get('message')).trim(),op=state.opportunities.find(x=>x.id===state.selectedOpportunityId);if(!text||!op)return;(state.opportunityMessages[op.id]||=[]).push({id:`MSG-${Date.now()}`,sender:state.businessProfiles[state.currentWorkspace]?.legalName||currentRole().label,text,kind:'text',at:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})});saveState(state);renderRoute();toast('Message sent to opportunity participants')});
  main.querySelector('[data-action="add-voice-message"]')?.addEventListener('click',()=>{const op=state.opportunities.find(x=>x.id===state.selectedOpportunityId);if(!op)return;(state.opportunityMessages[op.id]||=[]).push({id:`MSG-${Date.now()}`,sender:state.businessProfiles[state.currentWorkspace]?.legalName||currentRole().label,text:'Voice note: pickup time and loading contact confirmed.',kind:'voice',at:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})});saveState(state);renderRoute();toast('Voice note added with transcript')});
  main.querySelector('#owner-cover-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),cover={id:`COVER-${Date.now().toString().slice(-4)}`,workspace:state.currentWorkspace,delegateId:f.get('delegateId'),from:f.get('from'),to:f.get('to'),branchIds:f.getAll('branchIds'),paymentLimit:Number(f.get('paymentLimit')),blockedActions:['business.ownership','bank.change','business.close'],status:'active'};const error=validateOwnerCover(cover);if(error){showFormError('owner-cover-error',error);return}state.ownerCovers.push(cover);state.audit.unshift({id:`AUD-${Date.now()}`,event:`Owner Cover activated: ${cover.id}`,at:new Date().toLocaleString('en-IN'),actor:state.person.name});saveState(state);renderRoute();toast('Owner Cover activated with time and payment limits')});
  main.querySelector('[data-action="reassign-staff-work"]')?.addEventListener('click',()=>{const x=(state.peopleByWorkspace[state.currentWorkspace]||[]).find(p=>p.id===state.selectedStaffId);if(!x)return;x.activeAssignments=[];x.vehicleAssignments=[];saveState(state);renderRoute();toast('Active work and vehicles reassigned')});
  main.querySelector('[data-action="complete-offboarding"]')?.addEventListener('click',()=>{const x=(state.peopleByWorkspace[state.currentWorkspace]||[]).find(p=>p.id===state.selectedStaffId);if(!x)return;if(x.activeAssignments.length||x.vehicleAssignments.length){toast('Reassign active work and vehicles first');return}x.status='offboarded';x.accessRevokedAt=new Date().toISOString();state.audit.unshift({id:`AUD-${Date.now()}`,event:`Staff offboarded: ${x.id}`,at:new Date().toLocaleString('en-IN'),actor:state.person.name});saveState(state);navigate('staffDetail');toast('Future access stopped; history and dues retained')});
}

document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){if(route==='more')openMore();else navigate(route)}const workspace=e.target.closest('[data-workspace]')?.dataset.workspace;if(workspace)switchWorkspace(workspace);if(e.target.closest('[data-workspace-action="invitations"]')){closeOverlays();if(state.currentWorkspace!=='personal'){state.currentWorkspace='personal';renderWorkspace();renderDesktopNav();renderMobileNav()}navigate('invitations')}if(e.target.closest('[data-workspace-action="add-business"]')){closeOverlays();if(state.currentWorkspace!=='personal'){state.currentWorkspace='personal';renderWorkspace();renderDesktopNav();renderMobileNav()}currentApplication();navigate('businessStart')}if(e.target.closest('[data-close-dialog]'))$('workspace-dialog').hidden=true;if(e.target.closest('[data-close-more]'))$('more-sheet').hidden=true});
$('workspace-button').onclick=openWorkspaceDialog;$('menu-button').onclick=()=>{sidebar.classList.add('open');backdrop.hidden=false};backdrop.onclick=closeOverlays;$('reset-demo').onclick=()=>{state=resetState();renderAll();location.hash='#/home';toast('Demo data reset')};$('ai-button').onclick=()=>toast('AI assistant arrives in Phase P8');
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlays()});window.addEventListener('hashchange',renderRoute);

function renderAll(){renderWorkspace();renderDesktopNav();renderMobileNav();if(!location.hash)location.hash=state.auth?.status==='authenticated'?'#/home':'#/welcome';renderRoute();app.setAttribute('aria-busy','false')}
renderAll();

window.MoveAIVNextTest={state:()=>structuredClone(state),switchWorkspace,canOpen,reset:()=>{state=resetState();renderAll()},startSignup:()=>{state=signupDemoState();saveState(state);navigate('welcome')},routes:()=>Object.keys(ROUTES)};
