import {ROLE_TEMPLATES} from './people-rules.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const head=(title,description,action='')=>`<div class="page-header"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;
const pill=s=>`<span class="status-pill ${['pending','under_review','correction_required'].includes(s)?'warning':''}">${esc(String(s).replaceAll('_',' '))}</span>`;

export function purposeScreen(){return `${head('What do you want to do?','Choose one short path. You can add another activity later.')}<section class="panel form-panel narrow"><div class="service-grid"><button class="service-choice" data-purpose="personal"><span class="service-icon">⌂</span><span><b>Use personal services</b><small>Moving, a personal Driver, products or home services</small></span></button><button class="service-choice" data-purpose="work"><span class="service-icon">♟</span><span><b>Find work</b><small>Driver, Khalasi, Helper or staff</small></span></button><button class="service-choice" data-purpose="business"><span class="service-icon">▤</span><span><b>Create a business</b><small>Goods, Transport, Trucks or Movers</small></span></button><button class="service-choice" data-purpose="invitations"><span class="service-icon">✉</span><span><b>Review invitations</b><small>Join an existing business safely</small></span></button></div><button class="button text full" data-purpose="later">Do this later</button></section>`}

export function consentDetailsScreen(state){return `${head('Consent and privacy','Read the short scope before requesting an OTP.')}<section class="panel form-panel narrow"><div class="review-checklist"><span class="done">✓ Verify that this mobile belongs to you</span><span class="done">✓ Protect account and business invitations</span><span class="done">✓ Send security and service-status notifications</span><span>○ Marketing is not included in this consent</span></div><dl class="fact-list"><div><dt>Consent version</dt><dd>2026-09-27</dd></div><div><dt>Recorded</dt><dd>${esc(state.auth?.consentedAt||'After OTP request')}</dd></div></dl><button class="button primary full" data-route="signup">Back to mobile verification</button></section>`}

export function recoverySupportScreen(){return `${head('Account recovery support','The existing account remains locked while ownership is checked.')}<section class="panel form-panel narrow"><div class="action-warning"><b>Login stopped safely</b><span>No business names, branches or private activity are displayed.</span></div><div class="review-checklist"><span class="done">✓ Pending recovery cleared</span><span>○ Support verifies identity and mobile ownership</span><span>○ A verified recovery link is sent separately</span></div><button class="button primary full" data-route="signup">Use another mobile number</button></section>`}

export function productSearchScreen(state){return `${head('Search products','Search products directly. Store assignment happens internally.')}<form id="product-search-form" class="panel filter-bar"><input name="query" value="rice" placeholder="Search products"><button class="button primary">Search</button></form><div class="candidate-grid">${state.products.map(p=>`<article class="panel candidate-card"><span class="market-icon">🛒</span><h2>${esc(p.name)}</h2><p>${esc(p.size)} · ${esc(p.category)}</p><b>₹${Number(p.price).toLocaleString('en-IN')}</b><small>${esc(p.stock)}</small><button class="button primary full" data-action="buy-product" data-product="${p.id}">Buy now</button></article>`).join('')}</div><div class="info-banner"><b>No nearby-store selection</b><span>The platform assigns an eligible fulfilment partner after the order is confirmed.</span></div>`}

export function customerOrdersScreen(state){return `${head('My orders','Track confirmed product orders and internally assigned fulfilment.')}<div class="market-list panel">${state.customerOrders.map(o=>`<article class="market-row"><span class="market-icon">▥</span><span><b>${esc(o.id)}</b><small>${o.items.length} item(s) · ₹${Number(o.total).toLocaleString('en-IN')} · ${esc(o.eta)}</small></span>${pill(o.status)}<button class="button secondary" data-toast="Order tracking opened">Track</button></article>`).join('')}</div>`}

export function branchEditorScreen(state){const editing=state.branchDraft||{},p=state.businessProfiles[state.currentWorkspace],services=p?.services||[];return `${head(editing.id?'Edit branch':'Add branch','Store operating coverage and responsibility, not a sample branch.')}<form id="branch-editor-form" class="panel form-panel narrow"><input type="hidden" name="id" value="${esc(editing.id||'')}"><div class="form-grid two"><label><span>Branch name</span><input name="name" value="${esc(editing.name||'Lucknow Branch')}"></label><label><span>Contact mobile</span><input name="mobile" maxlength="10" value="${esc(editing.mobile||'9876502200')}"></label><label class="wide"><span>Full address</span><textarea name="address">${esc(editing.address||'Gomti Nagar, Lucknow, Uttar Pradesh')}</textarea></label><label><span>Service area</span><input name="serviceArea" value="${esc(editing.serviceArea||'Lucknow and nearby districts')}"></label><label><span>Manager</span><input name="manager" value="${esc(editing.manager||'Pankaj Meena')}"></label><fieldset class="wide"><legend>Services</legend><div class="check-grid">${services.map(s=>`<label><input type="checkbox" name="services" value="${s}" ${editing.services?.includes(s)||!editing.id?'checked':''}> ${esc(s)}</label>`).join('')}</div></fieldset></div><p id="branch-editor-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-route="branches">Cancel</button><button class="button primary">Save branch</button></div></form>`}

export function adminDocumentsScreen(state){const docs=state.businessApplications.flatMap(a=>a.documents.map((d,i)=>({...d,application:a.id,business:a.legalName,version:d.version||1,index:i+1})));return `${head('Documents','Review current versions, corrections and expiry without changing business ownership.')}<div class="document-list panel">${docs.map(d=>`<div class="document-row"><span class="document-icon">▣</span><span class="document-copy"><b>${esc(d.type)} · ${esc(d.business)}</b><small>${esc(d.name)} · v${d.version} · ${esc(d.status)}</small></span><button class="button secondary" data-toast="Secure document preview opened">View</button></div>`).join('')}</div>`}

export function adminUsersScreen(state){const people=[state.person,...state.candidates,...Object.values(state.peopleByWorkspace).flat()];const unique=[...new Map(people.filter(Boolean).map(p=>[p.mobile||p.id,p])).values()];return `${head('Users','One mobile identity can have several authorised contexts without duplication.')}<div class="people-list panel">${unique.map(p=>`<article class="person-row"><span class="avatar">${esc(p.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span><span><b>${esc(p.name)}</b><small>${p.mobile?`+91 ••••••${p.mobile.slice(-4)}`:esc(p.id)} · ${esc(p.status||'active')}</small></span></article>`).join('')}</div>`}

export function adminAuditScreen(state){return `${head('Audit','Actor, workspace, action and time remain immutable in the prototype history.')}<section class="panel"><div class="timeline">${state.audit.map(a=>`<div><i></i><span><b>${esc(a.event)}</b><small>${esc(a.at)} · ${esc(a.actor)}${a.role?` · ${esc(a.role)}`:''}${a.workspace?` · ${esc(a.workspace)}`:''}</small></span></div>`).join('')}</div></section>`}

export function ownVehicleAssignmentScreen(state){const vehicles=state.ownedVehicles.goods||[],drivers=state.candidates.filter(c=>c.capabilities.includes('driver')&&c.status==='available'),helpers=state.candidates.filter(c=>c.capabilities.includes('helper')&&c.status==='available');return `${head('Assign owned vehicle','Reserve an approved idle truck and available crew for this requirement.')}<form id="own-vehicle-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Approved vehicle</span><select name="vehicleId"><option value="">Select vehicle</option>${vehicles.map(v=>`<option value="${v.id}">${esc(v.registration)} · ${esc(v.status)} · ${esc(v.documents)}</option>`).join('')}</select></label><label><span>Driver</span><select name="driverId"><option value="">Select Driver</option>${drivers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label><span>Khalasi</span><select name="helperId"><option value="">Not required</option>${helpers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label></div><p id="own-vehicle-error" class="field-error" hidden></p><button class="button primary full">Confirm vehicle and crew</button></form>`}

export function sellerSourcingScreen(state){const req=state.goodsRequirements[0];return `${head('Source verified Seller',`${req.goods} · ${req.quantity} ${req.unit} · ${req.delivery}`)}<form id="seller-sourcing-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Verified Seller</span><select name="seller"><option>Sharma Foods</option><option>Bihar Agro</option></select></label><label><span>Goods price</span><input name="goodsPrice" type="number" value="615000"></label><label><span>Freight</span><input name="freight" type="number" value="72000"></label><label><span>Transporter service fee</span><input name="serviceFee" type="number" value="12000"></label></div><p id="seller-sourcing-error" class="field-error" hidden></p><button class="button primary full">Send proposal to Buyer</button></form>`}

export function transportOfferScreen(state,truckOwner=false){const offer=state.transportOffers.find(o=>o.id===state.selectedOfferId)||state.transportOffers[0];return `${head(truckOwner?'Truck Owner offer':'Transport offer',offer?`${offer.route} · ${offer.transporter}`:'Create rate, advance and conditions')}<form id="transport-offer-form" class="panel form-panel narrow"><input type="hidden" name="offerId" value="${esc(offer?.id||'')}"><div class="form-grid two"><label><span>Freight</span><input name="freight" type="number" value="${offer?.freight||68000}"></label><label><span>Truck Owner advance</span><input name="advance" type="number" value="${offer?.advance||12000}"></label><label><span>Pickup date</span><input name="pickupDate" type="date" value="${offer?.pickupDate||'2026-10-01'}"></label><label><span>Offer expiry</span><input name="expiresAt" type="date" value="${offer?.expiresAt||'2026-09-30'}"></label><label class="wide"><span>Conditions</span><textarea name="conditions">${esc(offer?.conditions||'Balance after POD. Toll and Dharamkata reimbursed separately.')}</textarea></label></div><p id="transport-offer-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button danger" data-action="offer-decision" data-decision="rejected">Reject</button><button type="button" class="button secondary" data-action="offer-decision" data-decision="countered">Counter</button><button class="button primary" type="submit">${truckOwner?'Accept offer':'Send offer'}</button></div></form>`}

export function applyOpeningScreen(state){const job=state.vacancies.find(x=>x.id===state.selectedOpeningId),candidate=state.candidates.find(x=>x.id===state.selectedCandidateId);return `${head('Confirm application',`${candidate?.name||'Candidate'} · ${job?.title||'Opening'}`)}<form id="apply-opening-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Available/joining date</span><input name="joiningDate" type="date" value="2026-10-01"></label><label><span>Expected pay</span><input name="expectedPay" type="number" value="${candidate?.expectedPay||3000}"></label><label class="wide"><span>Voice introduction (optional)</span><input name="voiceIntro" value="18 sec voice introduction"></label></div><label class="consent-row"><input type="checkbox" name="consent"><span>Share this work profile and verification status with this business.</span></label><p id="apply-opening-error" class="field-error" hidden></p><button class="button primary full">Submit application</button></form>`}

export function candidateReviewScreen(state){const c=state.candidates.find(x=>x.id===state.selectedCandidateId)||state.candidates[0];return `${head('Candidate verification',`${c.name} · ${c.capabilities.map(x=>ROLE_TEMPLATES[x]?.label||x).join(', ')}`)}<section class="panel form-panel narrow"><div class="review-checklist"><span class="done">✓ Mobile verified</span><span>○ Identity and licence capability</span><span>○ Expiry and vehicle-class check</span></div><label><span>Reason/note</span><textarea id="candidate-review-note" placeholder="Required for correction or rejection"></textarea></label><div class="form-actions"><button class="button danger" data-action="candidate-review" data-decision="rejected">Reject</button><button class="button secondary" data-action="candidate-review" data-decision="correction_required">Request correction</button><button class="button primary" data-action="candidate-review" data-decision="verified">Approve capability</button></div></section>`}

export function employmentChangeScreen(state){const x=Object.values(state.peopleByWorkspace).flat().find(p=>p.id===state.selectedStaffId);return `${head('Employment change',`${x?.name||'Staff'} · effective-dated history`)}<form id="employment-change-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>New role</span><select name="role">${Object.entries(ROLE_TEMPLATES).map(([id,r])=>`<option value="${id}" ${x?.role===id?'selected':''}>${esc(r.label)}</option>`).join('')}</select></label><label><span>New monthly/pay amount</span><input name="payAmount" type="number" value="${x?.payAmount||0}"></label><label><span>Effective date</span><input name="effectiveDate" type="date" value="2026-10-01"></label><label><span>Reason</span><input name="reason" value="Branch responsibility update"></label></div><p id="employment-change-error" class="field-error" hidden></p><button class="button primary full">Submit approved change</button></form>`}

export function staffWorkScreen(state,member){return `${head('My Work',`${member.name} · only assigned branch and tasks`)}<section class="panel"><div class="activity-list">${(member.activeAssignments||[]).map(id=>`<div class="activity-item"><span class="activity-icon">▦</span><span class="activity-copy"><b>${esc(id)}</b><small>Assigned to ${esc((member.branchIds||[]).join(', '))}</small></span>${pill('active')}</div>`).join('')||'<div class="empty-inline"><b>No assigned work</b><small>Unassigned business work stays hidden.</small></div>'}</div></section>`}
export function staffMessagesScreen(state,member){return `${head('Messages',`${member.name} · permitted job and branch channels`)}<section class="panel"><div class="chat-message"><b>Jaipur operations</b><p>Vehicle allocation for your assigned work is ready.</p><small>Internal branch channel</small></div></section>`}
export function staffMoneyScreen(state,member){return `${head('My Money',`${member.name} · own pay only`)}<div class="metrics"><div class="metric"><span>Pay amount</span><b>₹${Number(member.payAmount||0).toLocaleString('en-IN')}</b><small>${esc(member.payType||'monthly')}</small></div><div class="metric"><span>Amount due</span><b>₹${Number(member.dues||0).toLocaleString('en-IN')}</b><small>Visible only to you and authorised Accounts</small></div></div>`}
