import {ARRANGEMENT_MODES, routeMatch, privatePartyLabel} from './marketplace-rules.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const head = (title, description, action = '') => `<div class="page-header"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;
const pill = value => `<span class="status-pill ${['draft','discussion','sourcing'].includes(value) ? 'warning' : ''}">${esc(String(value).replaceAll('_',' '))}</span>`;
const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;

function opportunityCard(item) {
  return `<button class="opportunity-card" data-action="open-opportunity" data-opportunity="${item.id}"><span class="opportunity-icon">${item.type === 'truck_match' ? '🚚' : '▦'}</span><span><b>${esc(item.title)}</b><small>${esc(item.summary)}</small></span>${pill(item.status)}<i>›</i></button>`;
}

export function marketplaceHomeScreen(state) {
  const workspace = state.currentWorkspace;
  if (workspace === 'goods') {
    const requirements = state.transportRequirements.filter(x => x.workspace === 'goods');
    return `${head('Loads and goods','Create goods first, then arrange transport with your truck, selected Transporters or the eligible network.',`<button class="button primary" data-route="goodsOrder">+ Goods order</button>`)}
      <div class="shortcut-grid market-shortcuts">
        <button class="shortcut" data-route="goodsOrder"><span class="shortcut-icon">📦</span><b>Create goods order</b><small>Buyer, seller and goods price</small></button>
        <button class="shortcut" data-route="transportRequirement"><span class="shortcut-icon">🚚</span><b>Arrange transport</b><small>Route, vehicle and Dharamkata</small></button>
        <button class="shortcut" data-route="buyWithDelivery"><span class="shortcut-icon">🛒</span><b>Buy with delivery</b><small>Transporter sources goods</small></button>
        <button class="shortcut" data-route="transporterRequirements"><span class="shortcut-icon">⌕</span><b>Transporters need loads</b><small>Respond with available goods</small></button>
      </div>
      <div class="metrics"><div class="metric"><span>Goods orders</span><b>${state.goodsOrders.length}</b><small>Commercial agreements</small></div><div class="metric"><span>Transport requests</span><b>${requirements.length}</b><small>One published</small></div><div class="metric"><span>Opportunities</span><b>${state.opportunities.filter(x=>x.participants.includes('goods')).length}</b><small>Scoped conversations</small></div><div class="metric"><span>Confirmed loads</span><b>${state.canonicalLoads.length}</b><small>Created once</small></div></div>
      <div class="grid two"><section class="panel"><div class="panel-header"><div><h2>My transport requirements</h2><p>Goods and transport remain separate records.</p></div></div><div class="market-list">${requirements.map(r=>`<article class="market-row"><span class="market-icon">🚚</span><span><b>${esc(r.goods)}</b><small>${esc(r.pickup)} → ${esc(r.drop)} · ${r.capacity} t</small></span>${pill(r.status)}<button class="button secondary" data-action="open-arrangement" data-requirement="${r.id}">Arrangement</button></article>`).join('')}</div></section><section class="panel"><h2>Active opportunities</h2><div class="market-list">${state.opportunities.filter(x=>x.participants.includes('goods')).map(opportunityCard).join('')}</div></section></div>`;
  }
  if (workspace === 'vehicle') return vehicleOpportunityHome(state);
  return transporterOpportunityHome(state);
}

function transporterOpportunityHome(state) {
  return `${head('Load marketplace','Post confirmed loads, publish capacity looking for goods and respond to matched businesses.',`<button class="button primary" data-route="postAvailableLoad">+ Post load</button>`)}
    <div class="shortcut-grid market-shortcuts">
      <button class="shortcut" data-route="postAvailableLoad"><span class="shortcut-icon">📦</span><b>Available load</b><small>Confirmed goods need a truck</small></button>
      <button class="shortcut" data-route="postLoadRequirement"><span class="shortcut-icon">⌕</span><b>Looking for load</b><small>Route and capacity</small></button>
      <button class="shortcut" data-route="goodsRequirements"><span class="shortcut-icon">🛒</span><b>Source goods</b><small>Buyer delivery requests</small></button>
      <button class="shortcut" data-route="routeOpportunities"><span class="shortcut-icon">🧭</span><b>Route opportunities</b><small>Nearby compatible work</small></button>
    </div>
    <div class="metrics"><div class="metric"><span>Available loads</span><b>${state.availableLoads.filter(x=>x.status==='open').length}</b><small>Authority checked</small></div><div class="metric"><span>Looking for loads</span><b>${state.loadRequirements.filter(x=>x.status==='open').length}</b><small>Routes published</small></div><div class="metric"><span>Available trucks</span><b>${state.truckAvailability.filter(x=>x.status==='available').length}</b><small>Approved documents</small></div><div class="metric"><span>Discussions</span><b>${state.opportunities.filter(x=>x.participants.includes('transporter')).length}</b><small>Private and scoped</small></div></div>
    <div class="grid two"><section class="panel"><h2>Available loads</h2><div class="market-list">${state.availableLoads.map(load=>`<article class="market-row"><span class="market-icon">📦</span><span><b>${esc(load.route)}</b><small>${esc(load.goods)} · ${load.capacity} t · ${esc(privatePartyLabel(load,state.currentWorkspace))}</small></span>${pill(load.status)}<button class="button secondary" data-action="start-load-discussion" data-load="${load.id}">Discuss</button></article>`).join('')}</div></section><section class="panel"><h2>Matched discussions</h2><div class="market-list">${state.opportunities.filter(x=>x.participants.includes('transporter')).map(opportunityCard).join('')}</div></section></div>`;
}

function vehicleOpportunityHome(state) {
  return `${head('Work and next loads','Publish an idle truck and see compatible work near its current or expected route.',`<button class="button primary" data-route="postAvailableTruck">+ Available truck</button>`)}
    <div class="shortcut-grid market-shortcuts"><button class="shortcut" data-route="postAvailableTruck"><span class="shortcut-icon">🚚</span><b>Post available truck</b><small>Location, date and crew</small></button><button class="shortcut" data-route="routeOpportunities"><span class="shortcut-icon">🧭</span><b>Next load</b><small>Route-compatible work</small></button></div>
    <section class="panel"><h2>My availability</h2><div class="market-list">${state.truckAvailability.map(t=>`<article class="market-row"><span class="market-icon">🚚</span><span><b>${esc(t.registration)}</b><small>${esc(t.location)} · ${esc(t.truckType)} · ${t.capacity} t · ${esc(t.crew)}</small></span>${pill(t.status)}</article>`).join('')}</div></section>`;
}

export function goodsOrderScreen(state) {
  return `${head('Create goods order','Record the commercial goods agreement before arranging transport.')}<form id="goods-order-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Transaction</span><select name="type"><option value="sell">Sell goods</option><option value="buy">Buy goods</option></select></label><label><span>Buyer / Seller</span><input name="counterparty" value="Metro Retail"></label><label><span>Goods</span><input name="goods" value="Rice bags"></label><label><span>Quantity</span><input name="quantity" type="number" value="20"></label><label><span>Unit</span><select name="unit"><option>tonnes</option><option>bags</option><option>kilograms</option></select></label><label><span>Confirmed goods price</span><input name="goodsPrice" type="number" value="760000"></label><fieldset class="wide"><legend>Who arranges transport?</legend><div class="check-grid"><label><input type="radio" name="transportResponsibility" value="seller" checked> Seller</label><label><input type="radio" name="transportResponsibility" value="buyer"> Buyer</label></div></fieldset></div><p id="goods-order-error" class="field-error" hidden></p><div class="info-banner"><b>Goods and freight stay separate</b><span>This order records goods price only. Freight, advance, toll and Dharamkata belong to the transport requirement and trip ledger.</span></div><div class="form-actions"><button type="button" class="button secondary" data-route="work">Cancel</button><button class="button primary" type="submit">Save and arrange transport</button></div></form>`;
}

export function transportRequirementScreen(state) {
  const orders=state.goodsOrders.filter(x=>x.status==='confirmed');
  return `${head('Create transport requirement','Use a confirmed goods order. Add route, vehicle, Dharamkata and payment terms.')}<form id="transport-requirement-form" class="panel form-panel narrow"><div class="form-grid two"><label class="wide"><span>Goods order</span><select name="goodsOrderId">${orders.map(o=>`<option value="${o.id}">${esc(o.id)} · ${esc(o.goods)} · ${o.quantity} ${esc(o.unit)}</option>`).join('')}</select></label><label><span>Pickup</span><input name="pickup" value="Patna Warehouse, Bihar"></label><label><span>Delivery</span><input name="drop" value="Okhla, Delhi"></label><label><span>Pickup date</span><input name="pickupDate" type="date" value="2026-09-30"></label><label><span>Vehicle size</span><select name="truckType"><option>14-wheel open</option><option>22-ft closed</option><option>Pickup</option></select></label><label><span>Capacity (tonnes)</span><input name="capacity" type="number" value="20"></label><label><span>Dharamkata</span><select name="dharamkata"><option value="yes">Required</option><option value="no">Not required</option></select></label><label class="wide"><span>Payment terms</span><textarea name="paymentTerms">₹12,000 advance; balance after POD</textarea></label></div><p id="transport-requirement-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-route="work">Cancel</button><button class="button primary" type="submit">Continue to arrangement</button></div></form>`;
}

export function arrangementScreen(state) {
  const req=state.transportRequirements.find(x=>x.id===state.selectedRequirementId)||state.transportRequirements[0];
  return `${head('Choose transport arrangement',`${req?.goods||'Goods'} · ${req?.pickup||''} → ${req?.drop||''}`)}<form id="arrangement-form" class="panel form-panel narrow"><div class="arrangement-grid">${Object.entries(ARRANGEMENT_MODES).map(([id,item])=>`<label class="arrangement-choice"><input type="radio" name="arrangement" value="${id}" ${req?.arrangement===id?'checked':''}><span class="arrangement-icon">${id==='own_vehicle'?'🚚':id==='selected_transporters'?'✓':'◉'}</span><span><b>${esc(item.label)}</b><small>${id==='own_vehicle'?'Assign an approved owned vehicle.':id==='selected_transporters'?'Only chosen Transporters can view and respond.':'Eligible Transporters receive the masked requirement.'}</small></span></label>`).join('')}</div><label class="field-label">Selected Transporters</label><div class="check-grid"><label><input type="checkbox" name="transporters" value="Raj Logistics" checked> Raj Logistics</label><label><input type="checkbox" name="transporters" value="FastRoad Transport"> FastRoad Transport</label></div><p id="arrangement-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-route="transportRequirement">Back</button><button class="button primary" type="submit">Publish requirement</button></div></form>`;
}

export function buyWithDeliveryScreen() {
  return `${head('Buy goods with delivery','Ask a verified Transporter to source goods and arrange delivery.')}<form id="buy-delivery-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Goods needed</span><input name="goods" value="Premium rice"></label><label><span>Quantity (tonnes)</span><input name="quantity" type="number" value="15"></label><label><span>Deliver to</span><input name="delivery" value="Noida"></label><label><span>Required by</span><input name="requiredBy" type="date" value="2026-10-04"></label><label><span>Goods budget</span><input name="goodsBudget" type="number" value="615000"></label><label><span>Transport budget</span><input name="transportBudget" type="number" value="72000"></label><label class="wide"><span>Send to</span><select name="transporter"><option>Raj Logistics</option><option>Eligible verified Transporters</option></select></label></div><p id="buy-delivery-error" class="field-error" hidden></p><div class="info-banner"><b>Buyer approves before confirmation</b><span>The Transporter can source Sellers and prepare a goods, freight and service-fee breakdown. The Transporter is never shown as the Seller.</span></div><button class="button primary full" type="submit">Publish sourcing request</button></form>`;
}

export function goodsRequirementsScreen(state) {
  return `${head('Goods requirements','Source verified Sellers for Buyer delivery requests.')}<div class="market-list panel">${state.goodsRequirements.map(g=>`<article class="market-row"><span class="market-icon">🛒</span><span><b>${esc(g.goods)} · ${g.quantity} ${esc(g.unit)}</b><small>${esc(g.buyer)} · ${esc(g.delivery)} · Goods ${money(g.goodsBudget)} + Transport ${money(g.transportBudget)}</small></span>${pill(g.status)}<button class="button secondary" data-toast="Seller sourcing workspace opened">Source seller</button></article>`).join('')}</div>`;
}

export function postAvailableLoadScreen(state) {
  return `${head('Post available load','Publish confirmed goods needing a compatible truck.')}<form id="available-load-form" class="panel form-panel narrow"><div class="form-grid two"><label class="wide"><span>Authorized requirement</span><select name="requirementId">${state.transportRequirements.map(r=>`<option value="${r.id}">${esc(r.id)} · ${esc(r.goods)} · ${esc(r.pickup)} → ${esc(r.drop)}</option>`).join('')}</select></label><label><span>Authority</span><input name="authority" value="Authorized by Sharma Foods"></label><label><span>Goods owner display</span><input value="Verified Goods Business" disabled></label></div><div class="info-banner"><b>Privacy before matching</b><span>Goods Owner name and mobile stay masked until the authorized parties enter a scoped opportunity.</span></div><p id="available-load-error" class="field-error" hidden></p><button class="button primary full" type="submit">Publish available load</button></form>`;
}

export function postLoadRequirementScreen() {
  return `${head('Post that you need a load','Publish route and truck capacity. This is an opportunity, not a confirmed Load.')}<form id="load-requirement-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>From</span><input name="from" value="Jaipur"></label><label><span>To</span><input name="to" value="Delhi NCR"></label><label><span>Available date</span><input name="date" type="date" value="2026-10-01"></label><label><span>Truck type</span><select name="truckType"><option>22-ft closed</option><option>14-wheel open</option></select></label><label><span>Capacity (tonnes)</span><input name="capacity" type="number" value="12"></label><label><span>Accepted goods</span><input name="acceptedGoods" value="FMCG, packaged food"></label></div><p id="load-requirement-error" class="field-error" hidden></p><button class="button primary full" type="submit">Publish looking-for-load post</button></form>`;
}

export function transporterRequirementsScreen(state) {
  return `${head('Transporters looking for loads','Respond with available goods. A confirmed Load is created only after both parties agree.')}<div class="market-list panel">${state.loadRequirements.map(r=>`<article class="market-row"><span class="market-icon">⌕</span><span><b>${esc(r.from)} → ${esc(r.to)}</b><small>${esc(r.postedBy)} · ${esc(r.truckType)} · ${r.capacity} t · ${esc(r.acceptedGoods)}</small></span>${pill(r.status)}<button class="button primary" data-action="respond-load-requirement" data-requirement="${r.id}">Respond with goods</button></article>`).join('')}</div>`;
}

export function postAvailableTruckScreen(state) {
  const seeded=state.truckAvailability[0];
  return `${head('Post available truck','Only approved vehicles can be shown to Transporters.')}<form id="truck-availability-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Registration</span><input name="registration" value="${esc(seeded.registration)}"></label><label><span>Current location</span><input name="location" value="${esc(seeded.location)}"></label><label><span>Available date</span><input name="availableDate" type="date" value="${esc(seeded.availableDate)}"></label><label><span>Truck type</span><select name="truckType"><option>22-ft closed</option><option>14-wheel open</option></select></label><label><span>Capacity (tonnes)</span><input name="capacity" type="number" value="${seeded.capacity}"></label><label><span>Destination preference</span><input name="destinationPreference" value="${esc(seeded.destinationPreference)}"></label><label class="wide"><span>Crew</span><select name="crew"><option>Driver + Khalasi ready</option><option>Driver ready; need Khalasi</option><option>Need Driver and Khalasi</option></select></label></div><input type="hidden" name="documents" value="approved"><p id="truck-availability-error" class="field-error" hidden></p><button class="button primary full" type="submit">Publish truck availability</button></form>`;
}

export function routeOpportunitiesScreen(state) {
  const truck=state.truckAvailability[0];
  const matches=[...state.loadRequirements,...state.availableLoads].filter(item=>routeMatch(truck,item));
  return `${head('Route opportunities',`${truck.registration} · ${truck.location} · next-load recommendations`)}<div class="filter-bar"><span>${matches.length} compatible opportunities</span><span class="status-pill info">Route + empty distance + vehicle + date + documents + crew</span></div><div class="market-list panel">${matches.map(item=>`<article class="market-row"><span class="market-icon">🧭</span><span><b>${esc(item.route||`${item.from} → ${item.to}`)}</b><small>${esc(item.truckType)} · ${item.capacity} t · ${esc(item.goods||item.acceptedGoods)}</small></span><span class="match-score">92% match</span><button class="button primary" data-toast="Opportunity opened for discussion">Open</button></article>`).join('')||'<div class="empty-inline"><b>No compatible route today</b><small>Change the truck location, availability date or destination preference.</small></div>'}</div>`;
}

export function opportunityDetailScreen(state) {
  const op=state.opportunities.find(x=>x.id===state.selectedOpportunityId)||state.opportunities[0];
  return `${head(op.title,op.summary,`<button class="button secondary" data-route="opportunityChat">Open conversation</button>`)}<div class="grid two"><section class="panel"><div class="review-checklist"><span class="done">✓ Parties matched and authorized</span><span class="done">✓ Goods/truck compatibility checked</span><span>○ Agree route, advance, responsibility and settlement</span><span>○ Create one canonical Load</span></div><div class="info-banner"><b>Opportunity, not yet a Load</b><span>Discussion history is retained when this converts. Repeated confirmation cannot create a duplicate Load.</span></div><button class="button primary full" data-action="convert-opportunity" data-opportunity="${op.id}">${op.canonicalLoadId?`Load ${esc(op.canonicalLoadId)} already created`:'Confirm terms and create Load'}</button></section><aside class="panel"><h2>Responsibility</h2><dl class="fact-list"><div><dt>Primary Transporter</dt><dd>Raj Logistics</dd></div><div><dt>Operating party</dt><dd>${op.type==='truck_match'?'Raj Transport':'Raj Logistics'}</dd></div><div><dt>Goods authorization</dt><dd>Recorded</dd></div><div><dt>Settlement</dt><dd>Separate party ledger</dd></div></dl></aside></div>`;
}

export function opportunityChatScreen(state) {
  const op=state.opportunities.find(x=>x.id===state.selectedOpportunityId)||state.opportunities[0];
  const messages=state.opportunityMessages[op.id]||[];
  return `${head('Opportunity conversation',`${op.id} · ${op.title}`)}<div class="grid two"><section class="panel chat-panel"><div class="chat-list">${messages.map(m=>`<div class="chat-message ${m.kind==='summary'?'summary':''}"><b>${esc(m.sender)}</b><p>${esc(m.text)}</p><small>${esc(m.kind==='voice'?'Voice note · transcript shown':m.kind==='summary'?'AI voice-note summary':m.at)}</small></div>`).join('')}</div><form id="opportunity-message-form" class="chat-compose"><input name="message" placeholder="Type a message" value="Pickup can start at 8 AM."><button type="button" class="button secondary" data-action="add-voice-message">🎙 Voice</button><button class="button primary" type="submit">Send</button></form></section><aside class="panel"><h2>Privacy and history</h2><p>Only matched businesses can enter this conversation. Phone numbers remain masked until permitted.</p><p>Messages, voice transcripts and summaries stay attached if the opportunity becomes a Load.</p><button class="button primary full" data-route="opportunityDetail">Review and confirm</button></aside></div>`;
}

