import {buildMilestones, DOC_TYPES} from './ops-rules.js';

const done = (ms, keys, extra = {}) => ms.map(m => keys.includes(m.key) ? {...m, status: 'done', at: extra[m.key]?.at || '27 Sep 2026, 7:10 AM', proof: extra[m.key]?.proof || null, by: extra[m.key]?.by || 'System'} : m);
const docs = (status, expiry = '2027-03-31') => DOC_TYPES.map(type => ({type, status, file: status === 'missing' ? '' : `${type.toLowerCase()}-scan.pdf`, expiry, uploadedBy: status === 'missing' ? '' : 'Suresh Paswan · Document Staff'}));

export const PARTY_NAMES = {moveai: 'MoveAI Pay', 
  personal: 'Shubham Kumar', goods: 'Sharma Foods', transporter: 'Raj Logistics', vehicle: 'Raj Transport', movers: 'SafeMove Packers',
  commercialDriver: 'Mohan Yadav', personalDriver: 'Anil Kumar', helper: 'Ramesh Yadav', platform: 'MoveAI platform', admin: 'Platform Admin',
  'external:metro': 'Metro Retail', 'external:bihar-agro': 'Bihar Agro Mills', 'external:ritika': 'Ritika Jain', 'staff:STAFF-002': 'Sunita Verma', 'staff:STAFF-001': 'Ravi Kumar',
};

export const OPS_SEED = {
  tripSeq: 505,
  trips: [
    {
      id: 'TRP-501', title: 'Rice bags · Patna → Delhi', goodsOrderId: 'GO-401', requirementId: 'TR-401', goods: 'Rice bags', quantity: 12, unit: 'tonnes',
      from: 'Patna Warehouse, Bihar', to: 'Okhla, Delhi', branchId: 'BR-002', service: 'transport', goodsRole: 'seller', receiver: 'Metro Retail',
      arrangement: 'selected_transporters', parties: ['goods', 'transporter', 'vehicle'], owner: 'transporter',
      vehicleSource: 'external_owner', vehicleId: 'VEH-202', vehicleOwner: 'vehicle', registration: 'BR01 GX 5522',
      crew: [{id: 'WORKER-001', name: 'Mohan Yadav', role: 'driver', persona: 'commercialDriver', classification: 'staff', accepted: true}, {id: 'WORKER-002', name: 'Ramesh Yadav', role: 'helper', persona: 'helper', classification: 'staff', accepted: true}],
      window: {from: '2026-09-27T05:00', to: '2026-09-29T20:00'}, dharamkata: true,
      terms: {freight: 62000, truckOwnerPayout: 54000, advance: 12000, driverWage: 3500, khalasiWage: 1800, paymentTerms: '₹12,000 advance; balance after POD'},
      milestones: done(buildMilestones(true), ['terms_confirmed', 'vehicle_assigned', 'crew_accepted', 'pickup_reached', 'loaded'], {loaded: {proof: 'loading-photo-0712.jpg', by: 'Ramesh Yadav'}}),
      status: 'loaded', gps: {consent: true, status: 'paused', points: [{place: 'Patna Warehouse', at: '27 Sep, 6:40 AM'}, {place: 'Patna bypass', at: '27 Sep, 7:25 AM'}], lastSeen: '7:25 AM'},
      conversationId: 'CNV-501', exceptions: [], settlementCreated: false, receipt: null,
    },
    {
      id: 'TRP-502', title: 'Wheat inbound · Ara → Bihta Plant', goodsOrderId: 'GO-403', goods: 'Wheat', quantity: 18, unit: 'tonnes',
      from: 'Bihar Agro Mills, Ara', to: 'Bihta Plant, Patna', branchId: 'BR-011', service: 'transport', goodsRole: 'buyer', receiver: 'Sharma Foods · Bihta Plant',
      arrangement: 'own_vehicle', parties: ['goods'], owner: 'goods', vehicleSource: 'own_fleet', vehicleId: 'VEH-G01', vehicleOwner: 'goods', registration: 'BR01 GH 9088',
      crew: [{id: 'CAND-001', name: 'Amit Singh', role: 'driver', persona: null, classification: 'marketplace', accepted: true}],
      window: {from: '2026-09-26T06:00', to: '2026-09-27T12:00'}, dharamkata: false,
      terms: {freight: 0, driverWage: 3200, paymentTerms: 'Own vehicle · driver per trip'},
      milestones: done(buildMilestones(false), ['terms_confirmed', 'vehicle_assigned', 'crew_accepted', 'pickup_reached', 'loaded', 'in_transit', 'delivered'], {loaded: {proof: 'wheat-loading.jpg'}, delivered: {proof: 'pod-bihta-0927.pdf', by: 'Amit Singh'}}),
      status: 'delivered', gps: {consent: true, status: 'stopped', points: [{place: 'Ara', at: '26 Sep, 7:00 AM'}, {place: 'Bihta Plant', at: '27 Sep, 9:40 AM'}], lastSeen: '9:40 AM'},
      conversationId: 'CNV-502', exceptions: [], settlementCreated: false, receipt: null,
    },
    {
      id: 'TRP-503', title: 'FMCG cartons · Jaipur → Delhi NCR', goods: 'FMCG cartons', quantity: 10, unit: 'tonnes',
      from: 'Jaipur, Rajasthan', to: 'Delhi NCR', branchId: 'BR-002', service: 'transport', goodsRole: 'seller', receiver: 'Metro Retail',
      arrangement: 'eligible_network', parties: ['goods', 'transporter'], owner: 'transporter', vehicleSource: null, vehicleId: null, vehicleOwner: null, registration: null,
      crew: [], window: {from: '2026-10-01T06:00', to: '2026-10-02T18:00'}, dharamkata: false,
      terms: {freight: 38000, truckOwnerPayout: 32000, advance: 8000, driverWage: 3500, khalasiWage: 1600, paymentTerms: '₹8,000 advance; balance 7 days after POD'},
      milestones: done(buildMilestones(false), ['terms_confirmed']), status: 'terms_confirmed', gps: {consent: false, status: 'not_started', points: []},
      conversationId: 'CNV-503', exceptions: [], settlementCreated: false, receipt: null,
    },
    {
      id: 'TRP-504', title: 'Rice bags · Patna → Delhi (load 1)', goodsOrderId: 'GO-401', goods: 'Rice bags', quantity: 8, unit: 'tonnes',
      from: 'Patna Warehouse, Bihar', to: 'Okhla, Delhi', branchId: 'BR-001', service: 'transport', goodsRole: 'seller', receiver: 'Metro Retail',
      arrangement: 'selected_transporters', parties: ['goods', 'transporter'], owner: 'transporter', vehicleSource: 'own_fleet', vehicleId: 'VEH-T02', vehicleOwner: 'transporter', registration: 'UP16 RT 3302',
      crew: [{id: 'CAND-002', name: 'Iqbal Khan', role: 'driver', persona: null, classification: 'marketplace', accepted: true}],
      window: {from: '2026-09-24T05:00', to: '2026-09-26T12:00'}, dharamkata: false,
      terms: {freight: 41000, advance: 8000, driverWage: 3400, paymentTerms: '₹8,000 advance; balance after POD'},
      milestones: buildMilestones(false).map(m => ({...m, status: 'done', at: '26 Sep 2026', by: 'System'})), status: 'closed',
      gps: {consent: true, status: 'stopped', points: [{place: 'Okhla, Delhi', at: '26 Sep, 11:10 AM'}]}, conversationId: 'CNV-501', exceptions: [], settlementCreated: true, receipt: {quantity: 8, condition: 'Good', note: 'All bags sealed'},
    },
  ],
  goodsOrderExtras: [{id: 'GO-403', workspace: 'goods', type: 'buy', counterparty: 'Bihar Agro Mills', goods: 'Wheat', quantity: 18, unit: 'tonnes', goodsPrice: 432000, transportResponsibility: 'buyer', status: 'in_delivery', createdAt: '25 Sep 2026, 11:00 AM'}],
  extraVehicles: {
    transporter: [{id: 'VEH-T02', registration: 'UP16 RT 3302', truckType: '19-ft closed', capacity: 9, status: 'idle', documents: 'approved', documentExpiry: '2027-05-30', branchId: 'BR-001', crew: 'Driver needed'}],
    movers: [{id: 'VEH-M01', registration: 'DL01 MV 1101', truckType: '14-ft closed', capacity: 4, status: 'idle', documents: 'approved', documentExpiry: '2027-06-30', branchId: 'BR-030', crew: 'Packers ready'}],
  },
  vehicleDocs: {
    'VEH-201': docs('approved'), 'VEH-202': docs('approved', '2027-01-31'), 'VEH-203': docs('approved', '2026-09-20').map(d => d.type === 'Fitness' || d.type === 'Pollution' ? {...d, status: 'expired'} : d),
    'VEH-G01': docs('approved', '2027-04-30'), 'VEH-T01': docs('approved', '2027-02-15'), 'VEH-T02': docs('approved', '2027-05-30'), 'VEH-M01': docs('approved', '2027-06-30'),
  },
  bookings: [
    {id: 'BK-1', resourceId: 'VEH-202', ref: 'TRP-501', label: 'TRP-501 Patna → Delhi', service: 'transport', from: '2026-09-27T05:00', to: '2026-09-29T20:00', owner: 'vehicle'},
    {id: 'BK-2', resourceId: 'WORKER-001', ref: 'TRP-501', label: 'TRP-501 Patna → Delhi', service: 'transport', from: '2026-09-27T05:00', to: '2026-09-29T20:00', owner: 'transporter'},
    {id: 'BK-3', resourceId: 'WORKER-002', ref: 'TRP-501', label: 'TRP-501 Patna → Delhi', service: 'transport', from: '2026-09-27T05:00', to: '2026-09-29T20:00', owner: 'transporter'},
    {id: 'BK-4', resourceId: 'VEH-T01', ref: 'MOV-603', label: 'MOV-603 Office move, Noida', service: 'movers', from: '2026-10-02T08:00', to: '2026-10-02T19:00', owner: 'transporter'},
    {id: 'BK-5', resourceId: 'VEH-G01', ref: 'TRP-502', label: 'TRP-502 Wheat inbound', service: 'transport', from: '2026-09-26T06:00', to: '2026-09-27T12:00', owner: 'goods'},
  ],
  vehicleOffers: [],
  partnerships: [{id: 'PRT-1', vehicleOwner: 'vehicle', vehicleId: 'VEH-201', registration: 'BR01 GX 4421', mover: 'movers', status: 'requested', requestedAt: '26 Sep 2026'}],
  platformWorkers: [
    {id: 'PW-MOHAN', name: 'Mohan Yadav', persona: 'commercialDriver', capabilities: ['driver'], licences: ['Heavy vehicle (HMV) · commercial'], locations: ['Jaipur', 'Patna'], status: 'available', rating: 4.8, expectedPay: 3500, verified: true, classification: 'marketplace'},
    {id: 'PW-RAMESH', name: 'Ramesh Yadav', persona: 'helper', capabilities: ['helper'], skills: ['Truck Khalasi', 'Loading / unloading', 'Moving helper / packer'], licences: [], locations: ['Noida', 'Patna'], status: 'available', rating: 4.6, expectedPay: 1600, verified: true, classification: 'marketplace'},
    {id: 'PW-ANIL', name: 'Anil Kumar', persona: 'personalDriver', capabilities: ['driver'], licences: ['Personal car (LMV-NT)'], locations: ['Noida', 'Delhi'], status: 'available', rating: 4.9, expectedPay: 1200, verified: true, classification: 'marketplace'},
    {id: 'PW-SURAJ', name: 'Suraj Mandal', persona: null, capabilities: ['helper'], skills: ['Warehouse / assembly', 'Loading / unloading'], licences: [], locations: ['Jaipur', 'Noida'], status: 'available', rating: 4.4, expectedPay: 1400, verified: true, classification: 'marketplace'},
  ],
  workOffers: [
    {id: 'OFF-801', to: 'commercialDriver', kind: 'trip', from: 'transporter', fromName: 'Raj Logistics', ref: 'TRP-503', title: 'One-trip Driver · Jaipur → Delhi NCR', vehicle: 'Assigned at acceptance · 22-ft closed', pay: 3500, advance: 1000, platformFee: 150, feePaidBy: 'Raj Logistics', date: '01 Oct 2026', status: 'pending'},
    {id: 'OFF-802', to: 'commercialDriver', kind: 'invite', from: 'vehicle', fromName: 'Raj Transport', ref: null, title: 'Permanent Driver · Patna Yard', vehicle: '14-wheel open trucks', pay: 26000, payType: 'monthly', advance: 0, platformFee: 0, date: '05 Oct 2026', status: 'pending'},
    {id: 'OFF-803', to: 'helper', kind: 'job', from: 'movers', fromName: 'SafeMove Packers', ref: 'MOV-601', title: 'Packer / Moving Helper · 2 BHK Noida → Gurugram', vehicle: '14-ft closed truck', pay: 1500, advance: 300, platformFee: 60, feePaidBy: 'SafeMove Packers', date: '03 Oct 2026', status: 'pending'},
    {id: 'OFF-804', to: 'helper', kind: 'fixed_days', from: 'goods', fromName: 'Sharma Foods', ref: null, title: 'Warehouse loading · 5 fixed days', vehicle: 'Patna Warehouse', pay: 1300, payType: 'daily', advance: 0, platformFee: 0, date: '06 Oct 2026', status: 'pending'},
  ],
  serviceRequests: [
    {id: 'SR-701', customer: 'personal', type: 'moving', title: '2 BHK move · Sector 62 Noida → DLF Phase 3 Gurugram', movingJobId: 'MOV-601', date: '2026-10-03', quote: {total: 13919}, status: 'confirmed', paid: false, rating: null, conversationId: 'CNV-601', createdAt: '26 Sep 2026'},
    {id: 'SR-702', customer: 'personal', type: 'driver', title: 'Personal Driver · Daily · Hyundai Creta automatic', hireType: 'daily', duration: 1, carType: 'SUV automatic', location: 'Sector 62, Noida', date: '2026-09-28', provider: 'personalDriver', providerName: 'Anil Kumar', quote: {total: 1369, driverEarning: 1320}, status: 'accepted', paid: false, rating: null, conversationId: 'CNV-702', createdAt: '27 Sep 2026'},
    {id: 'SR-703', customer: 'personal', type: 'general', title: 'Carpenter · wardrobe hinge repair', category: 'carpenter', date: '2026-09-28', provider: 'partner', providerName: 'Verified service partner', quote: {total: 679}, status: 'provider_done', paid: false, rating: null, conversationId: null, createdAt: '25 Sep 2026'},
    {id: 'SR-704', customer: 'external:kavita', customerName: 'Kavita Rao', type: 'driver', title: 'Personal Driver · 4 hours · airport drop', hireType: 'hourly', duration: 4, carType: 'Hatchback manual', location: 'Sector 50, Noida', date: '2026-09-29', provider: null, providerName: null, quote: {total: 769, driverEarning: 720}, status: 'searching', paid: false, rating: null, conversationId: null, createdAt: '27 Sep 2026'},
  ],
  movingBranches: [
    {id: 'BR-030', workspace: 'movers', name: 'SafeMove · Noida Moving Branch', coverage: ['Noida', 'Delhi', 'Ghaziabad'], openJobs: 2},
    {id: 'BR-031', workspace: 'movers', name: 'SafeMove · Gurugram Branch', coverage: ['Gurugram', 'Manesar'], openJobs: 1},
    {id: 'BR-001', workspace: 'transporter', name: 'Raj Logistics · Noida HQ (Movers)', coverage: ['Noida'], openJobs: 4},
  ],
  movingJobs: [
    {id: 'MOV-601', owner: 'movers', branchId: 'BR-030', customer: 'personal', customerName: 'Shubham Kumar', serviceRequestId: 'SR-701', from: 'Sector 62, Noida', to: 'DLF Phase 3, Gurugram', date: '2026-10-03', size: '2 BHK', pkg: 'standard', vehicleNeed: '14-ft closed truck',
      price: [['Standard package · 2 BHK', 11340], ['Distance beyond 20 km', 456], ['GST 18%', 2123]], total: 13919, customerOtp: '4826', status: 'auto_assigned', vehicle: null, vehicleSource: null, crew: [],
      inventory: [{item: 'Double bed + mattress', packed: false}, {item: 'Wardrobe (2 door)', packed: false}, {item: 'Kitchen cartons × 8', packed: false}, {item: 'LED TV 55"', packed: false}, {item: 'Sofa set (3+1)', packed: false}],
      loadingProof: null, gps: {consent: false, status: 'not_started', points: []}, parties: ['personal', 'movers'], conversationId: 'CNV-601', window: {from: '2026-10-03T08:00', to: '2026-10-03T18:00'}, payoutsCreated: false, history: [{status: 'auto_assigned', at: '26 Sep 2026, 6:10 PM', by: 'Platform'}]},
    {id: 'MOV-602', owner: 'movers', branchId: 'BR-031', customer: 'external:ritika', customerName: 'Ritika Jain', serviceRequestId: null, from: 'Sector 45, Gurugram', to: 'Sohna Road, Gurugram', date: '2026-09-30', size: '1 BHK', pkg: 'basic', vehicleNeed: '8-ft mini truck',
      price: [['Basic package · 1 BHK', 5200], ['GST 18%', 936]], total: 6136, customerOtp: '1937', status: 'auto_assigned', vehicle: null, vehicleSource: null, crew: [],
      inventory: [{item: 'Single bed', packed: false}, {item: 'Study table', packed: false}, {item: 'Cartons × 6', packed: false}], loadingProof: null, gps: {consent: false, status: 'not_started', points: []}, parties: ['movers'], conversationId: null, window: {from: '2026-09-30T09:00', to: '2026-09-30T15:00'}, payoutsCreated: false, history: [{status: 'auto_assigned', at: '27 Sep 2026, 9:02 AM', by: 'Platform'}]},
    {id: 'MOV-603', owner: 'transporter', branchId: 'BR-001', customer: 'external:office', customerName: 'Kite Studio (office)', serviceRequestId: null, from: 'Sector 63, Noida', to: 'Sector 132, Noida', date: '2026-10-02', size: 'Office', pkg: 'premium', vehicleNeed: '19-ft closed truck',
      price: [['Premium package · Office', 25500], ['GST 18%', 4590]], total: 30090, customerOtp: '5541', status: 'resources_allocated', vehicle: {id: 'VEH-T01', registration: 'UP16 RT 2201', source: 'owned', owner: 'transporter'}, vehicleSource: 'owned',
      crew: [{id: 'WORKER-002', name: 'Ramesh Yadav', role: 'helper', persona: 'helper', classification: 'staff'}], inventory: [{item: 'Workstations × 12', packed: false}, {item: 'Server rack', packed: false}], loadingProof: null, gps: {consent: false, status: 'not_started', points: []}, parties: ['transporter'], conversationId: null, window: {from: '2026-10-02T08:00', to: '2026-10-02T19:00'}, payoutsCreated: false, history: []},
  ],
  ledger: [
    {id: 'PAY-9001', owner: 'transporter', sourceType: 'trip', sourceId: 'TRP-501', type: 'freight', direction: 'receivable', payer: 'goods', payee: 'transporter', responsible: 'goods', amount: 12000, method: 'bank', reference: 'UTR 5528190041', proof: 'utr-5528190041.png', channel: 'outside', status: 'confirmed', history: [{action: 'created', status: 'approved', actor: 'Vijay Sharma', at: '27 Sep 2026, 6:00 AM'}, {action: 'pay', status: 'paid', actor: 'Vijay Sharma', at: '27 Sep 2026, 6:05 AM'}, {action: 'confirm', status: 'confirmed', actor: 'Amit Raj', at: '27 Sep 2026, 6:30 AM'}], note: 'Freight advance'},
    {id: 'PAY-9002', owner: 'transporter', sourceType: 'trip', sourceId: 'TRP-501', type: 'advance', direction: 'payable', payer: 'transporter', payee: 'vehicle', responsible: 'transporter', amount: 10000, method: 'upi', reference: 'UPI 3301-TRP501', proof: '', channel: 'outside', status: 'paid', history: [{action: 'pay', status: 'paid', actor: 'Sunita Verma', at: '27 Sep 2026, 6:40 AM'}], note: 'Truck Owner advance'},
    {id: 'PAY-9003', owner: 'transporter', sourceType: 'trip', sourceId: 'TRP-501', type: 'advance', direction: 'payable', payer: 'transporter', payee: 'commercialDriver', responsible: 'transporter', amount: 1000, method: 'cash', reference: 'Cash slip 118', proof: 'cash-118.jpg', channel: 'outside', status: 'confirmed', history: [], note: 'Driver trip advance'},
    {id: 'PAY-9004', owner: 'transporter', sourceType: 'trip', sourceId: 'TRP-501', type: 'reimbursement', direction: 'payable', payer: 'transporter', payee: 'commercialDriver', responsible: 'transporter', amount: 640, method: 'upi', reference: 'Toll receipts 3', proof: 'toll-3.jpg', channel: 'outside', status: 'pending_approval', history: [], note: 'Toll reimbursement'},
    {id: 'PAY-9005', owner: 'transporter', sourceType: 'salary', sourceId: 'STAFF-002', type: 'salary', direction: 'payable', payer: 'transporter', payee: 'staff:STAFF-002', responsible: 'transporter', amount: 35000, method: 'bank', reference: 'SEP-SAL-002', proof: '', channel: 'outside', status: 'approved', history: [], note: 'September salary'},
    {id: 'PAY-9006', owner: 'transporter', sourceType: 'hiring', sourceId: 'JOB-301', type: 'platform_fee', direction: 'payable', payer: 'transporter', payee: 'platform', responsible: 'transporter', amount: 150, method: 'platform', reference: 'Platform invoice PF-2231', proof: '', channel: 'platform', status: 'paid', forWorker: 'commercialDriver', history: [], note: 'Hiring fee for Mohan Yadav (paid by business)'},
    {id: 'PAY-9007', owner: 'vehicle', sourceType: 'trip', sourceId: 'TRP-501', type: 'advance', direction: 'payable', payer: 'vehicle', payee: 'helper', responsible: 'vehicle', amount: 500, method: 'cash', reference: 'Cash slip RT-22', proof: '', channel: 'outside', status: 'paid', history: [], note: 'Khalasi food advance'},
    {id: 'PAY-9008', owner: 'personal', sourceType: 'service', sourceId: 'SR-701', type: 'customer_payment', direction: 'payable', payer: 'personal', payee: 'movers', responsible: 'personal', amount: 2000, method: 'platform', reference: 'Booking token', proof: '', channel: 'platform', status: 'confirmed', history: [], note: 'Moving booking token'},
  ],
  conversations: [
    {id: 'CNV-501', kind: 'job', ref: 'TRP-501', title: 'TRP-501 · Rice bags Patna → Delhi', participants: ['goods', 'transporter', 'vehicle', 'commercialDriver', 'helper'], status: 'open', messages: [
      {id: 'M1', from: 'Amit Raj · Transporter', type: 'text', body: 'Truck BR01 GX 5522 reached Patna Warehouse. Loading started.', at: '6:42 AM'},
      {id: 'M2', from: 'Ramesh Yadav · Khalasi', type: 'proof', body: 'loading-photo-0712.jpg', at: '7:12 AM'},
      {id: 'M3', from: 'Mohan Yadav · Driver', type: 'audio', body: 'Voice note 0:14 — "Loading complete, going to Dharamkata now"', at: '7:18 AM'},
      {id: 'M4', from: 'Mohan Yadav · Driver', type: 'location', body: 'Patna bypass · 25.59, 85.14', at: '7:25 AM'},
    ]},
    {id: 'CNV-502', kind: 'job', ref: 'TRP-502', title: 'TRP-502 · Wheat inbound', participants: ['goods'], status: 'open', messages: [{id: 'M1', from: 'Amit Singh · Driver', type: 'proof', body: 'pod-bihta-0927.pdf', at: '9:40 AM'}]},
    {id: 'CNV-503', kind: 'job', ref: 'TRP-503', title: 'TRP-503 · FMCG Jaipur → Delhi', participants: ['goods', 'transporter'], status: 'open', messages: [{id: 'M1', from: 'Vijay Sharma · Goods Owner', type: 'text', body: 'Terms confirmed. Please share vehicle details 24 hours before pickup.', at: 'Yesterday'}]},
    {id: 'CNV-601', kind: 'job', ref: 'MOV-601', title: 'MOV-601 · 2 BHK Noida → Gurugram', participants: ['personal', 'movers'], status: 'open', messages: [{id: 'M1', from: 'SafeMove Packers', type: 'text', body: 'Your request is assigned to our Noida branch. We will confirm the slot shortly.', at: 'Yesterday'}]},
    {id: 'CNV-702', kind: 'job', ref: 'SR-702', title: 'SR-702 · Personal Driver booking', participants: ['personal', 'personalDriver'], status: 'open', messages: [{id: 'M1', from: 'Anil Kumar · Personal Driver', type: 'text', body: 'I will reach Sector 62 at 8:45 AM tomorrow.', at: '10:05 AM'}]},
    {id: 'CNV-INT-T', kind: 'internal', owner: 'transporter', ref: null, branchIds: ['BR-001', 'BR-002'], title: 'Raj Logistics · Operations team', participants: ['transporter'], status: 'open', messages: [{id: 'M1', from: 'Ravi Kumar · Manager', type: 'text', body: 'Jaipur needs one 22-ft truck for 1 Oct. Do not use UP16 RT 2201 — booked for the Noida office move on 2 Oct.', at: '8:10 AM'}]},
    {id: 'CNV-INT-M', kind: 'internal', owner: 'movers', ref: null, branchIds: ['BR-030', 'BR-031'], title: 'SafeMove · Branch team', participants: ['movers'], status: 'open', messages: [{id: 'M1', from: 'Neha Singh · Mover Owner', type: 'text', body: 'Two new auto-assigned requests. Confirm slots before noon.', at: '9:05 AM'}]},
    {id: 'CNV-DIR-1', kind: 'direct', ref: null, title: 'Raj Logistics ↔ Raj Transport', participants: ['transporter', 'vehicle'], status: 'open', createdBy: 'transporter', messages: [{id: 'M1', from: 'Amit Raj · Transporter', type: 'text', body: 'Can BR01 GX 4421 take a Jaipur → Delhi load on 1 Oct?', at: 'Yesterday'}]},
  ],
  notifications: [
    {id: 'N1', to: 'transporter', text: 'Dharamkata is the next mandatory milestone on TRP-501.', ref: 'TRP-501', at: '7:20 AM', read: false},
    {id: 'N2', to: 'goods', text: 'TRP-502 delivered with POD. Confirm quantity and condition.', ref: 'TRP-502', at: '9:41 AM', read: false},
    {id: 'N3', to: 'movers', text: 'New auto-assigned request MOV-601 for Noida branch.', ref: 'MOV-601', at: 'Yesterday', read: false},
    {id: 'N4', to: 'vehicle', text: 'BR01 GX 6633 Fitness and Pollution certificates expired on 20 Sep.', ref: 'VEH-203', at: 'Yesterday', read: false},
    {id: 'N5', to: 'commercialDriver', text: 'Raj Logistics sent a one-trip offer for 1 Oct.', ref: 'OFF-801', at: '8:00 AM', read: false},
    {id: 'N6', to: 'personal', text: 'Carpenter marked SR-703 complete. Confirm and pay.', ref: 'SR-703', at: '10:30 AM', read: false},
  ],
  verificationQueue: [
    {id: 'VER-1', kind: 'person', subject: 'Mohan Yadav', ownerWorkspace: 'commercialDriver', capability: 'Commercial Driver (HMV)', documents: ['Commercial licence RJ14 20220012345 · v2', 'Aadhaar (masked)', 'Photo'], version: 2, status: 'pending', history: [{decision: 'correction', reason: 'Licence photo blurred', at: '24 Sep 2026', by: 'Admin Neha'}], submittedAt: '26 Sep 2026'},
    {id: 'VER-2', kind: 'vehicle', subject: 'BR01 GX 6633', ownerWorkspace: 'vehicle', vehicleId: 'VEH-203', capability: 'Commercial vehicle documents', documents: ['RC', 'Insurance', 'Permit', 'Fitness (renewal)', 'Pollution (renewal)'], version: 3, status: 'pending', history: [], submittedAt: '27 Sep 2026'},
    {id: 'VER-3', kind: 'person', subject: 'Anil Kumar', ownerWorkspace: 'personalDriver', capability: 'Personal Driver (LMV)', documents: ['LMV licence DL09 2019004431', 'PAN (masked)'], version: 1, status: 'approved', history: [{decision: 'approve', reason: 'Licence verified', at: '20 Sep 2026', by: 'Admin Neha'}], submittedAt: '19 Sep 2026'},
    {id: 'VER-4', kind: 'business', subject: 'FastRoad Transport', ownerWorkspace: 'external', capability: 'Transport business', documents: ['GST certificate', 'PAN'], version: 1, status: 'suspended', history: [{decision: 'suspend', reason: 'Two unresolved freight disputes', at: '22 Sep 2026', by: 'Admin Neha'}], appeal: 'Disputes settled. Bank statements attached.', submittedAt: '15 Sep 2026'},
  ],
  cases: [{id: 'CASE-1', kind: 'payment', subject: 'PAY-9002 duplicate claim', raisedBy: 'Raj Transport', status: 'open', severity: 'medium', at: '27 Sep 2026', notes: 'Truck Owner says advance was received twice.'}],
  exceptions: [{id: 'EXC-1', type: 'document_expired', ref: 'VEH-203', refKind: 'vehicle', reason: 'Fitness and Pollution certificates expired on 20 Sep 2026.', location: 'Patna Yard', proof: 'system check', responsible: 'vehicle', reportedBy: 'System', parties: ['vehicle'], status: 'open', action: 'Hold vehicle until renewal', at: '21 Sep 2026', history: [{event: 'Reported by system', at: '21 Sep 2026'}]}],
  staffEvents: [],
  formerStaff: {transporter: [{id: 'STAFF-OLD-1', name: 'Deepak Rao', designation: 'Dispatcher', offboardedAt: '12 Jul 2026', finalSettlement: 'Paid ₹18,400', history: 'Employment 2024-03-01 to 2026-07-12'}]},
  nextLoadPool: [
    {id: 'NL-901', route: 'Okhla, Delhi → Jaipur', pickup: 'Okhla, Delhi', drop: 'Jaipur', goods: 'Packaged snacks', capacity: 10, date: '2026-09-30'},
    {id: 'NL-902', route: 'Delhi NCR → Lucknow', pickup: 'Delhi NCR', drop: 'Lucknow', goods: 'Tiles', capacity: 14, date: '2026-10-03'},
  ],
  bookingDraft: null,
  aiLog: [],
};
