import {ROLE_TEMPLATES,OWNER_ONLY,candidateMatches,canOffboard} from './people-rules.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const head=(title,description,action='')=>`<div class="page-header"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;
const people=state=>state.peopleByWorkspace[state.currentWorkspace]||[];
const branches=state=>state.businessProfiles[state.currentWorkspace]?.branches||[];
const staff=state=>people(state).find(x=>x.id===state.selectedStaffId)||people(state)[0];
const opening=state=>state.vacancies.find(x=>x.id===state.selectedOpeningId)||state.vacancies[0];
const candidate=state=>state.candidates.find(x=>x.id===state.selectedCandidateId)||state.candidates[0];
const status=s=>`<span class="status-pill ${['pending','invited','offboarding'].includes(s)?'warning':''}">${esc(s.replaceAll('_',' '))}</span>`;
const branchName=(state,id)=>branches(state).find(x=>x.id===id)?.name||id;

export function peopleScreen(state){const list=people(state),pending=state.staffInvitations.filter(x=>x.workspace===state.currentWorkspace&&x.status==='pending');return `${head('People','Team, hiring and temporary owner delegation in one place.',`<button class="button primary" data-route="addStaff">+ Add staff</button>`)}<div class="people-tabs"><button class="active">Team</button><button data-route="hiring">Hiring</button><button data-route="roles">Roles</button><button data-route="ownerCover">Owner Cover</button></div><div class="metrics"><div class="metric"><span>Active staff</span><b>${list.filter(x=>x.status==='active').length}</b><small>Role-specific access</small></div><div class="metric"><span>Invitations</span><b>${pending.length}</b><small>Waiting to join</small></div><div class="metric"><span>Documents</span><b>${list.filter(x=>x.documentsStatus!=='verified').length}</b><small>Staff action needed</small></div><div class="metric"><span>Open roles</span><b>${state.vacancies.filter(x=>x.workspace===state.currentWorkspace&&x.status==='open').length}</b><small>Hiring</small></div></div><section class="panel"><div class="panel-header"><div><h2>Team members</h2><p>Owners see status. Staff upload their own identity, bank and emergency details.</p></div></div><div class="people-list">${list.map(x=>personRow(state,x)).join('')}${pending.map(x=>`<button class="person-row" data-action="accept-staff-invite" data-invite="${x.id}"><span class="avatar">${esc(x.name.split(' ').map(n=>n[0]).join('').slice(0,2))}</span><span><b>${esc(x.name)}</b><small>${ROLE_TEMPLATES[x.role].label} · ${branchName(state,x.branchId)} · Open invite demo</small></span>${status('invited')}<i>›</i></button>`).join('')}</div></section><div class="shortcut-grid people-shortcuts"><button class="shortcut" data-route="hiring"><span class="shortcut-icon">⌕</span><b>Hiring</b><small>Openings and applicants</small></button><button class="shortcut" data-route="roles"><span class="shortcut-icon">♟</span><b>Roles</b><small>Simple permissions</small></button><button class="shortcut" data-route="ownerCover"><span class="shortcut-icon">☂</span><b>Owner Cover</b><small>Temporary delegation</small></button><button class="shortcut" data-route="findWorkers"><span class="shortcut-icon">⌕</span><b>Find workers</b><small>Drivers, Helpers and staff</small></button></div>`}

function personRow(state,x){return `<button class="person-row" data-action="open-staff" data-staff="${x.id}"><span class="avatar">${esc(x.name.split(' ').map(n=>n[0]).join('').slice(0,2))}</span><span><b>${esc(x.name)}</b><small>${esc(x.designation)} · ${x.branchIds.map(id=>branchName(state,id)).join(', ')}</small></span>${status(x.status)}<i>›</i></button>`}

export function addStaffScreen(state){return `${head('Add staff','Invite by verified mobile. The staff member completes personal documents.')}<form id="staff-invite-form" class="panel form-panel narrow"><div class="form-grid two"><label><span>Name</span><input name="name" value="Pankaj Meena"></label><label><span>Mobile number</span><input name="mobile" inputmode="numeric" maxlength="10" value="9876501199"></label><label><span>Designation</span><select name="role">${Object.entries(ROLE_TEMPLATES).map(([id,r])=>`<option value="${id}">${r.label}</option>`).join('')}</select></label><label><span>Branch</span><select name="branchId">${branches(state).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></label><label><span>Employment</span><select name="employmentType"><option value="permanent">Permanent</option><option value="fixed_term">Fixed-term</option><option value="trip_only">Trip / job only</option></select></label><label><span>Pay type</span><select name="payType"><option value="monthly">Monthly</option><option value="daily">Daily</option><option value="per_job">Per trip / job</option></select></label><fieldset class="wide"><legend>Responsibilities</legend><div class="check-grid"><label><input type="checkbox" name="responsibilities" value="Trip updates" checked> Trip updates</label><label><input type="checkbox" name="responsibilities" value="Vehicle allocation"> Vehicle allocation</label><label><input type="checkbox" name="responsibilities" value="Documents"> Documents</label><label><input type="checkbox" name="responsibilities" value="Payment preparation"> Payment preparation</label></div></fieldset></div><div class="info-banner"><b>The owner does not upload staff documents</b><span>After accepting, the staff member adds ID, emergency contact and bank/UPI information. The owner only reviews completion and access.</span></div><p id="staff-invite-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-route="people">Cancel</button><button class="button primary" type="submit">Send invitation</button></div></form>`}

export function staffDetailScreen(state){const x=staff(state);if(!x)return empty('Staff member not found');const template=ROLE_TEMPLATES[x.role];return `${head(x.name,`${x.id} · ${x.designation}`,`<button class="button secondary" data-route="people">Back to People</button>`)}<div class="grid two"><section class="panel"><div class="profile-summary"><span class="avatar large">${esc(x.name.split(' ').map(n=>n[0]).join('').slice(0,2))}</span><span><h2>${esc(x.name)}</h2><p>${esc(template.label)} · ${x.branchIds.map(id=>branchName(state,id)).join(', ')}</p></span>${status(x.status)}</div><div class="staff-facts"><div><span>Mobile</span><b>+91 ••••••${x.mobile.slice(-4)}</b></div><div><span>Pay</span><b>${esc(x.payType)} · ₹${Number(x.payAmount).toLocaleString('en-IN')}</b></div><div><span>Documents</span><b>${esc(x.documentsStatus.replaceAll('_',' '))}</b></div><div><span>Bank</span><b>${esc(x.bankStatus.replaceAll('_',' '))}</b></div><div><span>Assignments</span><b>${x.activeAssignments.length}</b></div><div><span>Amount due</span><b>₹${Number(x.dues).toLocaleString('en-IN')}</b></div></div><div class="screen-actions"><button class="button primary" data-route="staffAccess">Access and role</button><button class="button secondary" data-action="preview-staff-onboarding">Open staff self-service</button><button class="button danger" data-route="offboarding">Offboard</button></div></section><aside class="panel"><h2>What this role can see</h2><div class="permission-list">${template.permissions.map(p=>`<span>✓ ${esc(p.replaceAll('.',' · '))}</span>`).join('')}</div><div class="owner-only"><b>Always owner-only</b>${OWNER_ONLY.map(p=>`<span>× ${esc(p.replaceAll('.',' · '))}</span>`).join('')}</div></aside></div>`}

export function staffOnboardingScreen(state){const x=staff(state);return `${head('Complete your joining details',`${x?.name||'Invited staff'} · Only your own information is shown`)}<section class="panel form-panel narrow"><div class="onboarding-status"><div><span>1</span><b>Identity documents</b>${status(x.documentsStatus)}</div><div><span>2</span><b>Emergency contact</b>${status(x.emergencyStatus)}</div><div><span>3</span><b>Bank / UPI</b>${status(x.bankStatus)}</div></div><div class="document-list"><div class="document-row"><span class="document-icon">▣</span><span class="document-copy"><b>Aadhaar or voter ID</b><small>Visible only to permitted reviewers</small></span><button class="button secondary" data-action="complete-staff-step" data-step="documentsStatus">Use sample</button></div><div class="document-row"><span class="document-icon">☎</span><span class="document-copy"><b>Emergency contact</b><small>Name, relationship and mobile</small></span><button class="button secondary" data-action="complete-staff-step" data-step="emergencyStatus">Add sample</button></div><div class="document-row"><span class="document-icon">₹</span><span class="document-copy"><b>Bank or UPI</b><small>Used for salary and reimbursements</small></span><button class="button secondary" data-action="complete-staff-step" data-step="bankStatus">Add sample</button></div></div><div class="info-banner"><b>Owner view is limited</b><span>The owner sees Verified, Pending or Rejected. Full document numbers remain restricted.</span></div><button class="button primary full" data-action="finish-staff-onboarding">Submit for owner review</button></section>`}

export function rolesScreen(){return `${head('Roles and permissions','Choose a simple designation first. Adjust only when needed.')}<div class="role-grid">${Object.entries(ROLE_TEMPLATES).map(([id,r])=>`<article class="panel role-card"><span class="role-icon">${id==='driver'?'🚚':id==='helper'?'🧰':id==='accounts'?'₹':'♟'}</span><h2>${esc(r.label)}</h2><p>${esc(r.summary)}</p><div class="permission-list">${r.permissions.slice(0,4).map(p=>`<span>✓ ${esc(p.replaceAll('.',' · '))}</span>`).join('')}</div><button class="button secondary" data-toast="Role template selected">Use role</button></article>`).join('')}</div><section class="panel owner-rule-panel"><h2>Owner-only actions cannot be delegated</h2><p>Ownership transfer, owner bank changes, appointing another owner and closing the business remain blocked even for Managers and Owner Cover.</p></section>`}

export function staffAccessScreen(state){const x=staff(state),template=ROLE_TEMPLATES[x.role];return `${head('Staff access',`${x.name} · ${template.label}`)}<form id="staff-access-form" class="panel form-panel narrow"><fieldset><legend>Allowed branches</legend><div class="check-grid">${branches(state).map(b=>`<label><input type="checkbox" name="branchIds" value="${b.id}" ${x.branchIds.includes(b.id)?'checked':''}> ${esc(b.name)}</label>`).join('')}</div></fieldset><fieldset><legend>Allowed services</legend><div class="check-grid">${(state.businessProfiles[state.currentWorkspace]?.services||[]).map(s=>`<label><input type="checkbox" name="services" value="${s}" ${x.services.includes(s)?'checked':''}> ${esc(s)}</label>`).join('')}</div></fieldset><fieldset><legend>Role permissions</legend><div class="permission-list">${template.permissions.map(p=>`<label><input type="checkbox" name="permissions" value="${p}" checked> ${esc(p.replaceAll('.',' · '))}</label>`).join('')}</div></fieldset><div class="temporary-access"><label><input type="checkbox" name="temporary"> Temporary additional access</label><div class="form-grid two"><label><span>From</span><input type="date" name="from"></label><label><span>Until</span><input type="date" name="to"></label></div></div><div class="info-banner"><b>Server-enforced scope</b><span>Business, branch, service, job and action checks apply even if someone changes the URL.</span></div><div class="form-actions"><button type="button" class="button secondary" data-route="staffDetail">Cancel</button><button class="button primary" type="submit">Save access</button></div></form>`}

export function hiringScreen(state){const jobs=state.vacancies.filter(x=>x.workspace===state.currentWorkspace),apps=state.jobApplications.filter(a=>jobs.some(j=>j.id===a.openingId));return `${head('Hiring','Open roles, applicants and available workers.',`<button class="button primary" data-route="postOpening">+ Post opening</button>`)}<div class="people-tabs"><button class="active">Openings</button><button data-route="applications">Applicants (${apps.length})</button><button data-route="findWorkers">Find workers</button></div><section class="panel"><div class="job-list">${jobs.map(j=>jobRow(j)).join('')||'<div class="empty-inline"><b>No openings</b><small>Post the first branch role.</small></div>'}</div></section>`}

function jobRow(j){return `<button class="job-row" data-action="open-opening" data-opening="${j.id}"><span class="job-icon">${j.role==='driver'?'🚚':'♟'}</span><span><b>${esc(j.title)}</b><small>${esc(j.branch)} · ${esc(j.employmentType.replaceAll('_',' '))}</small></span><span><b>₹${Number(j.payMin).toLocaleString('en-IN')}–₹${Number(j.payMax).toLocaleString('en-IN')}</b><small>${esc(j.payType.replaceAll('_',' '))}</small></span>${status(j.status)}<i>›</i></button>`}

export function postOpeningScreen(state){return `${head('Post opening','Keep the job clear for nearby workers.')}<form id="opening-form" class="panel form-panel narrow"><div class="form-grid two"><label class="wide"><span>Job title</span><input name="title" value="Heavy Truck Driver"></label><label><span>Role</span><select name="role">${['driver','helper','operations','accounts','documents'].map(r=>`<option value="${r}">${ROLE_TEMPLATES[r].label}</option>`).join('')}</select></label><label><span>Branch</span><select name="branchId">${branches(state).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></label><label><span>Number needed</span><input name="count" type="number" min="1" value="2"></label><label><span>Employment</span><select name="employmentType"><option value="trip_only">Trip / job only</option><option value="permanent">Permanent</option><option value="fixed_term">Fixed-term</option></select></label><label><span>Minimum pay</span><input name="payMin" type="number" value="3000"></label><label><span>Maximum pay</span><input name="payMax" type="number" value="4500"></label><label><span>Start date</span><input name="startDate" type="date" value="2026-09-30"></label><label><span>End date (fixed-term)</span><input name="endDate" type="date"></label><label><span>Approval</span><select name="approvalPolicy"><option>Manager can hire</option><option>Owner approval</option></select></label><label class="wide"><span>Requirements</span><textarea name="requirements">Heavy licence, 2+ years experience</textarea></label></div><p id="opening-error" class="field-error" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-route="hiring">Cancel</button><button class="button primary" type="submit">Publish opening</button></div></form>`}

export function findWorkersScreen(state){const job=opening(state),matches=state.candidates.filter(c=>candidateMatches(c,job));return `${head('Find workers',`${job.title} · ${job.location}`)}<div class="filter-bar"><span>${matches.length} matching workers</span><button class="button secondary" data-toast="Filters opened">Skills · Location · Verification · Availability</button></div><div class="candidate-grid">${matches.map(c=>candidateCard(c,job)).join('')||'<div class="empty-inline"><b>No exact matches</b><small>Expand location or expected pay.</small></div>'}</div>`}

function candidateCard(c,j){return `<article class="panel candidate-card"><div class="profile-summary"><span class="avatar">${esc(c.name.split(' ').map(n=>n[0]).join(''))}</span><span><h2>${esc(c.name)}</h2><p>${c.verified?'✓ Verified':'Verification pending'}</p></span></div><div class="service-tags">${c.capabilities.map(x=>`<span>${ROLE_TEMPLATES[x]?.label||x}</span>`).join('')}</div><dl><div><dt>Location</dt><dd>${esc(c.locations.join(', '))}</dd></div><div><dt>Available</dt><dd>${esc(c.availability)}</dd></div><div><dt>Expected</dt><dd>₹${Number(c.expectedPay).toLocaleString('en-IN')} · ${esc(c.workPreference)}</dd></div></dl><button class="button primary full" data-action="invite-candidate" data-candidate="${c.id}" data-opening="${j.id}">Invite to apply</button></article>`}

export function openingDetailScreen(state,worker=false){const j=opening(state),existing=state.jobApplications.find(a=>a.openingId===j.id&&a.candidateId===state.selectedCandidateId);return `${head(j.title,`${j.branch} · ${j.location}`)}<div class="grid two"><section class="panel"><div class="service-tags"><span>${esc(j.employmentType.replaceAll('_',' '))}</span><span>${j.count} positions</span></div><h2>₹${Number(j.payMin).toLocaleString('en-IN')}–₹${Number(j.payMax).toLocaleString('en-IN')} <small>${esc(j.payType.replaceAll('_',' '))}</small></h2><p>Start: ${esc(j.startDate)}</p><h3>Requirements</h3><ul>${j.requirements.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${worker?(existing?`<div class="info-banner"><b>Application: ${esc(existing.status)}</b><span>You can track or withdraw it here.</span></div><button class="button secondary" data-action="withdraw-application" data-application="${existing.id}">Withdraw application</button>`:`<button class="button primary" data-action="apply-opening" data-opening="${j.id}">Apply with profile</button>`):'<button class="button primary" data-route="findWorkers">Find matching workers</button>'}</section><aside class="panel"><h2>Access after hiring</h2><p>${j.employmentType==='trip_only'?'Only this trip or job. No full staff or branch access.':'A Staff ID is created with the selected branch and role permissions.'}</p><p><b>Approval:</b> ${esc(j.approvalPolicy)}</p></aside></div>`}

export function applicationsScreen(state){const jobs=state.vacancies.filter(x=>x.workspace===state.currentWorkspace),apps=state.jobApplications.filter(a=>jobs.some(j=>j.id===a.openingId));return `${head('Applicants','Move candidates through a clear hiring pipeline.')}<section class="panel"><div class="pipeline">${['new','reviewed','shortlisted','interview','offer','hired'].map(stage=>`<div><b>${esc(stage)}</b><span>${apps.filter(a=>a.status===stage).length}</span></div>`).join('')}</div><div class="people-list">${apps.map(a=>{const c=state.candidates.find(x=>x.id===a.candidateId),j=state.vacancies.find(x=>x.id===a.openingId);return `<article class="applicant-row"><span class="avatar">${esc(c.name.split(' ').map(n=>n[0]).join(''))}</span><span><b>${esc(c.name)}</b><small>${esc(j.title)} · Expected ₹${Number(a.expectedPay).toLocaleString('en-IN')}</small></span>${status(a.status)}<select data-action="change-application-status" data-application="${a.id}">${['new','reviewed','shortlisted','interview','offer','hired','rejected'].map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></article>`}).join('')}</div></section>`}

export function candidateProfileScreen(state){const c=candidate(state);return `${head('Work profile','One profile can support commercial driving, personal driving, Khalasi, Helper or staff work.')}<form id="candidate-profile-form" class="panel form-panel narrow"><div class="form-grid two"><label class="wide"><span>Name</span><input name="name" value="${esc(c.name)}"></label><fieldset class="wide"><legend>Work I can do</legend><div class="check-grid">${['driver','helper','operations','documents'].map(x=>`<label><input type="checkbox" name="capabilities" value="${x}" ${c.capabilities.includes(x)?'checked':''}> ${ROLE_TEMPLATES[x].label}</label>`).join('')}</div></fieldset><label><span>Location</span><input name="location" value="${esc(c.locations[0])}"></label><label><span>Availability</span><input name="availability" value="${esc(c.availability)}"></label><label><span>Work preference</span><select name="workPreference"><option ${c.workPreference==='Monthly'?'selected':''}>Monthly</option><option ${c.workPreference==='Per trip'?'selected':''}>Per trip</option><option>Daily</option></select></label><label><span>Expected pay</span><input name="expectedPay" type="number" value="${c.expectedPay}"></label></div><div class="form-actions"><button type="button" class="button secondary" data-route="home">Cancel</button><button class="button primary" type="submit">Save availability</button></div></form>`}

export function candidateWorkScreen(state){const c=candidate(state),jobs=state.vacancies.filter(j=>candidateMatches(c,j));return `${head('Find Work',`${c.name} · ${c.availability}`,'<button class="button secondary" data-route="candidateProfile">Update profile</button>')}<div class="job-list panel">${jobs.map(j=>jobRow(j)).join('')||'<div class="empty-inline"><b>No matching work today</b><small>Keep availability and location updated.</small></div>'}</div>`}

export function ownerCoverScreen(state){const eligible=people(state).filter(x=>['manager','operations','accounts'].includes(x.role)&&x.status==='active');return `${head('Owner Cover','Give a trusted staff member temporary operating access while the owner is unavailable.')}<div class="grid two"><form id="owner-cover-form" class="panel form-panel"><div class="form-grid two"><label class="wide"><span>Delegate</span><select name="delegateId"><option value="">Select staff</option>${eligible.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.designation)}</option>`).join('')}</select></label><label><span>From</span><input type="date" name="from" value="2026-09-28"></label><label><span>Until</span><input type="date" name="to" value="2026-10-05"></label><fieldset class="wide"><legend>Branches</legend><div class="check-grid">${branches(state).map(b=>`<label><input type="checkbox" name="branchIds" value="${b.id}" ${b.isDefault?'checked':''}> ${esc(b.name)}</label>`).join('')}</div></fieldset><label class="wide"><span>Payment approval limit</span><input name="paymentLimit" type="number" min="0" value="25000"></label></div><p id="owner-cover-error" class="field-error" hidden></p><button class="button primary full" type="submit">Activate Owner Cover</button></form><aside class="panel"><h2>Still blocked</h2><div class="owner-only">${OWNER_ONLY.map(p=>`<span>× ${esc(p.replaceAll('.',' · '))}</span>`).join('')}</div><p>Access automatically expires at the end date. Every action is recorded against the delegate.</p></aside></div><section class="panel cover-history"><h2>Active and previous cover</h2>${state.ownerCovers.length?state.ownerCovers.map(c=>`<div class="attention-item"><span class="attention-icon">☂</span><span class="attention-copy"><b>${esc(people(state).find(x=>x.id===c.delegateId)?.name||c.delegateId)}</b><small>${esc(c.from)} to ${esc(c.to)} · Limit ₹${Number(c.paymentLimit).toLocaleString('en-IN')}</small></span>${status(c.status)}</div>`).join(''):'<div class="empty-inline"><b>No Owner Cover</b><small>The owner currently controls all owner actions.</small></div>'}</section>`}

export function offboardingScreen(state){const x=staff(state),ready=canOffboard(x);return `${head('Offboard staff',`${x.name} · Future access stops; history and dues remain.`)}<div class="grid two"><section class="panel"><div class="review-checklist"><span class="${ready?'done':''}">${ready?'✓':'○'} Reassign active work (${x.activeAssignments.length})</span><span class="${!x.vehicleAssignments.length?'done':''}">${!x.vehicleAssignments.length?'✓':'○'} Remove vehicle assignments (${x.vehicleAssignments.length})</span><span class="done">✓ Preserve payment due ₹${Number(x.dues).toLocaleString('en-IN')}</span><span class="done">✓ Preserve messages and audit history</span></div>${!ready||x.vehicleAssignments.length?'<div class="action-warning"><b>Action required</b><span>Use automatic reassignment before completing offboarding.</span></div>':''}<button class="button secondary full" data-action="reassign-staff-work">Automatically reassign work</button><button class="button danger full" data-action="complete-offboarding">Complete offboarding</button></section><aside class="panel"><h2>After offboarding</h2><p>Future business access stops immediately. Past trips, tasks, salary, advances, documents and conversations stay attached to the Staff ID.</p></aside></div>`}

function empty(message){return `${head('People',message)}<button class="button primary" data-route="people">Back to People</button>`}
