import {HOME_CONTENT} from './mock-data.js';
import {ROUTES} from './config.js';

const esc=v=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const header=(title,description,action='')=>`<div class="page-header"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;

export function homeScreen(role,state){
  const h=HOME_CONTENT[role]||HOME_CONTENT.personal;
  const pending=state?.invitations?.filter(x=>x.status==='pending').length||0;
  const primaryAction=role==='personal'?'<button class="button primary" data-action="start-signup-demo">Test signup journey</button>':'<button class="button primary" data-route="states">Check shared states</button>';
  const attention=role==='personal'?`${pending?`<div class="attention-item"><span class="attention-icon">✉</span><span class="attention-copy"><b>${pending} business invitations</b><small>Review roles before joining</small></span><button class="status-pill info pill-button" data-route="invitations">Open</button></div>`:''}<div class="attention-item"><span class="attention-icon">+</span><span class="attention-copy"><b>Add or continue a business</b><small>Transport, fleet, movers and goods in one legal profile</small></span><button class="status-pill pill-button" data-route="businessStart">Open</button></div>`:'<div class="attention-item"><span class="attention-icon">!</span><span class="attention-copy"><b>One item needs review</b><small>Role-safe mock information</small></span><span class="status-pill warning">Review</span></div>';
  return `${header(h.greeting,h.summary,primaryAction)}
  <div class="grid two"><section class="panel"><div class="panel-header"><div><h2>Quick actions</h2><p>Only the actions relevant to this workspace</p></div></div><div class="shortcut-grid">${h.quick.map(x=>`<button class="shortcut" data-route="${x[0]}"><span class="shortcut-icon" aria-hidden="true">${x[1]}</span><b>${esc(x[2])}</b><small>${esc(x[3])}</small></button>`).join('')}</div></section>
  <section class="panel"><div class="panel-header"><div><h2>Needs attention</h2><p>Mock decisions for the current role</p></div></div><div class="attention-list">${attention}<div class="attention-item"><span class="attention-icon">✓</span><span class="attention-copy"><b>Workspace access is active</b><small>Navigation comes from centralized configuration</small></span><span class="status-pill">Ready</span></div></div></section></div>
  <div class="metrics">${h.metrics.map(x=>`<div class="metric"><span>${esc(x[0])}</span><b>${esc(x[1])}</b><small>${esc(x[2])}</small></div>`).join('')}</div>
  <div class="grid two"><section class="panel"><div class="panel-header"><div><h2>Recent activity</h2><p>Realistic mock information, not placeholder instructions</p></div></div><div class="activity-list"><div class="activity-item"><span class="activity-icon">▦</span><span class="activity-copy"><b>Current workspace loaded</b><small>Role navigation and permissions refreshed together</small></span><span class="status-pill info">Now</span></div><div class="activity-item"><span class="activity-icon">◷</span><span class="activity-copy"><b>Demo data ready</b><small>Reset is available from the sidebar</small></span><span class="status-pill">P0</span></div></div></section><section class="panel"><div class="panel-header"><div><h2>Foundation status</h2><p>Phase P0 release gate</p></div></div><p><b>Implemented:</b> shell, role navigation, route guard, workspace switching, responsive bottom navigation, shared states and reset.</p><button class="button secondary" data-route="states">Open state test lab</button></section></div>`;
}

export function placeholderScreen(route,roleLabel){const meta=ROUTES[route];return `${header(meta.title,`${roleLabel} · ${meta.phase} planned screen`)}<section class="panel screen-card"><span class="phase-tag">${meta.phase}</span><h2>${esc(meta.title)} route is connected</h2><p>The clean vNext shell already owns this route, navigation state and permission boundary. Feature content will be added in its planned phase without changing the shell or mutating role navigation.</p><div class="screen-actions"><button class="button primary" data-route="home">Back to Home</button><button class="button secondary" data-route="states">Check shared states</button></div></section>`}

export function statesScreen(){return `${header('Screen states','Reusable P0 states for every later phase')}<div class="state-demo"><article class="state-card"><span class="state-icon">◌</span><h3>Loading</h3><div class="skeleton"></div><div class="skeleton" style="width:70%"></div><p>Keep the current page stable while content loads.</p></article><article class="state-card"><span class="state-icon">□</span><h3>Empty</h3><p>No records yet. Explain the first useful action.</p><button class="button secondary" data-toast="First action opened">Create first item</button></article><article class="state-card"><span class="state-icon">!</span><h3>Error</h3><p>Could not load mock information. Existing work is safe.</p><button class="button secondary" data-toast="Retry successful">Retry</button></article><article class="state-card"><span class="state-icon">↻</span><h3>Pending sync</h3><p>Saved on this device and will retry when connection returns.</p><span class="status-pill warning">Waiting</span></article></div><section class="panel" style="margin-top:16px"><div class="panel-header"><div><h2>Route-guard test</h2><p>Use these actions to verify safe failures.</p></div></div><div class="screen-actions"><button class="button secondary" data-unknown-route>Open unknown route</button><button class="button secondary" data-forbidden-route>Open forbidden route</button></div></section>`}

export function notFoundScreen(){return `<section class="error-page"><div class="error-code">?</div><h1>Page not found</h1><p>This link does not exist in the vNext route registry.</p><button class="button primary" data-route="home">Go to Home</button></section>`}
export function deniedScreen(){return `<section class="error-page"><div class="error-code">×</div><h1>Access denied</h1><p>This workspace does not allow that screen. No information was loaded.</p><button class="button primary" data-route="home">Go to workspace Home</button></section>`}
