export const SEED={
  currentWorkspace:'personal', currentRoute:'home', demoRevision:2,
  auth:{status:'authenticated',mobile:'9876543210',mobileVerified:true,consentVersion:'2026-09-27',consentedAt:'2026-09-27T08:30:00.000Z',otpAttempts:0,otpSentAt:null,pendingMobile:null,isExistingIdentity:true},
  person:{id:'PER-1001',name:'Shubham Kumar'},
  workspaces:['personal','goods','transporter','vehicle','movers','commercialDriver','personalDriver','helper','admin'],
  badges:{transporter:{work:3,messages:4},vehicle:{work:2,messages:5},goods:{work:3,messages:2},movers:{work:4},admin:{approvals:7}},
  branches:{goods:['All branches','Patna Warehouse','Bihta Plant','Ranchi Depot'],transporter:['All branches','Noida HQ','Jaipur Branch'],vehicle:['All branches','Patna Yard'],movers:['All branches','Noida Moving Branch','Gurugram Branch']},
  knownIdentities:[{mobile:'9876543210',personId:'PER-1001',name:'Shubham Kumar',workspaces:['personal','goods','vehicle']}],
  invitations:[
    {id:'INV-2409',business:'Raj Logistics',workspace:'transporter',branch:'Noida HQ',role:'Operations Staff',invitedBy:'Amit Raj',mobile:'9876543210',expires:'30 Sep 2026',status:'pending'},
    {id:'INV-2412',business:'SafeMove Packers',workspace:'movers',branch:'Gurugram Branch',role:'Moving Coordinator',invitedBy:'Neha Singh',mobile:'9876543210',expires:'02 Oct 2026',status:'pending'},
    {id:'INV-2381',business:'Sharma Foods',workspace:'goods',branch:'Patna Warehouse',role:'Dispatch Staff',invitedBy:'Vijay Sharma',mobile:'9876543210',expires:'25 Sep 2026',status:'expired'},
  ],
  audit:[{id:'AUD-1',event:'Mobile verified',at:'27 Sep 2026, 8:30 AM',actor:'Shubham Kumar'}],
  currentApplicationId:'APP-2001',
  businessApplications:[
    {id:'APP-2001',ownerId:'PER-1001',ownerName:'Shubham Kumar',legalName:'Sinha Cargo & Movers',services:[],status:'draft',resumeSection:'services',version:1,details:{entityType:'Proprietorship',pan:'',gstin:'',address:''},documents:[],branches:[],bank:{accountName:'',accountNumber:'',ifsc:'',upi:'',verificationStatus:'not_added'},decisions:[],updatedAt:'27 Sep 2026, 10:45 AM'},
    {id:'APP-1988',ownerId:'PER-1188',ownerName:'Aarav Singh',legalName:'Aarav Freight Services',services:['transport','fleet'],status:'under_review',resumeSection:'review',version:2,details:{entityType:'Partnership',pan:'AAEFA7821K',gstin:'09AAEFA7821K1Z8',address:'Sector 62, Noida, Uttar Pradesh'},documents:[{type:'PAN',name:'aarav-pan.pdf',status:'uploaded'},{type:'GST certificate',name:'aarav-gst.pdf',status:'uploaded'},{type:'Business address proof',name:'noida-office.pdf',status:'uploaded'}],branches:[{id:'BR-A1',name:'Noida HQ',address:'Sector 62, Noida',serviceArea:'Delhi NCR',manager:'Aarav Singh',status:'active',isDefault:true,activeWork:0}],bank:{accountName:'Aarav Freight Services',accountNumber:'451278963214',ifsc:'HDFC0001842',upi:'aaravfreight@hdfc',verificationStatus:'verified'},decisions:[{version:1,decision:'correction_requested',reason:'GST certificate was unclear',section:'kyc',reviewer:'Admin Neha',at:'25 Sep 2026'}],updatedAt:'27 Sep 2026, 9:10 AM'},
    {id:'APP-1975',ownerId:'PER-1175',ownerName:'Meera Gupta',legalName:'North Star Movers',services:['movers'],status:'correction_required',resumeSection:'bank',version:1,details:{entityType:'Proprietorship',pan:'BKQPG4412C',gstin:'',address:'Vaishali, Ghaziabad'},documents:[{type:'PAN',name:'meera-pan.pdf',status:'uploaded'},{type:'Business address proof',name:'rental-agreement.pdf',status:'uploaded'},{type:'Service declaration',name:'moving-services.pdf',status:'uploaded'}],branches:[{id:'BR-N1',name:'Ghaziabad Branch',address:'Vaishali, Ghaziabad',serviceArea:'Ghaziabad and East Delhi',manager:'Meera Gupta',status:'active',isDefault:true,activeWork:0}],bank:{accountName:'Meera Gupta',accountNumber:'659014783212',ifsc:'ICIC0002241',upi:'',verificationStatus:'correction_required'},decisions:[{version:1,decision:'correction_requested',reason:'Account-holder name must match the submitted business proof.',section:'bank',reviewer:'Admin Neha',at:'26 Sep 2026'}],updatedAt:'26 Sep 2026, 5:30 PM'},
  ],
  businessProfiles:{
    transporter:{businessId:'BIZ-001',legalName:'Raj Logistics',services:['transport','fleet','movers'],kycStatus:'approved',bank:{maskedAccount:'•••• 3214',verificationStatus:'verified'},branches:[{id:'BR-001',name:'Noida HQ',serviceArea:'Delhi NCR',manager:'Ravi Kumar',status:'active',isDefault:true,activeWork:7},{id:'BR-002',name:'Jaipur Branch',serviceArea:'Rajasthan',manager:'Pankaj Meena',status:'active',isDefault:false,activeWork:2}]},
    goods:{businessId:'BIZ-002',legalName:'Sharma Foods',services:['goods','fleet'],kycStatus:'approved',bank:{maskedAccount:'•••• 9088',verificationStatus:'verified'},branches:[{id:'BR-010',name:'Patna Warehouse',serviceArea:'Bihar',manager:'Vijay Sharma',status:'active',isDefault:true,activeWork:3},{id:'BR-011',name:'Bihta Plant',serviceArea:'Bihar',manager:'Sunil Kumar',status:'active',isDefault:false,activeWork:0}]},
    vehicle:{businessId:'BIZ-006',legalName:'Raj Transport',services:['fleet'],kycStatus:'approved',bank:{maskedAccount:'•••• 7781',verificationStatus:'verified'},branches:[{id:'BR-020',name:'Patna Yard',serviceArea:'Bihar and Jharkhand',manager:'Rajesh Kumar',status:'active',isDefault:true,activeWork:2}]},
    movers:{businessId:'BIZ-009',legalName:'SafeMove Packers',services:['movers'],kycStatus:'approved',bank:{maskedAccount:'•••• 2204',verificationStatus:'verified'},branches:[{id:'BR-030',name:'Noida Moving Branch',serviceArea:'Delhi NCR',manager:'Neha Singh',status:'active',isDefault:true,activeWork:4},{id:'BR-031',name:'Gurugram Branch',serviceArea:'Gurugram',manager:'Ankit Rao',status:'active',isDefault:false,activeWork:0}]},
  },
};

export const HOME_CONTENT={
  personal:{greeting:'Good morning, Shubham',summary:'Your personal services and activity in one simple place.',metrics:[['Open orders','2','One arriving today'],['Service requests','1','Carpenter tomorrow'],['Invitations','2','Business access'],['Payments','₹1,850','This month']],quick:[['search','⌕','Search products','Find products directly'],['orders','▥','My orders','Track orders'],['messages','◌','Messages','Updates and support'],['invitations','✉','Invitations','Review business access']]},
  goods:{greeting:'Good morning, Shubham',summary:'Sharma Foods · owner view across every branch.',metrics:[['Active loads','3','One needs action'],['Owned vehicles','2','One idle'],['Staff','8','Across 3 branches'],['Open balance','₹40K','One settlement']],quick:[['work','▦','Loads','Create and track'],['fleet','▦','Fleet','Own use or available'],['people','♟','People','Staff and hiring'],['money','₹','Money','Freight and staff pay']]},
  transporter:{greeting:'Good morning, Shubham',summary:'Raj Logistics · Transport, Fleet and Movers with one shared team.',metrics:[['Loads waiting','3','Need vehicles'],['Available trucks','5','Two near Jaipur'],['Moving jobs','4','Today'],['Money due','₹1.24L','Six items']],quick:[['work','▦','Work','Loads and moving jobs'],['fleet','▦','Fleet','Owned and partner trucks'],['people','♟','People','Staff and marketplace workers'],['money','₹','Money','Advances and settlements']]},
  vehicle:{greeting:'Good morning, Rajesh',summary:'Raj Transport · trucks, people and payments.',metrics:[['Trucks','4','Three GPS online'],['On trip','2','Live tracking'],['Available','1','Jaipur'],['To receive','₹86K','Three settlements']],quick:[['fleet','▦','My Trucks','Documents and GPS'],['work','▦','Work','Offers and next loads'],['people','♟','People','Drivers and Khalasis'],['money','₹','Money','Advances and earnings']]},
  movers:{greeting:'Good morning, Shubham',summary:'SafeMove Packers · requests, crew and vehicles.',metrics:[['New requests','4','Auto-assigned'],['Today jobs','3','One loading'],['Available helpers','6','Across 2 branches'],['Payout due','₹22K','Partners and crew']],quick:[['work','▦','Moving jobs','Queue and allocation'],['fleet','▦','Vehicles','Owned and partners'],['people','♟','Crew','Drivers and helpers'],['money','₹','Money','Customer and payouts']]},
  commercialDriver:{greeting:'Good morning, Mohan',summary:'Your commercial work, availability and money.',metrics:[['Today trip','1','Patna to Delhi'],['Next offer','2','Review available'],['This month','₹38K','Earned'],['Documents','Valid','Licence checked']],quick:[['work','▦','My Work','Trip and offers'],['messages','◌','Messages','Trip groups'],['money','₹','My Money','Advance and wages'],['profile','○','Profile','Availability and documents']]},
  personalDriver:{greeting:'Good morning, Anil',summary:'Find personal driving work near you.',metrics:[['New jobs','8','Within 10 km'],['Applications','2','One shortlisted'],['This month','₹21K','Recorded'],['Availability','On','Until 8 PM']],quick:[['work','⌕','Find Work','Nearby requests'],['messages','◌','Messages','Customers and employers'],['money','₹','My Money','Work payments'],['profile','○','Profile','Skills and availability']]},
  helper:{greeting:'Good morning, Ramesh',summary:'Your Khalasi and moving-helper work.',metrics:[['Today task','1','Loading at 10 AM'],['New offers','3','Nearby'],['This month','₹19K','Recorded'],['Skills','3','Verified']],quick:[['work','▦','My Work','Trips and moving jobs'],['messages','◌','Messages','Assigned groups'],['money','₹','My Money','Advance and wages'],['profile','○','Profile','Skills and availability']]},
  admin:{greeting:'Platform operations',summary:'Verification, safety and audit queues.',metrics:[['Approvals','7','Three business'],['Documents','12','Four expiring'],['Safety cases','2','One urgent'],['Audit alerts','1','Payment access']],quick:[['approvals','✓','Approvals','Business and capability'],['documents','▣','Documents','People and vehicles'],['users','♟','Users','Support and status'],['audit','◷','Audit','Sensitive actions']]},
};
