import {maskMobile,MAX_OTP_ATTEMPTS} from './identity.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const step=(n,label,active=false,done=false)=>`<span class="journey-step ${active?'active':''} ${done?'done':''}"><i>${done?'✓':n}</i><small>${label}</small></span>`;
const steps=n=>`<div class="journey-steps" aria-label="Signup progress">${step(1,'Mobile',n===1,n>1)}${step(2,'Verify',n===2,n>2)}${step(3,'Ready',n===3,n>3)}</div>`;

export function welcomeScreen(){return `<section class="auth-layout"><div class="auth-brand"><span class="brand-mark">M</span><b>MoveAI One</b><p>One verified mobile. Personal and business workspaces stay separate and simple.</p></div><section class="auth-card"><span class="phase-tag">P1 · Identity</span><h1>Start with your mobile</h1><p>No long form. Verify once, then add business details only when you need them.</p><div class="benefit-list"><span><i>1</i><b>Verify mobile</b><small>OTP protects your identity</small></span><span><i>2</i><b>Personal space created</b><small>Always private and available</small></span><span><i>3</i><b>Accept work invites</b><small>Only invited business access</small></span></div><button class="button primary full" data-route="signup">Continue with mobile</button><button class="button text full" data-action="restore-seeded-demo">Open full demo instead</button></section></section>`}

export function signupScreen(state,error=''){return `<section class="auth-layout"><div class="auth-brand"><span class="brand-mark">M</span><b>MoveAI One</b><p>Use the number you keep with you. We will never create two people for one mobile.</p></div><section class="auth-card">${steps(1)}<h1>Enter mobile number</h1><p>We will send a 6-digit OTP.</p><form id="mobile-form" novalidate><label class="field-label" for="mobile">Mobile number</label><div class="phone-field"><span>+91</span><input id="mobile" name="mobile" inputmode="numeric" autocomplete="tel-national" maxlength="10" placeholder="98765 43210" value="${esc(state.auth.pendingMobile||'')}"></div><p id="mobile-error" class="field-error" ${error?'':'hidden'}>${esc(error)}</p><label class="consent-row"><input id="consent" name="consent" type="checkbox"><span>I agree to the <button type="button" class="inline-link" data-action="show-consent">Terms and Privacy Notice</button> and allow OTP verification.</span></label><button class="button primary full" type="submit">Send OTP</button></form><div class="mock-hint"><b>Test numbers</b><span>New: 9123456789 · Existing: 9876543210</span></div><button class="button text full" data-route="welcome">Back</button></section></section>`}

export function otpScreen(state,error=''){const attempts=state.auth.otpAttempts||0;return `<section class="auth-layout"><div class="auth-brand"><span class="brand-mark">M</span><b>MoveAI One</b><p>OTP confirmation links this phone to one person and keeps invitations safe.</p></div><section class="auth-card">${steps(2)}<h1>Verify your mobile</h1><p>Enter the OTP sent to <b>${maskMobile(state.auth.pendingMobile)}</b>.</p><form id="otp-form" novalidate><label class="field-label" for="otp">6-digit OTP</label><input class="otp-input" id="otp" name="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="• • • • • •"><p id="otp-error" class="field-error" ${error?'':'hidden'}>${esc(error)}</p><button class="button primary full" type="submit" ${attempts>=MAX_OTP_ATTEMPTS?'disabled':''}>Verify and continue</button></form><div class="otp-actions"><button class="button text" data-action="resend-otp">Resend OTP</button><button class="button text" data-route="signup">Change number</button></div><div class="mock-hint"><b>Prototype OTP</b><span>Use 123456 · ${MAX_OTP_ATTEMPTS-attempts} attempts left</span></div></section></section>`}

export function recoveryScreen(state){const identity=state.knownIdentities.find(x=>x.mobile===state.auth.pendingMobile)||state.knownIdentities[0];return `<section class="auth-layout"><div class="auth-brand"><span class="brand-mark">M</span><b>MoveAI One</b><p>Your verified mobile already belongs to one identity. Nothing will be duplicated.</p></div><section class="auth-card">${steps(3)}<span class="status-pill warning">Existing account found</span><h1>Welcome back, ${esc(identity.name)}</h1><p>${maskMobile(identity.mobile)} is already linked to this account.</p><div class="identity-summary"><span class="avatar">SK</span><span><b>${esc(identity.name)}</b><small>Personal + ${identity.workspaces.length-1} business workspaces</small></span></div><button class="button primary full" data-action="continue-existing">Continue to existing account</button><button class="button secondary full" data-action="wrong-account">This is not my account</button><p class="safety-note">Account changes require support verification. This prevents another person from taking over your business access.</p></section></section>`}

export function invitationsScreen(state){const pending=state.invitations.filter(x=>x.status==='pending');const history=state.invitations.filter(x=>x.status!=='pending');return `<div class="page-header"><div><h1>Pending invitations</h1><p>Business access sent to ${maskMobile(state.auth.mobile)}</p></div><span class="status-pill info">${pending.length} pending</span></div><section class="panel"><div class="panel-header"><div><h2>Review access</h2><p>Accept only a business and role you recognize.</p></div></div><div class="invitation-list">${pending.length?pending.map(invitationCard).join(''):'<div class="empty-inline"><b>No pending invitations</b><small>New invitations linked to your verified mobile will appear here.</small></div>'}</div></section><section class="panel history-panel"><div class="panel-header"><div><h2>Invitation history</h2><p>Expired and answered invitations</p></div></div><div class="invitation-list">${history.map(invitationCard).join('')}</div></section>`}

function invitationCard(x){const open=x.status==='pending';return `<article class="invitation-card"><span class="workspace-icon">${x.business.charAt(0)}</span><div class="invitation-copy"><b>${esc(x.business)}</b><span>${esc(x.role)} · ${esc(x.branch)}</span><small>Invited by ${esc(x.invitedBy)} · ${open?'Expires':'Expired'} ${esc(x.expires)}</small></div>${open?`<div class="invitation-actions"><button class="button primary" data-action="accept-invite" data-invite="${x.id}">Accept</button><button class="button secondary" data-action="reject-invite" data-invite="${x.id}">Decline</button></div>`:`<span class="status-pill ${x.status==='expired'?'warning':''}">${esc(x.status)}</span>`}</article>`}
