import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import {allowedRoutes} from '../js/config.js';
import {mobileNavigation} from '../js/navigation.js';
import * as W from '../js/grocery-workforce.js';
import * as Staff from '../js/grocery-staff.js';
import * as Pay from '../js/grocery-picker-pay.js';
import * as C from '../js/commerce.js';
import * as Orders from '../js/product-orders.js';

const s=structuredClone(SEED),today=new Date().toISOString().slice(0,10);
const okay=(result)=>assert.equal(result,'');
assert.ok(allowedRoutes('groceryManager').has('shopSchedule'));
assert.ok(!allowedRoutes('groceryManager').has('shopPickerPay'));
assert.ok(!allowedRoutes('groceryManager').has('shopOffboarding'));
assert.ok(allowedRoutes('picker').has('pickSchedule'));
assert.deepEqual(mobileNavigation('seller','groceryManager',[['home','Home'],['shopOrders','Orders'],['shopSchedule','Schedule'],['managerTimecards','Timecards']]).shown.map(x=>x[0]),['home','shopOrders','shopSchedule','managerTimecards']);
assert.match(C.screen(s,'shopTeam','grocery'),/Invite a branch manager/);
assert.match(C.screen(s,'managerProfile','groceryManager'),/Maya Manager/);
assert.match(C.screen(s,'shopSchedule','groceryManager'),/Publish shift/);
assert.match(C.screen(s,'pickSchedule','picker'),/My schedule/);
assert.match(C.screen(s,'commercePartners','admin'),/Managers/);

okay(W.inviteStoreManager(s,'grocery','Nina Supervisor','9876501299'));
const invited=s.storeManagers.at(-1);
assert.match(W.inviteStoreManager(s,'groceryFresh','Duplicate','9876501299'),/already in use/);
assert.match(W.acceptStoreManager(s,'groceryManager'),/No manager invitation/);
okay(W.selectStoreManager(s,'groceryManager',invited.id));
assert.match(C.screen(s,'shopSchedule','groceryManager'),/Accept manager invitation/);
okay(W.acceptStoreManager(s,'groceryManager'));
assert.match(W.removeStoreManager(s,'groceryFresh',invited.id),/not found/);
okay(W.selectStoreManager(s,'groceryManager','MGR-001'));

okay(Staff.invitePicker(s,'grocery','Priya Cover','9876501199'));
const cover=s.pickerStaff.at(-1);
okay(Staff.selectPicker(s,'picker',cover.id));okay(Staff.acceptPickerInvite(s,'picker'));okay(Pay.setPickerPayPlan(s,'grocery',cover.id,'daily',500));
assert.match(W.publishPickerShift(s,'groceryFreshManager',cover.id,today,'09:00','17:00'),/Choose an active picker/);
okay(W.publishPickerShift(s,'groceryManager',cover.id,today,'09:00','17:00'));
const roster=s.pickerSchedules.at(-1);
assert.match(Pay.startPickerShift(s,'picker'),/Confirm your scheduled shift/);
okay(W.respondPickerShift(s,'picker',roster.id,'cover'));
assert.match(Pay.startPickerShift(s,'picker'),/Confirm your scheduled shift/);
assert.match(W.reassignPickerShift(s,'groceryFreshManager',roster.id,'PICK-001'),/unavailable/);
okay(W.reassignPickerShift(s,'groceryManager',roster.id,'PICK-001'));
assert.equal(roster.pickerId,'PICK-001');
assert.match(C.screen(s,'pickSchedule','picker'),/No scheduled shifts/);
okay(Staff.selectPicker(s,'picker','PICK-001'));
okay(W.respondPickerShift(s,'picker',roster.id,'confirm'));
okay(Pay.startPickerShift(s,'picker'));okay(Pay.endPickerShift(s,'picker'));
const shift=s.pickerShifts.at(-1);
okay(W.requestPickerTimeCorrection(s,'picker',shift.id,'09:15','17:15','Clocked in late'));
const correction=s.pickerTimeCorrections.at(-1);
assert.match(Pay.approvePickerShift(s,'groceryManager',shift.id),/Resolve the time correction/);
assert.match(W.decidePickerTimeCorrection(s,'groceryFreshManager',correction.id,true),/unavailable/);
okay(W.decidePickerTimeCorrection(s,'groceryManager',correction.id,true));
assert.match(shift.startAt,/T09:15/);
okay(Pay.approvePickerShift(s,'groceryManager',shift.id));
assert.match(Pay.createPickerPayRun(s,'groceryManager','PICK-001'),/store access/);
assert.match(C.screen(s,'managerTimecards','groceryManager'),/Picker timecards/);
okay(Pay.createPickerPayRun(s,'grocery','PICK-001'));
const pay=s.pickerPayRuns.at(-1);okay(Pay.approvePickerPayRun(s,'grocery',pay.id));
assert.match(W.finalizePickerOffboarding(s,'grocery','PICK-001'),/Plan or revoke/);
okay(W.planPickerOffboarding(s,'grocery','PICK-001',today,'Voluntary exit'));
assert.match(W.finalizePickerOffboarding(s,'grocery','PICK-001'),/Resolve open tasks/);
okay(Pay.recordPickerPayment(s,'grocery',pay.id,'bank','TEST-FINAL-001'));

// Full customer order through the manager, picker, seller/courier and admin.
const placed=Orders.placeOrder(s,{productId:'PRD-101',qty:2,address:'Noida',method:'upi',vpa:'test@okaxis'}).order;
assert.match(C.sellerAction(s,'groceryFreshManager',placed.id,'accept'),/denied/);
okay(C.sellerAction(s,'groceryManager',placed.id,'accept'));
okay(Staff.assignPicker(s,'groceryManager',placed.id,'PICK-001'));
assert.match(W.finalizePickerOffboarding(s,'grocery','PICK-001'),/Resolve open tasks/);
okay(C.pickerAction(s,'picker',placed.id,'start'));
for(const item of placed.items)okay(C.pickerAction(s,'picker',placed.id,'check',item.productId));
okay(C.pickerAction(s,'picker',placed.id,'complete'));
okay(C.sellerAction(s,'groceryManager',placed.id,'pack',1));
assert.equal(placed.deliveryAssignment.partnerName,'Ravi Delivery');
okay(C.deliveryAction(s,'deliveryPartner',placed.id,'accept'));
okay(C.deliveryAction(s,'deliveryPartner',placed.id,'pickup',placed.pickupCode,1));
okay(C.deliveryAction(s,'deliveryPartner',placed.id,'deliver',placed.deliveryCode));
assert.equal(placed.status,'delivered');
assert.match(Orders.ordersScreen(s),new RegExp(placed.id));
s.selectedTrackingOrderId=placed.id;assert.match(Orders.trackingScreen(s),/Delivered|delivered/);
assert.ok(s.notifications.some(n=>n.to==='groceryManager'&&n.ref===placed.id));
assert.match(C.screen(s,'commerceOrders','admin'),new RegExp(placed.id));
okay(W.finalizePickerOffboarding(s,'grocery','PICK-001'));
assert.equal(s.pickerStaff[0].status,'offboarded');
assert.match(Pay.startPickerShift(s,'picker'),/Active picker/);
assert.match(C.screen(s,'shopOffboarding','grocery'),/completed/);
assert.match(C.screen(s,'commercePartners','admin'),/offboarded/);
assert.match(C.sellerAction(s,'groceryManager',placed.id,'pack',1),/current stage/);
okay(W.removeStoreManager(s,'grocery','MGR-001'));
assert.match(C.sellerAction(s,'groceryManager',placed.id,'accept'),/denied/);
console.log(JSON.stringify({status:'PASS',suite:'Manager invitation, shift cover, time correction, final pay, picker exit, full grocery fulfilment',order:placed.id,manager:invited.name,picker:s.pickerStaff[0].status}));
