import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import * as I from '../js/grocery-inventory.js';
import * as C from '../js/commerce.js';
const s=structuredClone(SEED),ok=x=>assert.equal(x,'');
const rice=s.products.find(x=>x.id==='PRD-101'),salt=s.products.find(x=>x.id==='PRD-103'),riceQty=rice.quantity,saltQty=salt.quantity;
ok(I.openCounterShift(s,'grocery',2000));assert.match(I.openCounterShift(s,'grocery',0),/already open/);
ok(I.addCounterItem(s,'groceryManager',rice.id,1));ok(I.updateCounterCart(s,'groceryManager',rice.id,2));ok(I.addCounterItem(s,'groceryManager',salt.id,1));assert.match(I.updateCounterCart(s,'groceryManager',salt.id,999),/valid/);
const bad=I.prepareCounterSale(s,'grocery',{payments:[{method:'cash',amount:500,tendered:500},{method:'upi',amount:200,reference:'UPI-123'}]});assert.match(bad.error,/add up/);assert.equal(rice.reserved||0,0);
const params={customer:'Walk-in',discount:0,payments:[{method:'cash',amount:500,tendered:600},{method:'upi',amount:976,reference:'UPI-123'}]};
// The second tender must match the actual item total, not an assumed total.
assert.match(I.prepareCounterSale(s,'grocery',params).error,/add up/);params.payments[1].amount=2*rice.price+salt.price-500;
const prepared=I.prepareCounterSale(s,'grocery',params);assert.ok(prepared.sale,prepared.error);const sale=prepared.sale;assert.equal(sale.status,'awaiting_confirmation');assert.equal(sale.cashChange,100);assert.equal(rice.quantity,riceQty);assert.equal(rice.reserved,2);assert.equal(s.ledger.filter(e=>e.sourceId===sale.id).length,0);assert.match(I.updateCounterCart(s,'grocery',rice.id,0),/pending/);assert.match(I.closeCounterShift(s,'grocery',2000),/pending/);
assert.match(I.confirmCounterSale(s,'groceryFresh',sale.id,true),/not found/);ok(I.confirmCounterSale(s,'groceryManager',sale.id,true));assert.equal(sale.status,'paid');assert.equal(rice.quantity,riceQty-2);assert.equal(salt.quantity,saltQty-1);assert.equal(rice.reserved,0);assert.equal(s.ledger.filter(e=>e.sourceId===sale.id&&e.type==='customer_payment').length,2);assert.equal(s.ledger.filter(e=>e.sourceId===sale.id&&e.type==='customer_payment').reduce((n,e)=>n+e.amount,0),sale.total);assert.match(I.confirmCounterSale(s,'grocery',sale.id,true),/not found/);
assert.match(I.returnCounterItems(s,'grocery',sale.id,salt.id,2,'sellable','upi','R1'),/quantity/);assert.match(I.returnCounterItems(s,'grocery',sale.id,salt.id,1,'sellable','upi',''),/reference/);ok(I.returnCounterItems(s,'grocery',sale.id,salt.id,1,'sellable','upi','REF-SALT'));assert.equal(sale.status,'partial_return');assert.equal(salt.quantity,saltQty);assert.match(I.returnCounterItems(s,'grocery',sale.id,salt.id,1,'sellable','upi','REF-SALT'),/quantity/);
ok(I.returnCounterItems(s,'grocery',sale.id,rice.id,1,'damaged','cash'));assert.equal(rice.quantity,riceQty-2);ok(I.returnCounterItems(s,'grocery',sale.id,rice.id,1,'sellable','cash'));assert.equal(sale.status,'returned');assert.equal(sale.refundedAmount,sale.total);assert.equal(rice.quantity,riceQty-1);
const shift=s.counterShifts.find(x=>x.status==='open'),sum=I.counterShiftSummary(s,shift);assert.equal(sum.cashExpected,2000+500-s.ledger.filter(e=>e.sourceId===sale.id&&e.type==='refund'&&e.method==='cash').reduce((n,e)=>n+e.amount,0));assert.equal(sum.upi,sale.payments.find(x=>x.method==='upi').amount);assert.match(I.closeCounterShift(s,'grocery',sum.cashExpected-20),/Explain/);ok(I.closeCounterShift(s,'grocery',sum.cashExpected-20,'₹20 drawer shortage reviewed'));assert.equal(shift.status,'closed_with_difference');assert.equal(shift.difference,-20);assert.equal(s.ledger.find(e=>e.sourceId===shift.id).type,'counter_shift_reconciliation');assert.match(C.screen(s,'shopCounter','groceryManager'),/closed_with_difference/);
// Declined payment releases a separate reserved cart without charging or reducing stock.
ok(I.addCounterItem(s,'grocery',salt.id,1));const declined=I.prepareCounterSale(s,'grocery',{payments:[{method:'card',amount:salt.price,reference:'POS-DECLINED'}]}).sale;assert.equal(salt.reserved,1);assert.match(I.confirmCounterSale(s,'grocery',declined.id,false,''),/reason/);ok(I.confirmCounterSale(s,'grocery',declined.id,false,'Terminal declined'));assert.equal(declined.status,'voided');assert.equal(salt.reserved,0);assert.equal(s.ledger.filter(e=>e.sourceId===declined.id).length,0);
// A return on a later shift changes that shift's cash, not the original shift.
const later=freshClone();
function freshClone(){return structuredClone(SEED)}
ok(I.openCounterShift(later,'grocery',1000));ok(I.addCounterItem(later,'grocery',salt.id,1));const first=I.prepareCounterSale(later,'grocery',{payments:[{method:'cash',amount:salt.price,tendered:salt.price}]}).sale;ok(I.confirmCounterSale(later,'grocery',first.id,true));ok(I.closeCounterShift(later,'grocery',1000+salt.price));const closed=later.counterShifts[0];ok(I.openCounterShift(later,'grocery',500));ok(I.returnCounterItems(later,'grocery',first.id,salt.id,1,'damaged','cash'));assert.equal(I.counterShiftSummary(later,closed).refunds,0);assert.equal(I.counterShiftSummary(later,later.counterShifts[0]).cashExpected,500-salt.price);
// Discount allocation and card split still refund exactly the amount charged.
const discounted=structuredClone(SEED);ok(I.addCounterItem(discounted,'grocery',rice.id,1));ok(I.addCounterItem(discounted,'grocery',salt.id,1));const due=rice.price+salt.price-11;const discountSale=I.prepareCounterSale(discounted,'grocery',{discount:11,reason:'Promotion',payments:[{method:'cash',amount:100,tendered:120},{method:'card',amount:due-100,reference:'POS-001'}]}).sale;assert.equal(discountSale.total,due);ok(I.confirmCounterSale(discounted,'grocery',discountSale.id,true));ok(I.returnCounterItems(discounted,'grocery',discountSale.id,rice.id,1,'damaged','card','CARD-REF-1'));ok(I.returnCounterItems(discounted,'grocery',discountSale.id,salt.id,1,'sellable','card','CARD-REF-2'));assert.equal(discountSale.refundedAmount,discountSale.total);assert.equal(discountSale.cashChange,20);
// Check the same controls through the button handler used by the rendered screen.
const ui=structuredClone(SEED);ui.currentWorkspace='grocery';let saved=0;
function click(action,values={},id='',product=''){const button={dataset:{commerce:action,id,product}},root={querySelectorAll:sel=>sel==='[data-commerce]'?[button]:[],querySelector:sel=>sel in values?{value:values[sel]}:null};C.bind(root,{getState:()=>ui,save:()=>saved++,render:()=>{},toast:m=>{if(m!=='Updated')throw new Error(m)}});button.onclick()}
click('counter-add',{'[data-counter-product]':salt.id,'[data-counter-qty]':'1'});click('counter-prepare',{'[data-counter-method]':'cash','[data-counter-amount]':String(salt.price),'[data-counter-tendered]':String(salt.price),'[data-counter-discount]':'0'});const viaUi=ui.counterSales[0];assert.equal(viaUi.status,'awaiting_confirmation');click('counter-confirm',{},viaUi.id);assert.equal(viaUi.status,'paid');assert.equal(saved,3);
assert.match(I.counterScreen(s,'grocery'),/Payment 2 \(optional\)/);assert.match(I.counterScreen(s,'grocery'),/cash drawer/i);
console.log(JSON.stringify({status:'PASS',suite:'Counter cart, split tender, change, manual confirmation, partial returns and shift reconciliation',sale:sale.id}));
