import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import * as Branches from '../js/seller-branches.js';
import * as Inventory from '../js/grocery-inventory.js';
import * as Shop from '../js/product-orders.js';
import * as Staff from '../js/grocery-staff.js';
import * as Pay from '../js/grocery-picker-pay.js';
import * as Commerce from '../js/commerce.js';
import {canOpen} from '../js/permissions.js';
const s=structuredClone(SEED),ok=v=>assert.equal(v,'');
for(const store of ['grocery','groceryFresh','electrical','fashion']){
 assert.ok(canOpen(store,'shopBranches'));
 assert.match(Commerce.screen(s,'shopBranches',store),/Store branches/);
 const second=`${store}-B2`;
 ok(Branches.selectBranch(s,store,second));
 assert.equal(Branches.selectedBranch(s,store),second);
 const category=store==='electrical'?'Electrical & lighting':store==='fashion'?'Fashion & clothing':'Fresh vegetables';
 const name=`${store} Noida demo item`;
 ok(Inventory.saveProduct(s,store,null,{name,size:'1 piece',category,vegStatus:store==='electrical'||store==='fashion'?'not_applicable':'vegetarian',price:210,quantity:5,lowStockAt:2,status:'active',brand:'Demo',sku:`${store}-NOI`}));
 const product=s.products.at(-1);
 assert.equal(Inventory.available(product,second),5);
 assert.equal(Inventory.available(product,`${store}-B1`),0);
 assert.match(Commerce.screen(s,'shopCatalog',store),/Noida demo item/);
 const order=Shop.placeOrder(s,{productId:product.id,qty:2,address:'Sector 62, Noida',method:'cod'}).order;
 assert.equal(order.branchId,second);
 assert.equal(order.pickupAddress,Branches.branch(s,store,second).address);
 assert.equal(Inventory.available(product,second),3);
 assert.doesNotMatch(Commerce.screen(s,'shopOrders',store),/No orders for this store/);
 assert.match(Commerce.screen(s,'shopOrders',store),new RegExp(order.id));
 const staff=Staff.staffFor(s,store).find(p=>p.status==='active');
 assert.ok(staff);
 ok(Commerce.sellerAction(s,store,order.id,'accept'));
 assert.match(Staff.assignPicker(s,store,order.id,staff.id),/Choose an active picker/);
 ok(Branches.assignStaffBranch(s,store,staff.id,second,true));
 ok(Staff.assignPicker(s,store,order.id,staff.id));
 assert.equal(order.pickerId,staff.id);
 ok(Branches.selectBranch(s,store,`${store}-B1`));
 assert.doesNotMatch(Commerce.screen(s,'shopOrders',store),new RegExp(order.id));
 assert.match(Commerce.screen(s,'shopBranches',store),/Noida/);
 ok(Branches.selectBranch(s,store,second));
 assert.match(Commerce.screen(s,'shopOrders',store),new RegExp(order.id));
 assert.match(Branches.assignStaffBranch(s,store==='grocery'?'fashion':'grocery',staff.id,second,true),/unavailable/);
 ok(Branches.toggleBranch(s,store,second));
 assert.match(Shop.placeOrder(s,{productId:product.id,qty:1,address:'Noida',method:'cod'}).error,/no active branch/);
 ok(Branches.toggleBranch(s,store,second));
 assert.match(Commerce.screen(s,'shopEarnings',store),/data-route="staffPay"/);
}
// A shift and pay run retains its branch for owner reconciliation.
const p=Staff.staffFor(s,'electrical').find(x=>x.status==='active');
const ws='pickerElectrical';
ok(Staff.selectPicker(s,ws,p.id));
ok(Branches.selectStaffBranch(s,ws,'electrical-B2'));
ok(Pay.setPickerPayPlan(s,'electrical',p.id,'daily',600));
ok(Pay.startPickerShift(s,ws));
assert.equal(s.pickerShifts.at(-1).branchId,'electrical-B2');
ok(Pay.endPickerShift(s,ws));
ok(Pay.approvePickerShift(s,'electrical',s.pickerShifts.at(-1).id));
ok(Pay.createPickerPayRun(s,'electrical',p.id));
const run=s.pickerPayRuns.at(-1);assert.equal(run.branchAllocation['electrical-B2'],600);
ok(Pay.approvePickerPayRun(s,'electrical',run.id));
ok(Pay.recordPickerPayment(s,'electrical',run.id,'upi','MOCK-EXTERNAL-123'));
assert.ok(s.ledger.some(x=>x.sourceId===run.id&&x.method==='upi'&&x.status==='confirmed'));
console.log('PASS four seller branches, products, routing, stock, staff scope, branch shifts and mock pay ledger');
