import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import * as HR from '../js/store-hr.js';
import * as T from '../js/staff-time.js';
import * as Pay from '../js/payroll-core.js';
import * as NC from '../js/notify-center.js';
const s=structuredClone(SEED),pid='PICK-001',store='grocery',branch='grocery-B1';
HR.people(s,store);Pay.ensurePayrollCore(s);
const real=new Date().toISOString().slice(0,10);
const nextMonday=Array.from({length:7},(_,i)=>i).find(i=>new Date(Date.now()+i*86400000).getUTCDay()===1);
s.simClockDays=nextMonday;globalThis.__moveaiClockOffset=nextMonday;
const monday=new Date(Date.now()+nextMonday*86400000).toISOString().slice(0,10);
const plus=n=>new Date(Date.parse(monday+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const fri=plus(4),sat=plus(5),sun=plus(6),tue=plus(1),wed=plus(2),m=monday.slice(0,7);
assert.equal(T.saveSchedule(s,store,pid,{weekdays:[1,2,3,4,5,6],effectiveFrom:monday,start:'09:00',end:'18:00'},'ABC Grocery'),'');
assert.match(T.saveSchedule(s,store,pid,{weekdays:[],effectiveFrom:monday,start:'09:00',end:'18:00'},'ABC Grocery'),/working day/);
assert.equal(T.scheduled(s,pid,sat),true);assert.equal(T.scheduled(s,pid,sun),false);
assert.equal(T.checkIn(s,store,pid,branch,monday),'');let d=s.staffDays.at(-1);
assert.equal(d.status,'pending');assert.match(HR.screen(s,'storeHR',store),/Attendance & leave/);
assert.equal(s.notifications[0].to,store);
assert.match(T.decideAttendance(s,store,d.id,'approve','Another branch manager','grocery-B2'),/another branch/);
assert.equal(T.decideAttendance(s,store,d.id,'approve','ABC Grocery',null),'');
assert.ok(NC.mine(s,'picker').some(n=>n.staffId===pid));
s.activePicker.picker='PICK-OTHER';assert.ok(!NC.mine(s,'picker').some(n=>n.staffId===pid));s.activePicker.picker=pid;
assert.equal(T.checkOut(s,store,pid,monday),'');
assert.match(T.checkIn(s,store,pid,branch,monday),/already recorded/);
assert.equal(T.requestLeave(s,store,pid,{from:tue,to:tue,units:1,reason:'Family'}),'');let l=s.staffLeaveRequests.at(-1);
assert.equal(l.dates.length,1);assert.match(T.requestLeave(s,store,pid,{from:sun,to:sun,units:1}),/no scheduled/);
assert.match(T.decideLeave(s,store,l.id,'approve','paid','Wrong manager','grocery-B2'),/another branch/);
assert.equal(T.decideLeave(s,store,l.id,'approve','paid','ABC Grocery',null),'');
s.simClockDays=nextMonday+2;globalThis.__moveaiClockOffset=s.simClockDays;
assert.equal(T.decideAbsence(s,store,pid,wed,'paid','ABC Grocery','Family emergency'),'');
assert.match(T.lockMonth(s,store,m,'ABC Grocery'),/Wait until the month ends/);
assert.match(HR.postEarnings(s,store),/lock this month/);
// A one-off Sunday shift is recorded by the owner, although Sunday is normally a rest day.
s.simClockDays=nextMonday+6;globalThis.__moveaiClockOffset=s.simClockDays;
assert.equal(HR.markDay(s,store,pid,sun,branch),'');assert.equal(s.staffDays.at(-1).extraShift,true);
// Worker reports the owner's entry as incorrect; owner keeps it with an audit trail.
const extra=s.staffDays.at(-1);
assert.equal(T.disputeAttendance(s,store,pid,extra.id,'I worked at another branch'),'');
assert.equal(T.resolveDispute(s,store,extra.id,'approve','ABC Grocery',null),'');
assert.equal(extra.status,'approved');
const end=T.advanceDemoToMonthEnd(s);assert.equal(end.slice(0,7),m);
const q=T.summary(s,store,pid,m);assert.equal(q.present,1);assert.equal(q.extra,1);assert.equal(q.paidLeave,1);assert.equal(q.paidException,1);assert.equal(q.paidUnits,4);
assert.equal(T.lockMonth(s,store,m,'ABC Grocery'),'');assert.match(T.checkIn(s,store,pid,branch,end),/locked/);
const line=HR.payrollLines(s,store).find(x=>x.p.id===pid);
assert.equal(line.base,Math.round(12000*4/q.scheduled));
s.hrTab='time';assert.match(HR.screen(s,'storeHR',store),/paid leave/);
assert.match(HR.screen(s,'myHR','picker'),/My workdays & leave/);
assert.match(HR.screen(s,'myHR','picker'),/Family/);
assert.equal(HR.postEarnings(s,store),'');
Pay.ensurePayrollCore(s);const emp=s.employments.find(e=>e.business===store&&e.source.id===pid);const due=Pay.balance(s,emp.personId,store);
assert.equal(due,line.base+line.meal+line.coverPay);
assert.equal(HR.postEarnings(s,store),'');assert.equal(Pay.balance(s,emp.personId,store),due,'post is idempotent');
assert.equal(Pay.payMonthlySalary(s,store,emp.personId,m,'cash'),'');const cash=s.payEvents.findLast(e=>e.personId===emp.personId&&e.method==='cash'&&e.payroll);
assert.equal(Pay.balance(s,emp.personId,store),due);assert.equal(Pay.confirmCashPayment(s,cash.id,emp.personId,true),'');assert.equal(Pay.balance(s,emp.personId,store),0);
// Separate seller cannot see the worker or approve this store's leave.
assert.equal(HR.people(s,'fashion').some(p=>p.id===pid),false);
assert.match(T.decideLeave(s,'fashion',l.id,'approve','paid','City Fashion'),/not found/);
// Identity consent and masked owner view.
assert.match(HR.verifyStaff(s,pid,{dob:'1990-01-01',aadhaar:'234567890123',otp:'123456',selfie:'me.jpg',emergencyName:'Mom',emergencyMobile:'9876500000'}),/consent/i);
assert.equal(HR.verifyStaff(s,pid,{dob:'1990-01-01',aadhaar:'234567890123',otp:'123456',consent:'1',selfie:'me.jpg',emergencyName:'Mom',emergencyMobile:'9876500000'}),'');
s.hrTab='team';assert.match(HR.screen(s,'storeHR',store),/Aadhaar ending 0123/);
assert.doesNotMatch(HR.screen(s,'storeHR',store),/234567890123/);
assert.match(HR.screen(s,'storeHR',store),/Confirm ID match/);
assert.equal(HR.reviewIdentity(s,store,pid,'approve'),'');
assert.match(HR.screen(s,'myHR','picker'),/verified \/ approved/);
assert.equal(HR.setPayout(s,pid,{method:'bank',account:'12345678901',ifsc:'SBIN0001234',name:'Asha Picker'}),'');
assert.match(HR.screen(s,'storeHR',store),/••••8901/);
assert.doesNotMatch(HR.screen(s,'storeHR',store),/12345678901/);
console.log(JSON.stringify({status:'PASS',suite:'Seller/store staff schedule, check-in, leave, absence, Sunday shift, monthly lock, payslip, payment and masked verification',month:m,scheduled:q.scheduled,paid:q.paidUnits}));
globalThis.__moveaiClockOffset=0;

// A half-day request shares the date with a half shift and never pays more than one day.
const h=structuredClone(SEED);HR.people(h,'fashion');h.simClockDays=nextMonday;globalThis.__moveaiClockOffset=nextMonday;
const hp='PICK-004';
assert.equal(T.saveSchedule(h,'fashion',hp,{weekdays:[1,2,3,4,5],effectiveFrom:monday,start:'10:00',end:'19:00'},'City Fashion'),'');
assert.equal(T.requestLeave(h,'fashion',hp,{from:tue,to:tue,units:.5,reason:'Doctor'}),'');
const half=h.staffLeaveRequests.at(-1);
assert.equal(T.decideLeave(h,'fashion',half.id,'approve','paid','City Fashion'),'');
h.simClockDays=nextMonday+1;globalThis.__moveaiClockOffset=h.simClockDays;
assert.equal(T.checkIn(h,'fashion',hp,'fashion-B1',tue),'');
const halfDay=h.staffDays.at(-1);assert.equal(T.decideAttendance(h,'fashion',halfDay.id,'approve','City Fashion'),'');
const halfSummary=T.summary(h,'fashion',hp,m);
assert.equal(halfSummary.present,.5);assert.equal(halfSummary.paidLeave,.5);assert.equal(halfSummary.paidUnits,1);
assert.match(T.requestLeave(h,'fashion',hp,{from:tue,to:tue,units:1,reason:'Duplicate'}),/already marked present|already requested/);
// Worker payout change is used by the shared payment routine, even if an older source bank exists.
Pay.ensurePayrollCore(h);const he=h.employments.find(e=>e.business==='fashion'&&e.source.id===hp);
h.pickerStaff.find(x=>x.id===hp).bank={accountNumber:'11111111000'};h.pickerStaff.find(x=>x.id===hp).bankStatus='verified';
assert.match(HR.setPayout(h,hp,{method:'bank',account:'12345678000',ifsc:'SBIN0001234',name:'Pooja Store Staff'}),/different account holder/);
Pay.addReimbursement(h,'fashion',he.personId,{amount:500,note:'Work supplies'});
assert.match(Pay.payNow(h,'fashion',he.personId,500,'bank',''),/rejected|account/);
assert.equal(Pay.balance(h,he.personId,'fashion'),500);
assert.equal(HR.setPayout(h,hp,{method:'bank',account:'12345678901',ifsc:'SBIN0001234',name:'Pooja Store Staff'}),'');
assert.equal(Pay.payNow(h,'fashion',he.personId,500,'bank',''),'');assert.equal(Pay.balance(h,he.personId,'fashion'),0);
console.log(JSON.stringify({status:'PASS',suite:'Half-day leave, duplicate request and updated bank payout'}));
globalThis.__moveaiClockOffset=0;
const mgr=structuredClone(SEED);HR.people(mgr,'grocery');
assert.match(HR.screen(mgr,'myHR','groceryManager'),/My workdays & leave/);
assert.match(HR.markDay(mgr,'groceryManager','MGR-001',new Date().toISOString().slice(0,10),'grocery-B1'),/owner approves/);
console.log(JSON.stringify({status:'PASS',suite:'Manager self-service and owner-only self-attendance approval'}));
const shift=structuredClone(SEED);HR.people(shift,'groceryFresh');shift.simClockDays=nextMonday;globalThis.__moveaiClockOffset=nextMonday;
assert.equal(T.saveSchedule(shift,'groceryFresh','PICK-002',{weekdays:[1,2,3,4,5,6],effectiveFrom:monday,start:'08:00',end:'17:00'},'Fresh Mart'),'');
assert.equal(T.requestLeave(shift,'groceryFresh','PICK-002',{from:tue,to:tue,units:.5,reason:'Appointment'}),'');
assert.equal(T.decideLeave(shift,'groceryFresh',shift.staffLeaveRequests.at(-1).id,'approve','paid','Fresh Mart'),'');
shift.simClockDays=nextMonday+1;globalThis.__moveaiClockOffset=shift.simClockDays;
assert.equal(T.checkIn(shift,'groceryFresh','PICK-002','groceryFresh-B1',tue),'');
assert.equal(T.decideAttendance(shift,'groceryFresh',shift.staffDays.at(-1).id,'approve','Fresh Mart'),'');
T.advanceDemoToMonthEnd(shift);assert.equal(T.lockMonth(shift,'groceryFresh',m,'Fresh Mart'),'');
assert.equal(HR.payrollLines(shift,'groceryFresh').find(x=>x.p.id==='PICK-002').base,500);
assert.equal(HR.postEarnings(shift,'groceryFresh'),'');
console.log(JSON.stringify({status:'PASS',suite:'Paid half-day leave with daily shift rate'}));
globalThis.__moveaiClockOffset=0;
