import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import * as HR from '../js/store-hr.js';
import * as Pay from '../js/payroll-core.js';
const s=structuredClone(SEED),store='grocery',worker=s.pickerStaff.find(p=>p.store===store&&p.status==='active');
HR.people(s,store);Pay.ensurePayrollCore(s);const pid=worker.id,emp=s.employments.find(e=>e.source.id===pid&&e.business===store);
const mock={name:'test.png',type:'image/png',data:'data:image/png;base64,iVBORw0KGgo='};
const id={idType:'aadhaar',aadhaar:'234567890123',otp:'123456',consent:'1',dob:'1990-01-01',selfie:'selfie.png',emergencyName:'Mother',emergencyMobile:'9876543210',front:mock,back:mock};
assert.match(HR.verifyStaff(s,pid,{...id,back:null}),/both mock ID sides/);
assert.equal(HR.verifyStaff(s,pid,id),'');s.hrTab='team';
assert.match(HR.screen(s,'storeHR',store),/View ID front/);
assert.doesNotMatch(HR.screen(s,'storeHR','groceryManager'),/View ID front|234567890123|ID front/);
assert.equal(HR.escalateIdentity(s,store,pid,'Please check photo'), '');
assert.match(HR.platformStaffReviews(s),/Please check photo/);
assert.equal(HR.reviewIdentity(s,store,pid,'approve'),'No verified ID is waiting for store review.');
assert.equal(HR.platformIdentityDecision(s,pid,'cleared'),'');
assert.equal(HR.reviewIdentity(s,store,pid,'approve'),'');
const bank={method:'bank',name:worker.name,account:'12345678901',ifsc:'SBIN0001234',proof:mock,reviewRequired:true};
assert.equal(HR.setPayout(s,pid,bank),'');
assert.equal(Pay.runMonthlyPayroll(s,store,new Date().toISOString().slice(0,7)).lines.find(l=>l.personId===emp.personId).verified,false);
assert.match(HR.screen(s,'myHR','picker'),/Send payout details for review/);
assert.equal(HR.reviewPayout(s,'groceryManager',pid,'approve'),'Only this store owner reviews payout details.');
assert.equal(HR.reviewPayout(s,store,pid,'approve'),'');
assert.equal(Pay.runMonthlyPayroll(s,store,new Date().toISOString().slice(0,7)).lines.find(l=>l.personId===emp.personId).verified,true);
assert.equal(HR.setPayout(s,pid,{...bank,account:'12345678902'}),'');
assert.equal(s.staffHR[pid].previousPayout.accountNumber,'12345678901');
assert.equal(Pay.runMonthlyPayroll(s,store,new Date().toISOString().slice(0,7)).lines.find(l=>l.personId===emp.personId).verified,true,'approved old bank remains for current run');
assert.equal(HR.reviewPayout(s,store,pid,'correction','Upload a clearer cheque'),'');
assert.match(HR.screen(s,'myHR','picker'),/Upload a clearer cheque/);
assert.equal(HR.setPayout(s,pid,{...bank,account:'12345678903'}),'');
assert.equal(HR.reviewPayout(s,store,pid,'approve'),'');
assert.equal(s.staffHR[pid].payout.accountNumber,'12345678903');
assert.equal(HR.setPayout(s,pid,{method:'upi',upi:'asha@okaxis',name:worker.name,reviewRequired:true}),'');
assert.equal(s.staffHR[pid].payout.verified,false);
assert.equal(HR.reviewPayout(s,store,pid,'approve'),'');
assert.equal(s.staffHR[pid].payout.verified,true);
assert.equal(Pay.runMonthlyPayroll(s,store,new Date().toISOString().slice(0,7)).lines.find(l=>l.personId===emp.personId).verified,false,'UPI-only approval cannot enter bank batch');
assert.ok(s.staffCredentialHistory.filter(x=>x.personId===pid).length>=8);
console.log('PASS staff credentials: mock ID sides, owner/admin review, payout correction, old approved bank until new approval, payroll readiness');
