import assert from 'node:assert/strict';
import {SEED} from '../js/mock-data.js';
import * as HR from '../js/store-hr.js';
const s=structuredClone(SEED);HR.people(s,'grocery');const pid='PICK-001',mock={name:'demo-front.png',type:'image/png',data:'data:image/png;base64,iVBORw0KGgo='};
let ui=HR.screen(s,'myHR','picker');
assert.match(ui,/Demo identity prefilled/);assert.match(ui,/data-id-path="otp"/);assert.match(ui,/data-id-path="offline"/);assert.match(ui,/data-id-path="aadhaar_document"/);assert.match(ui,/data-id-path="other_document"/);
assert.match(ui,/Personal details · emergency contact/);const otp=ui.split('data-id-path="otp"')[1].split('data-id-path="offline"')[0];assert.doesNotMatch(otp,/name="front"|name="back"|name="emergencyMobile"/);
assert.match(HR.verifyStaff(s,pid,{method:'otp',aadhaar:'234567890123',otp:'123456',consent:'1'}),/Send demo OTP/);
assert.equal(HR.issueMockOtp(s,pid,'234567890123'),'');
assert.match(HR.verifyStaff(s,pid,{method:'otp',aadhaar:'234567890123',otp:'111111',consent:'1'}),/OTP/);
assert.equal(HR.verifyStaff(s,pid,{method:'otp',aadhaar:'234567890123',otp:'123456',consent:'1'}),'');
assert.equal(s.staffHR[pid].kyc.method,'otp');assert.equal(s.staffHR[pid].kyc.front,null);assert.match(HR.screen(s,'storeHR','grocery'),/Confirm worker joined/);
assert.equal(HR.reviewIdentity(s,'grocery',pid,'approve'),'');
assert.equal(HR.verifyStaff(s,pid,{method:'offline',idLast4:'0123',dob:'1990-01-01',selfie:'face.png',offlineFile:mock,consent:'1'}),'');
assert.equal(s.staffHR[pid].kyc.status,'submitted');assert.match(HR.screen(s,'myHR','picker'),/digital signature not checked/);
assert.match(HR.screen(s,'storeHR','grocery'),/Mock offline file/);
assert.equal(HR.reviewIdentity(s,'grocery',pid,'correction','QR not visible'),'');
assert.match(HR.screen(s,'myHR','picker'),/QR not visible/);
assert.match(HR.verifyStaff(s,pid,{method:'aadhaar_document',idLast4:'0123',dob:'1990-01-01',selfie:'face.png',front:mock,consent:'1'}),/both mock ID sides/);
assert.equal(HR.verifyStaff(s,pid,{method:'aadhaar_document',idLast4:'0123',dob:'1990-01-01',selfie:'face.png',front:mock,back:mock,consent:'1'}),'');
assert.match(HR.screen(s,'storeHR','grocery'),/Approve documents/);
assert.equal(HR.escalateIdentity(s,'grocery',pid,'Check photo'),'');assert.match(HR.platformStaffReviews(s),/Check photo/);
assert.equal(HR.platformIdentityDecision(s,pid,'cleared'),'');assert.equal(HR.reviewIdentity(s,'grocery',pid,'approve'),'');
assert.equal(HR.verifyStaff(s,pid,{method:'other_document',idLast4:'9876',dob:'1990-01-01',selfie:'face.png',front:mock,back:mock,consent:'1'}),'');
assert.equal(s.staffHR[pid].kyc.idType,'other');assert.doesNotMatch(HR.screen(s,'storeHR','groceryManager'),/View ID front|Confirm worker joined|Approve documents/);
assert.equal(HR.saveEmergencyContact(s,pid,{name:'Mother',mobile:'9876500000'}),'');assert.equal(s.staffHR[pid].kyc.emergency.mobile,'9876500000');
console.log('PASS staff ID paths: OTP, offline, Aadhaar manual, alternate ID, correction, escalation, personal contact, manager visibility');
