import assert from 'node:assert/strict';
import * as J from '../js/staff-join.js';
import * as W from '../js/worker-onboarding.js';
import {SEED} from '../js/mock-data.js';
const S=()=>JSON.parse(JSON.stringify(SEED));
const s=S();
const inv=J.prepareInvite(s,{id:'SINV-T',workspace:'transporter',name:'Test',mobile:'9876501177',role:'operations',branchId:'BR-001',payType:'monthly',employmentType:'permanent',status:'pending',history:[]});
assert.ok(inv.token&&inv.expiresAt>Date.now());
assert.match(J.validateNewInvite(s,{...inv,mobile:'9811000102'}).error,/own mobile/);
s.staffInvitations.push(inv);
assert.ok(J.validateNewInvite(s,{...inv,id:'X'}).duplicate,'duplicate detected');
assert.equal(J.inviteState(s,inv.token).inv.id,'SINV-T');
assert.equal(J.inviteState(s,'zzz').blocked,'not_found');
const old=inv.token;J.resendInvite(s,inv);assert.equal(J.inviteState(s,old).blocked,'replaced');
inv.expiresAt=Date.now()-1;assert.equal(J.inviteState(s,inv.token).blocked,'expired');inv.expiresAt=Date.now()+1e6;
const sess={};assert.match(J.checkMobile(sess,inv,'9999999999'),/ending 1177/);
for(let i=0;i<4;i++)J.checkOtp(sess,'000000');assert.equal(J.checkOtp(sess,'000000').locked,true);assert.match(J.checkOtp(sess,'123456').error,/Locked|Try again/);
sess.lockedUntil=0;assert.deepEqual(J.checkOtp(sess,'123456'),{});
assert.match(J.establishIdentity(s,sess,inv,'Test User',false),/terms/);
assert.equal(J.establishIdentity(s,sess,inv,'Test User',true),'');assert.ok(s.knownIdentities.some(k=>k.mobile==='9876501177'));
const n=s.knownIdentities.length;const sess2={verified:true};J.establishIdentity(s,sess2,inv,'',false);assert.equal(s.knownIdentities.length,n,'existing identity reused');
assert.equal(J.acceptInvite(s,sess,inv),'');const m=J.memberFor(s,inv);assert.equal(m.status,'profile_pending');assert.equal(inv.status,'accepted');
assert.match(J.validateJoining({dob:'1990-01-01',address:'A',idLast4:'1234',documentName:'id.jpg',emergencyName:'B',emergencyMobile:'9876501177',accountName:'T',accountNumber:'123456789',ifsc:'SBIN0001234',ownMobile:'9876501177'}),/someone else/);
// verified MoveAI Partner reuses Aadhaar + bank
const c={id:'C9',name:'Test User',mobile:'9876501177',workerType:'helper',checks:{},skills:['Loading / unloading']};s.candidates.push(c);W.ensureOnboarding(c);
const ws={candidates:[c],verificationQueue:[],audit:[],auth:{}};W.runCheck(ws,c,'aadhaar',{aadhaar:'234567891234',otp:'123456',consent:true});W.runCheck(ws,c,'selfie',{file:{name:'a.jpg'}});W.runCheck(ws,c,'bank',{account:'123456789',confirm:'123456789',ifsc:'SBIN0001234'});W.runCheck(ws,c,'emergency',{name:'Z',phone:'9811111111'});
const partner=J.partnerProfile(s,'9876501177');assert.ok(partner,'partner profile found');
assert.equal(J.validateJoining({dob:'1990-01-01',address:'A',idLast4:'1234',emergencyName:'B',emergencyMobile:'9811111112',reused:true,ownMobile:'9876501177'}),'','no ID upload or bank needed when reused');
J.submitJoining(s,inv,m,{dob:'1990-01-01',address:'A',idLast4:'1234',emergencyName:'B',emergencyMobile:'9811111112',reused:true},partner);assert.equal(m.bank.source,'Reused from MoveAI Partner');assert.equal(inv.status,'submitted');
J.declineInvite(s,{},{...inv,status:'pending',history:[]},'x');
console.log(JSON.stringify({status:'PASS',suite:'Staff invitation link rules'},null,2));
