import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {SEED} from '../js/mock-data.js';
import * as Shop from '../js/product-orders.js';
import * as Commerce from '../js/commerce.js';
import * as Inventory from '../js/grocery-inventory.js';
import {canOpen} from '../js/permissions.js';

const s=structuredClone(SEED);
assert.ok(canOpen('electrical','shopIssues')&&canOpen('electricalManager','shopIssues'));
assert.ok(!canOpen('pickerElectrical','shopIssues'));
assert.match(Commerce.screen(s,'shopIssues','electrical'),/No store exceptions/);
const o=Shop.placeOrder(s,{productId:'PRD-201',qty:1,address:'Delhi',method:'cod'}).order;
assert.equal(Commerce.sellerAction(s,'electrical',o.id,'accept'),'');
assert.equal(Commerce.storeExceptions(s,'electrical')[0].reason,'No staff assigned or available');
assert.equal(Commerce.storeExceptions(s,'fashion').length,0);
assert.match(Commerce.screen(s,'shopIssues','electricalManager'),new RegExp(o.id));
assert.equal(Commerce.pickerAction(s,'electrical',o.id,'start'),'');
assert.match(Commerce.pickerAction(s,'electrical',o.id,'check','PRD-201'),/product-specific/);
assert.match(Commerce.screen(s,'shopOrders','electrical'),/Model \/ wattage matches order/);
assert.equal(Commerce.pickerAction(s,'electrical',o.id,'check','PRD-201',[true,true]),'');
assert.deepEqual(o.pick.quality['PRD-201'].map(x=>x.confirmed),[true,true]);
assert.equal(Commerce.pickerAction(s,'electrical',o.id,'uncheck','PRD-201'),'');
assert.equal(o.pick.quality['PRD-201'],undefined);
assert.match(Commerce.pickerAction(s,'electrical',o.id,'complete'),/product-specific/);
assert.equal(Commerce.pickerAction(s,'electrical',o.id,'check','PRD-201',[true,true]),'');
assert.equal(Commerce.pickerAction(s,'electrical',o.id,'complete'),'');
o.pick.completedAt=Date.now()-16*60000;
assert.equal(Commerce.storeExceptions(s,'electrical')[0].reason,'Picking complete; packing delayed');
assert.equal(Commerce.sellerAction(s,'electrical',o.id,'pack',1),'');
o.deliveryAssignment.offeredAt=Date.now()-11*60000;
assert.equal(Commerce.storeExceptions(s,'electrical')[0].reason,'Courier offer expired');

assert.equal(Inventory.saveProduct(s,'groceryFresh',null,{name:'Fresh Tomato',size:'1 kg',category:'Fresh vegetables',subcategory:'',vegStatus:'vegetarian',price:60,quantity:10,lowStockAt:2,status:'active'}),'');
const tomato=s.products.at(-1),fresh=Shop.placeOrder(s,{productId:tomato.id,qty:1,address:'Delhi',method:'cod'}).order;
assert.equal(Commerce.sellerAction(s,'groceryFresh',fresh.id,'accept'),'');
assert.equal(Commerce.pickerAction(s,'groceryFresh',fresh.id,'start'),'');
assert.match(Commerce.pickerAction(s,'groceryFresh',fresh.id,'check',tomato.id),/product-specific/);
assert.equal(Commerce.pickerAction(s,'groceryFresh',fresh.id,'check',tomato.id,[true,true]),'');
assert.match(Commerce.screen(s,'shopOrders','groceryFresh'),/Fresh Tomato/);
assert.match(readFileSync(new URL('../demo-guide.html',import.meta.url),'utf8'),/index.html#\/search/);
assert.match(readFileSync(new URL('../demo-guide.html',import.meta.url),'utf8'),/delivery.html#\/deliveryJobs/);
console.log('PASS store exception queue, category checks, cross-store isolation and demo guide');
